Fix syntax for task.ext.use_cache for ensemblvep and snpeff
nf-core/modules pull request #1105
Opened 2021-11-30 16:08 UTC by maxulysse

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-11-30 16:35 UTC, maxulysse commented on modules/ensemblvep/main.nf
> +        !task.ext.use_cache ?
```suggestion
        task.ext.use_cache ?
```

2021-11-30 16:35 UTC, maxulysse commented on modules/snpeff/main.nf
> +        !task.ext.use_cache ?
```suggestion
        task.ext.use_cache ?
```

2021-12-06 11:58 UTC, FriederikeHanssen requested changes

2021-12-06 11:58 UTC, FriederikeHanssen commented on modules/ensemblvep/main.nf
>      def prefix = task.ext.suffix ? "${meta.id}${task.ext.suffix}" : "${meta.id}"
This needs to be updated with the new suffix annotation. I think like this:
```suggestion
    def suffix = task.ext.prefix ?: "${task.ext.prefix}"
```

2021-12-06 11:58 UTC, FriederikeHanssen commented on modules/snpeff/main.nf
>      def prefix = task.ext.suffix ? "${meta.id}${task.ext.suffix}" : "${meta.id}"
same here: 
```suggestion
    def suffix = task.ext.prefix ?: "${task.ext.prefix}"
```

2021-12-06 11:59 UTC, FriederikeHanssen approved these changes

2021-12-06 11:59 UTC, merged