Dragmap
nf-core/modules pull request #1108
Opened 2021-12-01 03:13 UTC by Emiller88

Closes #1106

2021-12-01 09:05 UTC, JoseEspinosa requested changes
Very nice job @Emiller88 ! 
Just suggested whether it would be more optimal to output `bam` files directly (although this will need a mulled container 🙄) and also whether you plan to add the alt-masked bed file test on this iteration.

2021-12-01 14:52 UTC, Emiller88 commented on modules/dragmap/align/main.nf
> +
Yeah, I think that's what needs to happen. Same thing as the other aligners, to save on jobs, storage, etc.

2021-12-06 08:49 UTC, JoseEspinosa approved these changes
Awseome @Emiller88 ! 🚀

2021-12-06 08:49 UTC, JoseEspinosa commented on modules/dragmap/align/meta.yml
> +    - sam:
```suggestion
    - bam:
```

2021-12-06 08:56 UTC, merged