Update all subworkflows to new NF syntax
nf-core/modules pull request #1187
Opened 2021-12-22 10:18 UTC by drpatelh

2021-12-22 15:16 UTC, GCJMackenzie requested changes
The gatk subworkflows were failing due to the recent changes in test datasets to prevent empty files being generated, reference files needed to be updated to use the chr21 references rather than the old chr22. These changes should get the tests working again.

2021-12-22 15:16 UTC, GCJMackenzie commented on tests/subworkflows/nf-core/gatk_create_somatic_pon/main.nf
> +    interval_file = file(params.test_data['homo_sapiens']['genome']['genome_interval_list'], checkIfExists: true)
```suggestion
    fasta         = file(params.test_data['homo_sapiens']['genome']['genome_21_fasta'], checkIfExists: true)
    fai           = file(params.test_data['homo_sapiens']['genome']['genome_21_fasta_fai'], checkIfExists: true)
    dict          = file(params.test_data['homo_sapiens']['genome']['genome_21_dict'], checkIfExists: true)
    pon_name      = "test_panel"
    interval_file = file(params.test_data['homo_sapiens']['genome']['genome_21_interval_list'], checkIfExists: true)
```

2021-12-22 15:16 UTC, GCJMackenzie commented on tests/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf
> +    interval_file         = file(params.test_data['homo_sapiens']['genome']['genome_interval_list'], checkIfExists: true)
```suggestion
    fasta                 = file(params.test_data['homo_sapiens']['genome']['genome_21_fasta'], checkIfExists: true)
    fai                   = file(params.test_data['homo_sapiens']['genome']['genome_21_fasta_fai'], checkIfExists: true)
    dict                  = file(params.test_data['homo_sapiens']['genome']['genome_21_dict'], checkIfExists: true)
    germline_resource     = file(params.test_data['homo_sapiens']['genome']['gnomad_r2_1_1_21_vcf_gz'], checkIfExists: true)
    germline_resource_tbi = file(params.test_data['homo_sapiens']['genome']['gnomad_r2_1_1_21_vcf_gz_tbi'], checkIfExists: true)
    panel_of_normals      = file(params.test_data['homo_sapiens']['genome']['mills_and_1000g_indels_21_vcf_gz'], checkIfExists: true)
    panel_of_normals_tbi  = file(params.test_data['homo_sapiens']['genome']['mills_and_1000g_indels_21_vcf_gz_tbi'], checkIfExists: true)
    interval_file         = file(params.test_data['homo_sapiens']['genome']['genome_21_interval_list'], checkIfExists: true)
```

2021-12-22 15:16 UTC, GCJMackenzie commented on tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf
> +    interval_file         = file(params.test_data['homo_sapiens']['genome']['genome_interval_list'], checkIfExists: true)
```suggestion
    fasta                 = file(params.test_data['homo_sapiens']['genome']['genome_21_fasta'], checkIfExists: true)
    fai                   = file(params.test_data['homo_sapiens']['genome']['genome_21_fasta_fai'], checkIfExists: true)
    dict                  = file(params.test_data['homo_sapiens']['genome']['genome_21_dict'], checkIfExists: true)
    germline_resource     = file(params.test_data['homo_sapiens']['genome']['gnomad_r2_1_1_21_vcf_gz'], checkIfExists: true)
    germline_resource_tbi = file(params.test_data['homo_sapiens']['genome']['gnomad_r2_1_1_21_vcf_gz_tbi'], checkIfExists: true)
    panel_of_normals      = file(params.test_data['homo_sapiens']['genome']['mills_and_1000g_indels_21_vcf_gz'], checkIfExists: true)
    panel_of_normals_tbi  = file(params.test_data['homo_sapiens']['genome']['mills_and_1000g_indels_21_vcf_gz_tbi'], checkIfExists: true)
    interval_file         = file(params.test_data['homo_sapiens']['genome']['genome_21_interval_list'], checkIfExists: true)
```

2022-10-11 09:28 UTC, Emiller88 commented
Closing because of https://github.com/nf-core/modules/pull/2097 https://github.com/nf-core/modules/pull/2101 https://github.com/nf-core/modules/pull/2156

2022-10-11 09:28 UTC, closed without merging