Antismashlite download databases
nf-core/modules pull request #1426
Opened 2022-03-21 16:54 UTC by jasmezz

This module downloads the antiSMASH databases (using the [lite version](https://quay.io/repository/biocontainers/antismash-lite) of antiSMASH).

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-03-21 19:54 UTC, jfy133 requested changes
Overall looks OK, I'm not sure about what the input parameter is going on here and you're missing a working test (as it doesn't include the actual db atm?)

2022-03-21 19:54 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +    val(database_dir)
This confuses me, the database isn't download yet, are you specifying 'where' the database should be downloaded?

I wouldn't do that - if necessary hardcode it into a dir name (e.g. antismash-dbs or something). NXF should deal with the location of internally downloaded files, and the `modules.config` file publishDir options can allow a user tosave this somewhere for re-use.

Alternative if this is necessary, use `prefix` instead

2022-03-21 19:54 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +
```suggestion
```

2022-03-21 19:54 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +    path(database_dir) , emit: database
This probably woudn't work, as you would have a conflict between the input/output varaible (NXF wouldn't know which to pick up... they can't be the same file.

2022-03-21 19:54 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/meta.yml
> +      description: Directory containing the user-specified path for the download of antiSMASH databases
See question above

2022-03-21 19:54 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/meta.yml
> +      pattern: "lib/python3.8/site-packages/antismash/databases/"
is this correct? Above you were saying this location was a user defined location?

2022-03-21 19:54 UTC, jfy133 commented on tests/modules/antismash/antismashlitedownloaddatabases/test.yml
> +      md5sum: e2656c8d2bcc7469eba40eb1ee5c91b3
Missing the actual DB path?

can be simply that it requirs `-path: /<oath>/<to>/<dir>`, don't need a md5sum (as not psossible for directories anyway)

2022-03-22 15:19 UTC, jasmezz commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +    val(database_dir)
```suggestion
```

2022-03-22 15:20 UTC, jasmezz commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +    path(database_dir) , emit: database
```suggestion
    path("antismash_db") , emit: database
```

2022-03-22 15:21 UTC, jasmezz commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +        $databases \\
```suggestion
        --database-dir antismash_db \\
```

2022-03-22 15:22 UTC, jasmezz commented on modules/antismash/antismashlitedownloaddatabases/meta.yml
> +
```suggestion
```

2022-03-22 15:22 UTC, jasmezz commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +
```suggestion
```

2022-03-22 15:24 UTC, jasmezz commented on modules/antismash/antismashlitedownloaddatabases/meta.yml
> +      pattern: "lib/python3.8/site-packages/antismash/databases/"
```suggestion
      description: Download directory for antiSMASH databases
      pattern: "antismash_db"
```

2022-03-22 15:26 UTC, jasmezz commented on tests/modules/antismash/antismashlitedownloaddatabases/main.nf
> +    ANTISMASH_ANTISMASHLITEDOWNLOADDATABASES ( input )
```suggestion
    ANTISMASH_ANTISMASHLITEDOWNLOADDATABASES ( )
```

2022-03-22 15:26 UTC, jasmezz commented on tests/modules/antismash/antismashlitedownloaddatabases/nextflow.config
> +}
```suggestion
}

```

2022-03-22 20:54 UTC, Midnighter approved these changes
Looks good to me! I haven't checked why the tests are failing but we can talk about that tomorrow.

I was wondering a little, though, if it's strictly necessary to have the download in nf-core modules rather than just as a local module in the funcscan pipeline... Did you discuss that at some point?

2022-03-22 20:54 UTC, Midnighter commented on tests/modules/antismash/antismashlitedownloaddatabases/test.yml
> +    - path: output/antismash/antismash_db
I would maybe test for the presence of a few more expected directories/files.

2022-04-07 12:54 UTC, Midnighter commented
So mounting the correct directory structure did not work out? Having such a long command might actually break things.

2022-04-20 08:32 UTC, jfy133 reviewed
In terms of modules guidelines wise, this looks OK now, however it comes across as very circular - your input is channels what you're downloading?

```
      description: antismash/outputs/html/css folder which is being created during the antiSMASH database downloading step
```

Is that correct?

I also agree with @Midnighter we should add more test paths, to check for but I think this is would otherwise be OK.

2022-04-20 09:50 UTC, jfy133 approved these changes
Once `meta.yml` is updated for describing the input channels are circular and this module is NOT recommended for pipeline use

Add a few more output files checks in the test.yml

2022-04-20 12:36 UTC, jfy133 approved these changes
DOCS! DOCS EVERYWHERE!

2022-04-20 12:36 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/meta.yml
> +      description: antismash/outputs/html/css folder which is being created during the antiSMASH database downloading step
```suggestion
      description: |
      antismash/outputs/html/css folder which is being created during the antiSMASH database downloading step. This is required due to particularities of antiSMASH that is not very compatible with container engines. These files are normally downloaded by download-antismash-databases itself, and must be retrieved by the use by manually running the command with conda or a standalone installation of antiSMASH. Therefore we do not recommend using this module for production pipelines, but rather require users to specify their own local copy of the antiSMASH database in pipelines.
```

2022-04-20 12:36 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/meta.yml
> +      description: antismash/modules folder which is being created during the antiSMASH database downloading step
```suggestion
      description: |
      These files are normally downloaded by download-antismash-databases itself, and must be retrieved by the use by manually running the command with conda or a standalone installation of antiSMASH. Therefore we do not recommend using this module for production pipelines, but rather require users to specify their own local copy of the antiSMASH database in pipelines.
```

2022-04-20 12:36 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +    input:
```suggestion
    
    input:
```

2022-04-20 12:36 UTC, jfy133 commented on modules/antismash/antismashlitedownloaddatabases/main.nf
> +    containerOptions {
```suggestion

    /* 
    These files are normally downloaded by download-antismash-databases itself, and must be retrieved for input by manually running the command with conda or a standalone installation of antiSMASH. Therefore we do not recommend using this module for production pipelines, but rather require users to specify their own local copy of the antiSMASH database in pipelines. This is solely for use for CI tests of the nf-core/module version of antiSMASH
    Reason: the tool on execution tries to modify contents of database files stored within the container itself based on the order of files according to their timestamp. During container construction these timestamps get incorrectly modified and the re-genration of the files within the container is attempted. By mounting the files it prevents the tool from trying to modify database files. 
    */
    
    containerOptions {
```

Or something...

2022-04-21 08:37 UTC, jfy133 commented
I approve merging now - singularity was working previously, currently biocontainer is down so the image can't be pulled.

2022-04-21 08:38 UTC, merged