Fix untar for centrifuge
nf-core/modules pull request #1472
Opened 2022-03-31 13:47 UTC by sofstam

Update centrifuge module so that the database is extracted using the untar module

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-03-31 19:04 UTC, jfy133 requested changes
Don't forget to update `meta.yml` to specify the database is now just a directory.

See my comment about the slightly ugly `-x` requirements by centrifuge and a possible solution to make it more flexible wihtin the nf-core module

2022-04-01 13:49 UTC, sofstam commented on modules/centrifuge/main.nf
> +        -x ${db}/${db} \\
Thank you for your comments.I will update the `meta.yml`

I did not like the solution with `-x`  either but a second parameter sounds a good idea. If I understand you suggestion, that would mean:

```
tuple val(meta), path(reads)
path db
val db_name
val save_unaligned
val save_aligned
val sam_format
```

2022-04-01 14:14 UTC, jfy133 commented on modules/centrifuge/main.nf
> +        -x ${db}/${db} \\
Yup exactly

2022-04-01 19:11 UTC, jfy133 approved these changes
Small suggestions to make tests slightly more smoother but otherwise I think we are good to go.

2022-04-01 19:11 UTC, jfy133 commented on modules/centrifuge/meta.yml
> +      description: Centrifuge filenames without the suffix ".cf"
```suggestion
      description: Centrifuge database filenames without the suffix ".cf"
```

2022-04-01 19:11 UTC, jfy133 commented on modules/centrifuge/main.nf
> +        -x ${db}/$db_name \\
```suggestion
        -x ${db}/${db_name} \\
```

2022-04-01 19:11 UTC, jfy133 commented on tests/modules/centrifuge/main.nf
> +    db_name = file('https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/delete_me/minigut_cf.tar.gz').toString().replace(".tar.gz","")
```suggestion
    db_name = "minigut_cf"
```

2022-04-01 19:11 UTC, jfy133 commented on tests/modules/centrifuge/main.nf
> +    db_name = file('https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/delete_me/minigut_cf.tar.gz').toString().replace(".tar.gz","")
Don't need to stage twice for these tests :+1:

2022-04-01 19:11 UTC, jfy133 commented on tests/modules/centrifuge/main.nf
> +     db_name = file('https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/delete_me/minigut_cf.tar.gz').toString().replace(".tar.gz","")
```suggestion
     db_name = "minigut_cf"
```

2022-04-04 08:15 UTC, sofstam commented
I committed your suggestions, thanks for all the comments. Shall I merge now?

2022-04-04 08:16 UTC, jfy133 commented
Go ahead!

2022-04-04 08:18 UTC, merged