picard CollectWgsMetrics: update to new cli args
nf-core/modules pull request #1578
Opened 2022-04-28 10:56 UTC by matthdsm

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-04-28 11:24 UTC, matthdsm commented
Dropped the bai index from the input tuple because it's unused and collides with the other picard metrics modules

2022-04-28 19:23 UTC, sateeshperi commented on modules/picard/collectwgsmetrics/main.nf
> +        -INPUT $bam \\
guess will have to update the other picard modules as well in one picard upgrade

2022-04-28 19:25 UTC, sateeshperi approved these changes
lgtm! will wait for another review though

2022-04-28 21:16 UTC, JoseEspinosa requested changes
Thanks @matthdsm! though maybe we could bump last Picard version

2022-04-28 21:16 UTC, JoseEspinosa commented on modules/picard/collectwgsmetrics/main.nf
>          'quay.io/biocontainers/picard:2.26.10--hdfd78af_0' }"
Maybe take the opportunity to bump version `2.27.1`?

2022-04-29 07:31 UTC, JoseEspinosa commented
> Whoops, missed that one! Should I do a bulk update of all the others too? In a separate PR of course.

If you fancy doing it :smile:

2022-04-29 07:32 UTC, JoseEspinosa approved these changes
Awesome @matthdsm :rocket:

2022-04-29 07:32 UTC, merged