Add ivar variants
nf-core/modules pull request #172
Opened 2021-02-15 19:52 UTC by andersgs

2021-02-15 19:58 UTC, andersgs commented
Weird it worked locally... I'll look in to it.

2021-02-15 20:00 UTC, andersgs commented
For logging purposes, it looks like this was the issue:

```
N E X T F L O W  ~  version 20.11.0-edge
Launching `./tests/software/ivar/variants/main.nf` [desperate_meninsky] - revision: eca6b56c86
Creating Conda env: bioconda::ivar=1.3.1 [cache /home/runner/pytest_workflow_qfumrxbk/ivar_variants_no_gff/work/conda/env-b6deb684c62494fb6921b1962c660b51]
Error executing process > 'test_ivar_variants_no_gff:IVAR_VARIANTS (test)'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /home/runner/pytest_workflow_qfumrxbk/ivar_variants_no_gff/work/conda/env-b6deb684c62494fb6921b1962c660b51 bioconda::ivar=1.3.1
  status : 1
  message:
    InvalidArchiveError("Error with archive /home/runner/conda_pkgs_dir/libnghttp2-1.43.0-h812cca2_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to create dir 'lib'")
```

2021-02-15 21:24 UTC, andersgs commented
> For logging purposes, it looks like this was the issue:
> 
> ```
> N E X T F L O W  ~  version 20.11.0-edge
> Launching `./tests/software/ivar/variants/main.nf` [desperate_meninsky] - revision: eca6b56c86
> Creating Conda env: bioconda::ivar=1.3.1 [cache /home/runner/pytest_workflow_qfumrxbk/ivar_variants_no_gff/work/conda/env-b6deb684c62494fb6921b1962c660b51]
> Error executing process > 'test_ivar_variants_no_gff:IVAR_VARIANTS (test)'
> 
> Caused by:
>   Failed to create Conda environment
>   command: conda create --mkdir --yes --quiet --prefix /home/runner/pytest_workflow_qfumrxbk/ivar_variants_no_gff/work/conda/env-b6deb684c62494fb6921b1962c660b51 bioconda::ivar=1.3.1
>   status : 1
>   message:
>     InvalidArchiveError("Error with archive /home/runner/conda_pkgs_dir/libnghttp2-1.43.0-h812cca2_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to create dir 'lib'")
> ```

This seem to fix itself by re-running... The docker and singularity images had incorrect URL and those are now fixed.

2021-02-15 22:50 UTC, drpatelh commented on software/ivar/variants/main.nf
> +
```suggestion
```

2021-02-15 23:11 UTC, drpatelh approved these changes
Thanks @andersgs. Some niggly things with syntax, channel and variable declaration but otherwise looking great!

2021-02-15 23:11 UTC, drpatelh commented on software/ivar/variants/main.nf
> +        -p $prefix
```suggestion
            $options.args \\
            $features \\
            -r $fasta \\
            -p $prefix
```

2021-02-15 23:11 UTC, drpatelh commented on software/ivar/variants/meta.yml
> +        pattern: "*.fa"
Add entry for `gff` here.

2021-02-15 23:11 UTC, drpatelh commented on software/ivar/variants/meta.yml
> +    - variants:
```suggestion
    - tsv:
```

2021-02-15 23:11 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +
```suggestion
params.gff = false

```

2021-02-15 23:11 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +params.gff = file("${launchDir}/tests/data/gff/sarscov2/MN908947.3.gff3", checkIfExists: true)
```suggestion
params.gff = "${launchDir}/tests/data/gff/sarscov2/MN908947.3.gff3"
```

2021-02-15 23:11 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +    IVAR_VARIANTS ( input, ref )
```suggestion
    def ref = file("${launchDir}/tests/data/fasta/sarscov2/MN908947.3.fa", checkIfExists: true)
    def gff = file(params.gff, checkIfExists: true)
    def input = []
    input = [ [ id:'test'], 
              file("${launchDir}/tests/data/bam/test-sc2-artic-v3-sorted-trimmed.bam", checkIfExists: true) ]
    IVAR_VARIANTS ( input, ref, gff )
```

2021-02-15 23:11 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +    IVAR_VARIANTS ( input, ref )
```suggestion
    def ref   = file("${launchDir}/tests/data/fasta/sarscov2/MN908947.3.fa", checkIfExists: true)
    def dummy = file("${launchDir}/tests/data/dummy/dummy_file.txt", checkIfExists: true)
    def input = []
    input = [ [ id:'test'], 
              file("${launchDir}/tests/data/bam/test-sc2-artic-v3-sorted-trimmed.bam", checkIfExists: true) ]
    IVAR_VARIANTS ( input, ref, dummy )
```

2021-02-15 23:11 UTC, drpatelh commented on tests/software/ivar/variants/test.yml
> +  command: nextflow run ./tests/software/ivar/variants -entry test_ivar_variants_no_gff -c tests/config/nextflow.config
Be good to add a test here with and without mpileup file output too.

2021-02-15 23:12 UTC, drpatelh requested changes
Commenting to actually request changes :)

2021-02-16 22:56 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +
```suggestion

params.gff = "${launchDir}/tests/data/gff/sarscov2/MN908947.3.gff3"
```

2021-02-16 22:57 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +}
```suggestion

params.gff = "${launchDir}/tests/data/gff/sarscov2/MN908947.3.gff3"

workflow test_ivar_variants_with_gff_with_mpileup {
    
    def ref = file("${launchDir}/tests/data/fasta/sarscov2/MN908947.3.fa", checkIfExists: true)
    def gff = file(params.gff, checkIfExists: true)
    def input = []
    input = [ [ id:'test'], 
              file("${launchDir}/tests/data/bam/test-sc2-artic-v3-sorted-trimmed.bam", checkIfExists: true) ]
    IVAR_VARIANTS ( input, ref, gff )
}
```

2021-02-16 22:58 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +workflow test_ivar_variants_no_gff_no_mpileup {
```suggestion

params.gff = false

workflow test_ivar_variants_no_gff_no_mpileup {
```

2021-02-16 23:00 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +params.gff = false
```suggestion
params.gff          = false
params.save_mpileup = false
```

2021-02-16 23:01 UTC, drpatelh commented on tests/software/ivar/variants/main.nf
> +workflow test_ivar_variants_no_gff_with_mpileup {
```suggestion

params.gff          = false
params.save_mpileup = true

workflow test_ivar_variants_no_gff_with_mpileup {
```

2021-02-16 23:20 UTC, drpatelh commented
Hmmm...something 🐟 going on here. Will merge and fix in a follow up PR. Thanks @andersgs  😎

2021-02-16 23:20 UTC, drpatelh approved these changes

2021-02-16 23:20 UTC, merged