New module: krakentools/kreport2krona
nf-core/modules pull request #1746
Opened 2022-06-09 13:57 UTC by MillironX

This module adds support for [KrakenTools](https://github.com/jenniferlu717/KrakenTools)' `kreport2krona` utility.

## PR checklist

Closes #1741 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-06-09 17:27 UTC, jfy133 requested changes
Pretty good! Main thing is taking out the custom clean up of the contents of the file (see comment).

2022-06-09 17:27 UTC, jfy133 commented on modules/krakentools/kreport2krona/main.nf
> +        -o ${prefix}.krona \\
I normally prefer to specify the fileformat as an extension (and also the out channel name), which would be `.txt` in this case, but it's not so strict if you strongly prefer krona.

2022-06-09 17:27 UTC, jfy133 commented on modules/krakentools/kreport2krona/main.nf
> +    sed -i "s/_/ /g" ${prefix}.krona
Whule it's useful, this stuff is 'custom' not natively support by the tool, which shouldn't be in the main module (we would make a local module in the pipeline for this), so it should be removed. If you'd be willing to make the local module for taxprofiler that woud be awesome (but no worries if you don't have time)!

2022-06-09 17:27 UTC, jfy133 commented on modules/krakentools/kreport2krona/meta.yml
> +      description: Krona text file converted from Kraken report
```suggestion
      description: Krona text-based input file converted from Kraken report
```

2022-06-09 17:27 UTC, jfy133 commented on tests/modules/krakentools/kreport2krona/test.yml
> +      md5sum: 4227755fe40478b8d7dc8634b489761e
```suggestion
```

2022-06-13 14:23 UTC, MillironX commented
Changes made: ready for re-review

2022-06-13 18:14 UTC, jfy133 approved these changes

2022-06-13 18:14 UTC, merged

2022-06-13 18:14 UTC, jfy133 commented
Thanks very much @MillironX !

Would you mind adding this into Taxprofiler now? And then you could re-add in a separate module the clean up thing.