Add gatk cnvcaller
nf-core/modules pull request #1755
Opened 2022-06-10 11:56 UTC by ryanjameskennedy

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-09-28 07:16 UTC, FriederikeHanssen commented on tests/modules/gatk4/annotateintervals/main.nf
> +// include { GATK4_PREPROCESSINTERVALS } from '../../../../modules/gatk4/preprocessintervals/main.nf'
the commented code can probably be removed?

2022-09-28 07:18 UTC, FriederikeHanssen commented on tests/modules/gatk4/determinegermlinecontigploidy/main.nf
> +    // model = file('/fs1/resources/ref/hg38/gatk_cnv/cnvref/ploidy-model/', checkIfExists: true)
this can probably be removed

2022-09-28 07:18 UTC, FriederikeHanssen commented on tests/modules/gatk4/determinegermlinecontigploidy/test.yml
> +## TODO nf-core: Please run the following command to build this file:
remove

2022-09-28 07:19 UTC, FriederikeHanssen requested changes
as a quick general feedback: there is a lot  of commented code and TODO statements that should be removed

2022-09-28 07:19 UTC, FriederikeHanssen commented on modules/gatk4/annotateintervals/main.nf
> +    path  "*.tsv"                 , emit: tsv
```suggestion
    path "*.tsv"                 , emit: tsv
```

2022-09-28 07:20 UTC, FriederikeHanssen commented on modules/gatk4/annotateintervals/main.nf
> +        -imr OVERLAPPING_ONLY \\
is it correct that this one parameter only has one dash? can you use the full name parameter for readability

2022-09-28 07:21 UTC, FriederikeHanssen commented on modules/gatk4/determinegermlinecontigploidy/main.nf
> +    // path  model
seems like model may be a possible file? In that case it should be provided as input

2022-09-28 07:21 UTC, FriederikeHanssen commented on modules/gatk4/filterintervals/main.nf
> +    --intervals $processed_intervals \\
can you intend the command for readability

2022-10-25 11:34 UTC, nvnieuwk commented
@ryanjameskennedy what's the status on this PR?

2022-12-15 15:10 UTC, closed without merging