entrezdirect/esearch module with tests
nf-core/modules pull request #1807
Opened 2022-06-24 03:53 UTC by alxndrdiaz

## PR checklist

Closes #1771 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-06-30 13:45 UTC, priyanka-surana commented on modules/entrezdirect/esearch/main.nf
> +    val spell_check
Do we really need these optional values? Why can't they be part of `ext.args`?

2022-06-30 20:36 UTC, muffato commented on modules/entrezdirect/esearch/main.nf
> +    val spell_check
Good point, and that would address https://github.com/nf-core/modules/pull/1807#discussion_r910839779

2022-07-06 18:54 UTC, alxndrdiaz commented
For check: Pytest-workflow / entrezdirect/esearch conda (pull_request)  I have been unable to reproduce the error, pytest works fine locally.

2022-07-12 19:20 UTC, muffato requested changes
Same as in #1833

2022-07-12 19:20 UTC, muffato commented on modules/entrezdirect/esearch/main.nf
> +        esearch: \$(echo \$(esearch -version 2>&1) | sed 's/^esearch //; s/Using.*\$//' ))
```suggestion
        esearch: \$(esearch -version)
```

2022-07-14 07:22 UTC, jfy133 approved these changes
LGTM!

2022-07-14 10:17 UTC, muffato reviewed
Looks good to me as well. Just make sure you rebase/merge as necessary to resolve the conflict in `pytest_modules.yml` (likely due to the merge of #1833).

Also, why can't you use MD5 checksums in `test.yml` ?

2022-07-15 16:12 UTC, muffato approved these changes

2022-07-22 19:36 UTC, jfy133 reviewed
I'm not sure what's changed but your output files don't contain some of your strings in all cases:

```
FAILED tests/modules/entrezdirect/esearch/test.yml::entrezdirect esearch test_entrezdirect_esearch_pubmed::output/entrezdirect/test_pubmed.xml::content::contains '<ENTREZ_DIRECT>'
FAILED tests/modules/entrezdirect/esearch/test.yml::entrezdirect esearch test_entrezdirect_esearch_pubmed::output/entrezdirect/test_pubmed.xml::content::contains '<Db>pubmed</Db>'
FAILED tests/modules/entrezdirect/esearch/test.yml::entrezdirect esearch test_entrezdirect_esearch_genome::output/entrezdirect/test_genome.xml::content::contains '<ENTREZ_DIRECT>'
FAILED tests/modules/entrezdirect/esearch/test.yml::entrezdirect esearch test_entrezdirect_esearch_genome::output/entrezdirect/test_genome.xml::content::contains '<Db>genome</Db>'
FAILED tests/modules/entrezdirect/esearch/test.yml::entrezdirect esearch test_entrezdirect_esearch_assembly::output/entrezdirect/test_assembly.xml::content::contains '<ENTREZ_DIRECT>'
FAILED tests/modules/entrezdirect/esearch/test.yml::entrezdirect esearch test_entrezdirect_esearch_assembly::output/entrezdirect/test_assembly.xml::content::contains '<Db>assembly</Db>'
```

2022-07-25 22:08 UTC, alxndrdiaz reviewed
Removed files from wrong merge.

2022-07-25 22:25 UTC, muffato commented
Hi @alxndrdiaz . Same issue as in the other commit. The right branch to start from is `nf-core_master`, not `main`

2022-07-26 00:30 UTC, closed without merging