Add Eigenstratdatabasetools/snpcoverage
nf-core/modules pull request #1811
Opened 2022-06-26 14:30 UTC by TCLamnidis

Add module for eigenstratdatabsetools/snpcoverage.

## PR checklist

Closes #853 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-06-26 14:34 UTC, TCLamnidis commented
PileupCaller module is required to avoid using local test data.

2022-06-27 07:03 UTC, nvnieuwk commented
Hi, you have to upload some test data for GitHub Actions to use as the test samples. You can do this on https://github.com/nf-core/test-datasets/tree/modules on the branch `modules`. You can then add the data to `tests/config/test_data.config`. If you then use the samples specified in this config file in `tests/modules/eigenstratdatabasetools/coverage/main.nf`, your tests should pass :)

2022-06-27 08:08 UTC, jfy133 commented
> Hi, you have to upload some test data for GitHub Actions to use as the test samples. You can do this on https://github.com/nf-core/test-datasets/tree/modules on the branch `modules`. You can then add the data to `tests/config/test_data.config`. If you then use the samples specified in this config file in `tests/modules/eigenstratdatabasetools/coverage/main.nf`, your tests should pass :)

TYhanks @nvnieuwk ! In this case I think @TCLamnidis doesn't want to pollute test-data with highly specific test data for a single tool, thus his comment of "PileupCaller module is required to avoid using local test data.". I.e. @TCLamnidis will make the upstream module and insert this as a first step in the workflow. Thus we can review it, but I'll switch it to draft for now to make this clear it's not 100% ready.

2022-06-27 08:13 UTC, nvnieuwk commented
> > Hi, you have to upload some test data for GitHub Actions to use as the test samples. You can do this on https://github.com/nf-core/test-datasets/tree/modules on the branch `modules`. You can then add the data to `tests/config/test_data.config`. If you then use the samples specified in this config file in `tests/modules/eigenstratdatabasetools/coverage/main.nf`, your tests should pass :)
> 
> TYhanks @nvnieuwk ! In this case I think @TCLamnidis doesn't want to pollute test-data with highly specific test data for a single tool, thus his comment of "PileupCaller module is required to avoid using local test data.". I.e. @TCLamnidis will make the upstream module and insert this as a first step in the workflow. Thus we can review it, but I'll switch it to draft for now to make this clear it's not 100% ready.

Oh okay, my bad :p

2022-06-27 08:14 UTC, jfy133 requested changes
A few comments but overall pretty shipshape

2022-06-27 08:14 UTC, jfy133 commented on modules/eigenstratdatabasetools/snpcoverage/main.nf
> +    tuple val(meta), path(geno), path(snp), path(ind), val(suffix)
Suffix presumably would be same across all files, so should go in separate channel, this would make it slightly easier for a pipeline developer

2022-06-27 08:14 UTC, jfy133 commented on modules/eigenstratdatabasetools/snpcoverage/main.nf
> +    // If a suffix is provided, then remove an extra suffix from the geno name.
What is this referring to? Or left over?

2022-06-27 08:14 UTC, jfy133 commented on modules/eigenstratdatabasetools/snpcoverage/meta.yml
> +      doi: ""
If not published anywhere, you can delete this line

2022-06-27 08:22 UTC, jfy133 commented
> > > Hi, you have to upload some test data for GitHub Actions to use as the test samples. You can do this on https://github.com/nf-core/test-datasets/tree/modules on the branch `modules`. You can then add the data to `tests/config/test_data.config`. If you then use the samples specified in this config file in `tests/modules/eigenstratdatabasetools/coverage/main.nf`, your tests should pass :)
> > 
> > 
> > TYhanks @nvnieuwk ! In this case I think @TCLamnidis doesn't want to pollute test-data with highly specific test data for a single tool, thus his comment of "PileupCaller module is required to avoid using local test data.". I.e. @TCLamnidis will make the upstream module and insert this as a first step in the workflow. Thus we can review it, but I'll switch it to draft for now to make this clear it's not 100% ready.
> 
> Oh okay, my bad :p

No worries! You're technically correct, but in some cases it's not necessary to have explicit test data - the test-data repo is ballooning currently, so if you can just generate the input with very quick preparation steps in the test workflow it's normally worth it!

2022-11-03 12:08 UTC, closed without merging