New module for fasta_windows
nf-core/modules pull request #1956
Opened 2022-08-16 14:15 UTC by muffato

`fasta_windows` is a tool to quickly compute statistics over a fasta file in windows.
https://github.com/tolkit/fasta_windows

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-09-07 12:18 UTC, jfy133 requested changes
Output name shouldn't include anything other than prefix (up to pipeline developer to decide this), otherwise LGTM

2022-09-07 12:18 UTC, jfy133 commented on modules/fastawindows/main.nf
> +        --output ${prefix}_fw
```suggestion
        --output ${prefix}
```

Should be updated elsewhere as well, please see [^1] point 5 if you fear a clash in file names etc.

[^1]: https://nf-co.re/docs/contributing/modules#naming-conventions

2022-09-07 12:18 UTC, jfy133 commented on modules/fastawindows/meta.yml
> +      pattern: "*.{fa}"
```suggestion
      pattern: "*.{fa,fasta,fna}"
```

2022-09-08 15:47 UTC, muffato commented
Both fixed

2022-09-09 06:54 UTC, jfy133 approved these changes

2022-09-09 07:41 UTC, merged

2022-09-09 07:41 UTC, muffato commented
Thank you James !