Somalier relate
nf-core/modules pull request #2001
Opened 2022-09-02 19:54 UTC by ashotmarg

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-09-07 12:12 UTC, jfy133 commented
Looks rather incomplete due to boilerplate containers/conda env URLS, and also has random (output?) files in the test directory - so I'm converting to draft for now!

2022-09-08 11:53 UTC, ashotmarg commented
Hi James, thanks for going through the code.

I have actually left the default containers/conda env URLS in the code "on purpose" to emphasise that there are no biocontainer or conda images for this (somalier) program. Only docker is available.
Re the random (output?) files: these are actually the test input files (both required and optional files). These are not available in the "test_data.config" so I put them there.

So please advise how to proceed for these two points and I will fix them accordingly.

2022-09-08 14:30 UTC, ashotmarg commented
> Is there no chance they Somalier can go on conda/biocontainers?
I am not really sure, I don't have experience with this. Can we use the module with only docker? I guess it's not ideal but maybe possible, could you check with the other modules? Alternatively, do you know what's the easiest way to push/publish a e.g., singularity image to depot.galaxyproject.org/singularity ?
I could technically make a dockerfile for biocontainers, and push the docker image of Somalier to "quay.io" (which as far as I've read is preferred over the docker hub). Then, depot.galaxyproject.org/singularity should be able to automatically (?) get/make the singularity images from the biocontainers, mirroring the biocontainers, is that correct?

I will add the test files to the test-datasets repo where relevant. E.g., the input files for this module are the output files from https://github.com/nf-core/modules/pull/1986 , so cannot really use the existing files.

2022-09-09 04:23 UTC, jfy133 commented
Ok I took a stab last night and putting on bioconda was actually rather painless!

https://github.com/bioconda/bioconda-recipes/pull/36877

I also ran the 'functional tests' in somalier's scripts directory and it appeared to work as well with no failures

Once reviewed and merged it'll be a few days and then the biocontainers  will be available :)

2022-09-09 07:50 UTC, jfy133 commented
> I will add the test files to the test-datasets repo where relevant. E.g., the input files for this module are the output files from https://github.com/nf-core/modules/pull/1986 , so cannot really use the existing files.

Also, OK - then we can focus on getting extract in first :), can move discussion over there

2022-09-19 07:02 UTC, ashotmarg commented
Hi @jfy133, please double check this one as well, I've changed it according to the other module, so this should be (almost) ready. Re the input files that are not in the official datasets, should we keep them in the "delete_me" folder for now?

2022-09-19 07:43 UTC, jfy133 requested changes
You're missing docs in meta.yml for `sample_groups`, `ped`.

yes keeping in `delete_me` is fine!

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/main.nf
> +    tag "somalier_relate_all"
```suggestion
    tag "$meta.id"
```

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/main.nf
> +    -o ${prefix}somalier.res \\
```suggestion
    -o ${prefix} \\
```
https://nf-co.re/docs/contributing/modules#naming-conventions point 5

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/main.nf
> +    tuple val(meta), path("*somalier.res.samples.tsv"),   emit: samplesTSV
```suggestion
    tuple val(meta), path("*.html"),          emit: html
    tuple val(meta), path("*.pairs.tsv"),     emit: pairs_tsv
    tuple val(meta), path("*.samples.tsv"),   emit: samples_tsv
```

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/main.nf
> +    ${ped_command}
```suggestion
        -o ${prefix}somalier.res \\
        ${input_list} \\
        ${args} \\
        ${sample_groups_command} \\
        ${ped_command}
```

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/main.nf
> +
```suggestion
```

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/meta.yml
> +  - somalierExtract:
```suggestion
  - extract:
```

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/meta.yml
> +  - samples:
```suggestion
  - samples_tsv:
```

2022-09-19 07:43 UTC, jfy133 commented on modules/somalier/relate/meta.yml
> +  - pairs:
```suggestion
  - pairs_tsv:
```

2022-09-19 10:37 UTC, jfy133 approved these changes

2022-09-19 11:22 UTC, merged