add subworkflow bam_markduplicates_picard
nf-core/modules pull request #2229
Opened 2022-10-11 10:57 UTC by dmarron

## PR checklist

Closes #2168 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-11 11:08 UTC, Emiller88 requested changes
Just need a cram test to make sure those are working as expected!

2022-10-11 11:08 UTC, Emiller88 commented on subworkflows/nf-core/bam_markduplicates_picard/meta.yml
> +  - "@dmarron"
```suggestion
  - "@dmarron"
  - "@drpatelh"
```

2022-10-11 11:08 UTC, Emiller88 commented on tests/subworkflows/nf-core/bam_markduplicates_picard/main.nf
> +}
Can we test cram input as well?

2022-10-12 10:42 UTC, Emiller88 approved these changes
Awesome work! Good to merge if the tests pass!

2022-10-12 10:43 UTC, drpatelh commented on subworkflows/nf-core/bam_markduplicates_picard/main.nf
> +include { PICARD_MARKDUPLICATES      } from '../../../modules/nf-core/picard/markduplicates/main'
```suggestion
include { PICARD_MARKDUPLICATES } from '../../../modules/nf-core/picard/markduplicates/main'
```

2022-10-12 10:43 UTC, drpatelh approved these changes
🚀

2022-10-12 10:44 UTC, merged