Rename bam_sort_samtools to bam_sort_stats_samtools to follow convention
nf-core/modules pull request #2232
Opened 2022-10-11 11:10 UTC by KamilMaliszArdigen

## PR checklist

Closes #2230  

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-11 11:29 UTC, Emiller88 requested changes
You want to throw a mermaid diagram in there as well :smiley: ? #2218

2022-10-11 11:29 UTC, Emiller88 commented on subworkflows/nf-core/align_bowtie2/main.nf
>  include { BOWTIE2_ALIGN     } from '../../../modules/nf-core/bowtie2/align/main' addParams( options: params.align_options    )
```suggestion
include { BOWTIE2_ALIGN     } from '../../../modules/nf-core/bowtie2/align/main'
```

2022-10-11 11:29 UTC, Emiller88 commented on subworkflows/nf-core/align_bowtie2/main.nf
> +include { BAM_SORT_STATS_SAMTOOLS } from '../bam_sort_stats_samtools/main'           addParams( sort_options: params.samtools_sort_options, index_options: params.samtools_index_options, stats_options
```suggestion
include { BAM_SORT_STATS_SAMTOOLS } from '../bam_sort_stats_samtools/main'
```
Maybe toss a `nextflow.config` in there

2022-10-11 11:34 UTC, KamilMaliszArdigen commented on subworkflows/nf-core/align_bowtie2/main.nf
>  include { BOWTIE2_ALIGN     } from '../../../modules/nf-core/bowtie2/align/main' addParams( options: params.align_options    )
Is there any existing example?

2022-10-12 08:59 UTC, drpatelh approved these changes
🎉

2022-10-12 08:59 UTC, merged