Adding module fgbio/callduplexconsensusreads
nf-core/modules pull request #2243
Opened 2022-10-11 13:29 UTC by lescai

## PR checklist

Closes #2242 

- [ ] This PR adds the tool callduplexconsensusreads from fgbio: this tool is needed to update the fgbio UMI consensus subworkflow to the FGBIO best practices and add capacity to process duplex UMIs
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] test data have been added to this purpose on test-datasets
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-11 14:23 UTC, lescai commented on modules/nf-core/fgbio/callduplexconsensusreads/main.nf
> +    val(min_baseq)
Hi, about this I'm not quite of the same opinion. these are parameters, one should be able to specify as params of the pipeline. they might change according to the dataset being processed, and are by definition a variable. args are better suited for more "conserved" arguments of the software (i.e. run options for example).

2022-10-11 14:32 UTC, lescai commented on modules/nf-core/fgbio/callduplexconsensusreads/main.nf
> +        --output ${prefix}_consensus.bam \\
correct. modified to let prefix handle but also prevent errors in case user does not set it

2022-10-11 14:59 UTC, lescai commented on modules/nf-core/fgbio/callduplexconsensusreads/main.nf
> +    val(min_baseq)
ok, I might agree this is very elegant. but the config is down to the user, we don't provide a default config for the module.
I don't see many modules handling parameters this way tbh. 
I understand being passionate about things, but "nf-core" way? :)

2022-10-12 08:58 UTC, ameynert reviewed
Need to resolve conflict in test_data.config

2022-10-12 08:58 UTC, ameynert commented on modules/nf-core/fgbio/callduplexconsensusreads/meta.yml
> +## TODO nf-core: Add a description of all of the variables used as input
Confirm this TODO complete?

2022-10-12 08:59 UTC, lescai commented on modules/nf-core/fgbio/callduplexconsensusreads/meta.yml
> +## TODO nf-core: Add a description of all of the variables used as input
argh :) removed! thanks

2022-10-12 09:14 UTC, lescai commented
sweet! all checks passing now, md5sum issue resolved.

2022-10-12 09:30 UTC, ameynert requested changes
After discussion with the modules team at the hackathon, the guidance is going to be clarified in https://nf-co.re/docs/contributing/modules to remove "non-mandatory" from the line "All non-mandatory command-line tool non-file arguments MUST be provided as a string via the $args variable, which is assigned to using the task.ext.args variable.".

2022-10-12 09:43 UTC, matthdsm commented on modules/nf-core/fgbio/callduplexconsensusreads/main.nf
> +    val(min_baseq)
I agree with Adam here. The values for specific samples can be set inside the meta map

2022-10-12 13:17 UTC, ggabernet commented
ok, just not to block this module being merged now should we allow the current syntax @ameynert and just update the request once the guidelines have been re-discussed and clarified?

2022-10-13 06:46 UTC, lescai commented
Hello there. This module is essential to update the already existing fgbio subworkflow.
The code is linting, pytest workflows are passing on all three environments, and code has been written according to guidelines in force at the moment of submission. 
This seems however to be blocked over a guidelines update, initiated after submission, which has been now thoroughly debated on slack. 
I would really appreciate an approval, to allow further contributions to this community.

2022-10-13 07:18 UTC, matthdsm commented
![Let's go already](https://i1.sndcdn.com/artworks-000055524235-7ckjp4-t500x500.jpg)

2022-10-13 08:11 UTC, ameynert approved these changes
It works - happy to leave the args discussion for later.

2022-10-13 08:13 UTC, merged