Adding module fgbio/filterconsensusreads
nf-core/modules pull request #2248
Opened 2022-10-11 14:17 UTC by lescai

## PR checklist

Closes #2246 

- [ ] This PR introduces a module fgbio/filterconsensusreads, needed to update the fgbio UMI subworkflow in line with released best practices 
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] test data have been added to repo test-datasets
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-12 08:39 UTC, lescai commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +      pattern: "*.bam"
correct I missed that, thanks! :) they've been added in last commit

2022-10-12 08:40 UTC, lescai commented on modules/nf-core/fgbio/filterconsensusreads/main.nf
> +    val(max_base_error_rate)
same as with other modules: these are required mandatory arguments, so should be explicitly given by the user as input to the module.

2022-10-12 08:48 UTC, lescai commented
Hi, I've committed suggested changes to the yaml.
As far as inputs/ext.args are concerned: [modules guidelines](https://nf-co.re/docs/contributing/modules#general) indicate *non mandatory arguments MUST go* in `ext.args`.
These are *mandatory* parameters of the tool, as indicated in the [tool description](http://fulcrumgenomics.github.io/fgbio/tools/latest/FilterConsensusReads.html) and therefore I believe the use should be explicitly alerted their value should be specified as an input.

2022-10-12 09:04 UTC, nvnieuwk commented
@jfy133 what is your opinion on this?

2022-10-12 09:29 UTC, ameynert requested changes
After discussion with the modules team at the hackathon, the guidance is going to be clarified in https://nf-co.re/docs/contributing/modules to remove "non-mandatory" from the line "All non-mandatory command-line tool non-file arguments MUST be provided as a string via the $args variable, which is assigned to using the task.ext.args variable.".

2022-10-13 06:46 UTC, lescai commented
Hello there. This module is essential to update the already existing fgbio subworkflow.
The code is linting, pytest workflows are passing on all three environments, and code has been written according to guidelines in force at the moment of submission. 
This seems however to be blocked over a guidelines update, initiated after submission, which has been now thoroughly debated on slack. 
I would really appreciate an approval, to allow further contributions to this community.

2022-10-13 07:26 UTC, jfy133 reviewed
Overall LGTM.

So now I've looked at the module properly I do where the discussion came from. Instinctively I would have requested that they go in the nextflow.config, as these are clear parameters (rather than positional).

One of the exceptions I would consider would be if the tool does not produce a useful error messages if one of the mandatory arguments are missing? 

If not I'm happy to reconfigure the module with suggestions once I get to the tower (and I will also make the docs update for the exceptions on the website)

2022-10-13 07:26 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +  # Only when we have meta
Can be removed

2022-10-13 07:26 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +
These empty lines between entries can be removed

2022-10-13 07:40 UTC, jfy133 requested changes
Reconfiguration based on updated guidelines

2022-10-13 07:40 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/main.nf
> +    val(max_base_error_rate)
```suggestion
```

2022-10-13 07:40 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/main.nf
> +        --max-base-error-rate ${max_base_error_rate} \\
```suggestion
```

2022-10-13 07:40 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +      description: The maximum error rate for a single consensus base
```suggestion
```

2022-10-13 07:40 UTC, jfy133 commented on tests/modules/nf-core/fgbio/filterconsensusreads/nextflow.config
> +
```suggestion
    publishDir = { "${params.outdir}/${task.process.tokenize(':')[-1].tokenize('_')[0].toLowerCase()}" }
    
    withName: FGBIO_FILTERCONSENSUS {
        ext.args = "        --min-reads 3 --min-base-quality 45 --max-base-error-rate 0.2"
    }
    
```

2022-10-13 07:40 UTC, jfy133 commented on tests/modules/nf-core/fgbio/filterconsensusreads/main.nf
> +    max_base_error_rate = '0.2'
```suggestion
```

2022-10-13 07:40 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +  #
```suggestion
```

2022-10-13 07:48 UTC, jfy133 commented
x-ref argument clarifications: https://github.com/nf-core/nf-co.re/pull/1399

2022-10-13 08:12 UTC, ameynert approved these changes
LGTM!

2022-10-13 13:36 UTC, lescai commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +  - filter
done

2022-10-13 13:36 UTC, lescai commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +  # Only when we have meta
thanks :)

2022-10-13 13:37 UTC, lescai commented on tests/modules/nf-core/fgbio/filterconsensusreads/nextflow.config
> +
made changes locally and pushed

2022-10-13 13:38 UTC, lescai commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +  #
changed locally and pushed

2022-10-13 14:27 UTC, lescai commented
all should be ok except conda failing on GitHub Action but succeeding locally :alien:

2022-10-13 14:27 UTC, lescai commented on tests/modules/nf-core/fgbio/filterconsensusreads/main.nf
> +    max_base_error_rate = '0.2'
modified locally and pushed

2022-10-13 21:37 UTC, jfy133 approved these changes
Minor formatting and you're GTG!

2022-10-13 21:37 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/main.nf
> +    // please notice:
```suggestion
    // please note:
```

2022-10-13 21:37 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/main.nf
> +    // --make sure they are specified via ext.args in your config
```suggestion
    // make sure they are specified via ext.args in your config
```

2022-10-13 21:37 UTC, jfy133 commented on modules/nf-core/fgbio/filterconsensusreads/meta.yml
> +  #
```suggestion
```

2022-10-13 21:37 UTC, jfy133 commented on tests/config/test_data.config
> +
```suggestion
```

2022-10-14 08:50 UTC, lescai commented
thanks @jfy133 @adamrtalbot @ameynert

2022-10-14 08:53 UTC, merged