Markduplicates
nf-core/modules pull request #2256
Opened 2022-10-11 15:48 UTC by dmarron

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-11 16:00 UTC, Emiller88 requested changes
Can we leave the unsorted bam test alone and just add the sorted cram test?

2022-10-12 09:11 UTC, dmarron commented
> From @dmarron :
> 
> > we can't leave the unsorted bam alone, the test actually fails
> > for picard markduplicates
> > in the markduplicates documentation it says a sorted bam is required
> 
> Solid, good find! Let's add the test back and mark it as failing! https://pytest-workflow.readthedocs.io/en/stable/#test-options

I added this test back as succeeding, it turns out it could succeed if --ASSUME_SORT_ORDER queryname is passed in as a parameter to markduplicates

2022-10-12 09:24 UTC, LaurenceKuhl approved these changes
Hi,

looks good to me but adding an additional mandatory parameter might break all the pipelines/workflows currently using markduplicates, right?

2022-10-12 09:43 UTC, Emiller88 approved these changes
LGTM, just adding a comment for another test in the future!

2022-10-12 09:43 UTC, Emiller88 commented on tests/modules/nf-core/picard/markduplicates/main.nf
>  }
```suggestion
}

// TODO Add a test with PICARD_MARKDUPLICATES ( input, [], [] )
```

2022-10-12 09:46 UTC, merged

2022-10-12 09:46 UTC, qclayssen approved these changes