CIRCexplorer2 modules
nf-core/modules pull request #2298
Opened 2022-10-14 05:18 UTC by BarryDigby

## PR checklist

Added two functions `parse` and `annotate` from the tool `CIRCexplorer2`. 

- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md) - I think?
- [x] If necessary, include test data in your PR.
    - circRNA test data is funky and unlikely to be of any use to others. I'm happy hosting it on the circrna branch of test-datasets.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfill software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-14 05:58 UTC, jfy133 requested changes
Missing `$args` in both modules but otherwie cosmetic changes!

2022-10-14 05:58 UTC, jfy133 commented on modules/nf-core/circexplorer2/annotate/main.nf
> +        -o ${prefix}.txt
Missing $args

2022-10-14 05:58 UTC, jfy133 commented on modules/nf-core/circexplorer2/annotate/meta.yml
> +  - Annotate
```suggestion
  - annotate
  - circexplorer
```

2022-10-14 05:58 UTC, jfy133 commented on modules/nf-core/circexplorer2/annotate/meta.yml
> +  - circRNAs
```suggestion
  - circrnas
```

2022-10-14 05:58 UTC, jfy133 commented on modules/nf-core/circexplorer2/parse/main.nf
> +        -b ${prefix}.junction.bed
Missing $args

2022-10-14 05:58 UTC, jfy133 commented on modules/nf-core/circexplorer2/parse/main.nf
> +        -b ${prefix}.junction.bed
Should just be `.bed`, if there is  risk of a clash, add a warning [^1]

[^1]: https://nf-co.re/docs/contributing/modules#naming-conventions

2022-10-14 05:58 UTC, jfy133 commented on modules/nf-core/circexplorer2/parse/meta.yml
> +  - circRNA
```suggestion
  - circrnas
  - circexplorer
```

2022-10-14 05:58 UTC, jfy133 commented on modules/nf-core/circexplorer2/parse/meta.yml
> +      description: BAM (BWA), BED (Segemehl), TXT (MapSplice), Junction (STAR).
```suggestion
      description: BAM (BWA), BED (Segemehl), TXT (MapSplice), or Junction (STAR) file. Aligner will be autodetected based on file suffix.
```

2022-10-16 00:39 UTC, ramprasadn approved these changes
LGTM! 🚀

2022-10-17 10:26 UTC, nvnieuwk approved these changes

2022-10-17 10:45 UTC, jfy133 approved these changes
A few more keywords would be useful for findability but otherwise good to og!

2022-10-17 14:44 UTC, merged