add module odgi/build
nf-core/modules pull request #2340
Opened 2022-10-19 14:17 UTC by subwaystation

## PR checklist

This PR progresses https://github.com/nf-core/pangenome/issues/70.

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-19 14:24 UTC, subwaystation commented
@mirpedrol Do you have any idea, why no test is run?

```
PROFILE=docker pytest --tag odgi/build --symlink --keep-workflow-wd
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.10.8, pytest-7.1.3, pluggy-1.0.0
rootdir: /home/heumos/git/modules, configfile: pytest.ini
plugins: workflow-1.6.0, anyio-3.6.1
collecting ... 
collected 1147 items                                                                                                                                                                                                                         

tests/test_versions_yml.py sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 17%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 37%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 57%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 77%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 97%]
ssssssssssssssssssssssss                                                                                                                                                                                                               [100%]

============================================================================================================== warnings summary ==============================================================================================================
../../.local/lib/python3.10/site-packages/pytest_workflow/plugin.py:122: 673 warnings
  /home/heumos/.local/lib/python3.10/site-packages/pytest_workflow/plugin.py:122: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return YamlFile.from_parent(parent, fspath=path)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================================================================================== 1147 skipped, 673 warnings in 7.82s =====================================================================================================
```

2022-10-19 14:27 UTC, subwaystation commented
@nvnieuwk Maybe you know why no test is actually executed?

2022-10-19 14:31 UTC, nvnieuwk requested changes

2022-10-19 14:47 UTC, subwaystation commented on tests/modules/nf-core/odgi/build/main.nf
> +              [ file(params.test_data['homo_sapiens']['pangenome']['pangenome_smoothxg_gfa'], checkIfExists: true) ],
Unfortunately, that didn't fix the issue.

2022-10-19 14:54 UTC, nvnieuwk commented on tests/modules/nf-core/odgi/build/main.nf
> +              [ file(params.test_data['homo_sapiens']['pangenome']['pangenome_smoothxg_gfa'], checkIfExists: true) ],
I'll take a better look tomorrow :p

2022-10-20 07:07 UTC, nvnieuwk commented on tests/modules/nf-core/odgi/build/main.nf
> +              [ file(params.test_data['homo_sapiens']['pangenome']['pangenome_smoothxg_gfa'], checkIfExists: true) ],
I have no clue, I posted on Slack about it

2022-10-20 07:17 UTC, subwaystation commented on tests/modules/nf-core/odgi/build/main.nf
> +              [ file(params.test_data['homo_sapiens']['pangenome']['pangenome_smoothxg_gfa'], checkIfExists: true) ],
Ah, you were 9 minutes faster. I always get a delay here xD

2022-10-20 07:18 UTC, nvnieuwk commented on tests/modules/nf-core/odgi/build/main.nf
> +              [ file(params.test_data['homo_sapiens']['pangenome']['pangenome_smoothxg_gfa'], checkIfExists: true) ],
No problem posting it twice can't hurt, right ;)

2022-10-20 08:56 UTC, subwaystation commented on tests/modules/nf-core/odgi/build/main.nf
> +              [ file(params.test_data['homo_sapiens']['pangenome']['pangenome_smoothxg_gfa'], checkIfExists: true) ],
`build` is a keyword for `pytest` at @nvnieuwk ...... See https://nfcore.slack.com/archives/CJRH30T6V/p1666255001028999.

Could you please take a quick look again? All should be fine now.

2022-10-20 09:22 UTC, subwaystation commented
@nvnieuwk Somehow I can't merge, although I resolved your issue. Hmm.

2022-10-20 09:28 UTC, nvnieuwk approved these changes

2022-10-20 09:29 UTC, nvnieuwk commented
Hit it ;)

2022-10-20 09:30 UTC, merged