Add calder2 module
nf-core/modules pull request #2351
Opened 2022-10-20 09:28 UTC by lucananni93

## PR checklist

Closes #2293 

- [X] This comment contains a description of changes (with reason).
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-10-21 09:27 UTC, jfy133 requested changes

2022-10-21 09:27 UTC, jfy133 commented on modules/nf-core/calder2/main.nf
> +def VERSION = '0.3'
This needs to be in the script block: https://github.com/nf-core/modules/blob/f919110f52861a5c0c2ab8229c17560f41405721/modules/nf-core/homer/annotatepeaks/main.nf#L26

2022-10-21 09:27 UTC, jfy133 commented on modules/nf-core/calder2/main.nf
> +    # calling CALDER
```suggestion
```

2022-10-21 09:27 UTC, jfy133 commented on modules/nf-core/calder2/main.nf
> +    # getting binsize
```suggestion
    # getting binsize as mandatory input for calder
```

2022-10-21 09:27 UTC, jfy133 commented on modules/nf-core/calder2/main.nf
> +    calder --input $cool$suffix --outpath ${meta.id} --nproc $cpus --type cool --bin_size "\${binsize}" $args
- Please split each parameter across multiple lines (see other modules as example)
- Please use `prefix` not `meta.id` for outpath, you will see examples for this in other modules [^1]


[^1]: https://nf-co.re/docs/contributing/modules#naming-conventions point 6

2022-10-21 09:27 UTC, jfy133 commented on modules/nf-core/calder2/meta.yml
> +  - calder2
More keywords please! make the module searchable, e.g. `hi-c` etc. you can see more examples/suggestions in the green tags here: https://nf-co.re/modules

2022-10-21 09:27 UTC, jfy133 commented on modules/nf-core/calder2/meta.yml
> +      type: folder
```suggestion
      type: directory
```

2022-10-21 09:27 UTC, jfy133 commented on modules/nf-core/calder2/meta.yml
> +      description: Calder output
Containing....?

2022-10-21 09:27 UTC, jfy133 commented on tests/modules/nf-core/calder2/main.nf
> +}
Can you add a test also using the `resolution` input channel?

2022-10-24 08:43 UTC, lucananni93 commented
@jfy133 Is it possible to merge now?

2022-10-24 09:18 UTC, jfy133 approved these changes
One more docs thing,and you're good to go.

I also see there is a `--keep_intermediate` flag, you may wish to make an optional output channel to pick up these files if someone supplies that flag via modules.conf or similar. However this is not a dealbreak for me.

But otherwise LGTM

```
Usage: /home/jfellows/.conda/envs/calder2/bin/calder [options]


Options:
	-i INPUT, --input=INPUT
		Input Hi-C contacts

	-t TYPE, --type=TYPE
		The type of input: hic or cool [default hic]

	-b BIN_SIZE, --bin_size=BIN_SIZE
		Bin size to use for the analysis [default 50000]

	-g GENOME, --genome=GENOME
		Genome assembly to use [default hg19]

	-f FEATURE_TRACK, --feature_track=FEATURE_TRACK
		Genomic feature track to be used to determine A/B compartment direction
	              when genome == 'others'. The track should presumably have higher values
	              in A than in B compartmnets. [default NA]

	-p NPROC, --nproc=NPROC
		Number of cores to use [default 1]

	-o OUTPATH, --outpath=OUTPATH
		Path to the output folder

	-k, --keep_intermediate
		Keep intermediate data after done [default FALSE]

	-h, --help
		Show this help message and exit
```

2022-10-24 09:18 UTC, jfy133 commented on modules/nf-core/calder2/meta.yml
> +      description: Resolution
Please expand on 'resolution' here

2022-10-24 14:04 UTC, lucananni93 commented
I've added the optional folder for intermediate data to the module and improved the description of the "Resolution" output.
All checks are successful. If you agree, @jfy133, I'll proceed with the merge.

2022-10-24 14:06 UTC, jfy133 approved these changes
Yes you can merge

2022-10-24 14:06 UTC, merged