bump dragmap version
nf-core/modules pull request #2496
Opened 2022-11-10 16:55 UTC by FriederikeHanssen

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-11-10 16:56 UTC, FriederikeHanssen commented
waiting on samtools container

2022-11-11 11:26 UTC, maxulysse commented on modules/nf-core/dragmap/align/main.nf
> +        'https://depot.galaxyproject.org/singularity/mulled-v2-mulled-v2-580d344d9d4a496cd403932da8765f9e0187774d:bb7e33c2ede38421063b8379a5fb3453645bb047-0':
```suggestion
        'https://depot.galaxyproject.org/singularity/mulled-v2-580d344d9d4a496cd403932da8765f9e0187774d:bb7e33c2ede38421063b8379a5fb3453645bb047-0':
```

2022-11-11 11:26 UTC, maxulysse requested changes
I think there's an issue on a mulled container definition

2022-11-11 11:29 UTC, FriederikeHanssen commented
> I think there's an issue on a mulled container definition

Thank you 🙏 I am starring at this for the past 20min, trying to figure out why it an't find it

2022-11-11 11:30 UTC, maxulysse commented
> > I think there's an issue on a mulled container definition
> 
> Thank you pray I am starring at this for the past 20min, trying to figure out why it an't find it

Always good to have a new set of eyes

2022-11-11 11:31 UTC, maxulysse approved these changes
Toppen

2022-11-11 13:22 UTC, maxulysse approved these changes

2022-11-11 13:36 UTC, maxulysse approved these changes

2022-11-11 13:55 UTC, FriederikeHanssen commented
just conda being conda

2022-11-11 13:55 UTC, merged