Add gatk4 germlinecnvcaller
nf-core/modules pull request #2538
Opened 2022-11-22 15:29 UTC by ryanjameskennedy

I have been trying to add this module (gatk4 GermlineCNVCaller) to nf-core/modules for quite some time, but seem to be stuck on the testing part. I have created an [issue on broadinstitute's github page](https://github.com/broadinstitute/gatk/issues/8097) outlining the problem and containing the test files and how to run the test (NOTE: Docker is required to test it). Any help is appreciated! Please try testing it yourself using nf-core's testing software if you wish. I will soon run it with complete clinical files instead of small test files.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible (not possibleat the moment) to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-12-05 13:24 UTC, nvnieuwk requested changes
Hi, such strange error that you encounter when running this... I'll have a look

2022-12-05 13:24 UTC, nvnieuwk commented on tests/modules/nf-core/gatk4/germlinecnvcaller/main.nf
> +    UNTAR (GATK4_DETERMINEGERMLINECONTIGPLOIDY.out.calls)
You could add automatic untarring in the module if the input is tarred (by using a combination of these lines https://github.com/nf-core/modules/blob/230c66b9cd2b8233c94f5f34d56d6ffc68d638ce/modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf#L33-L36)

2023-04-11 09:08 UTC, jemten commented on modules/nf-core/gatk4/germlinecnvcaller/main.nf
> +    def avail_mem = 3
Try and use the same syntax as used for the other gatk modules. Example
https://github.com/nf-core/modules/blob/880d634b0d5aead9447ae29e3e02e0e31ca7ae7f/modules/nf-core/gatk4/bedtointervallist/main.nf#L25

2023-04-11 12:12 UTC, maxulysse commented on tests/modules/nf-core/gatk4/germlinecnvcaller/main.nf
> +include { GATK4_GERMLINECNVCALLER as GATK4_GERMLINECNVCALLER_COHORT; GATK4_GERMLINECNVCALLER as GATK4_GERMLINECNVCALLER_CASE } from '../../../../../modules/nf-core/gatk4/germlinecnvcaller/main.nf'
```suggestion
include { GATK4_DETERMINEGERMLINECONTIGPLOIDY as GATK4_DETERMINEGERMLINECONTIGPLOIDY_COHORT } from '../../../../../modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf'
include { GATK4_DETERMINEGERMLINECONTIGPLOIDY as GATK4_DETERMINEGERMLINECONTIGPLOIDY_CASE } from '../../../../../modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf'
include { UNTAR as UNTAR_PLOIDY_COHORT } from '../../../../../modules/nf-core/untar/main.nf'
include { UNTAR as UNTAR_PLOIDY_CASE } from '../../../../../modules/nf-core/untar/main.nf'
include { UNTAR as UNTAR_MODEL } from '../../../../../modules/nf-core/untar/main.nf'
include { GATK4_GERMLINECNVCALLER as GATK4_GERMLINECNVCALLER_COHORT } from '../../../../../modules/nf-core/gatk4/germlinecnvcaller/main.nf'
include { GATK4_GERMLINECNVCALLER as GATK4_GERMLINECNVCALLER_CASE } from '../../../../../modules/nf-core/gatk4/germlinecnvcaller/main.nf'
```

Just for simpler reading

2023-04-11 12:44 UTC, ryanjameskennedy commented on modules/nf-core/gatk4/germlinecnvcaller/main.nf
> +    def untar_ploidy = ploidy ? (ploidy ==~ /^.*\.tar\.gz$/ ? "tar -xzf ${ploidy}" : "") : ""
Something like [this](https://github.com/nf-core/modules/blob/880d634b0d5aead9447ae29e3e02e0e31ca7ae7f/modules/nf-core/gatk4/genotypegvcfs/main.nf#L29)? I think it has to be `ploidy.name.endsWith("tar.gz")`. Will quickly test and push changes.

2023-04-11 13:59 UTC, maxulysse commented on modules/nf-core/gatk4/germlinecnvcaller/meta.yml
> +  - model:
We're still missing the description for intervals here in the meta.yml file

2023-04-11 14:45 UTC, jemten reviewed
some comments

2023-04-11 14:45 UTC, jemten commented on modules/nf-core/gatk4/germlinecnvcaller/main.nf
> +    path  "versions.yml"             , emit: versions
A little bit of nitpicking but it would look nicer if you could align the commas

2023-04-11 14:45 UTC, jemten commented on modules/nf-core/gatk4/germlinecnvcaller/meta.yml
> +      description: TSV file
Wouldn't hurt with one or two more words describing the tsv. Like what you did for the bed file

2023-04-11 14:45 UTC, jemten commented on modules/nf-core/gatk4/germlinecnvcaller/meta.yml
> +  - bed:
```suggestion
  - intervals:
```
This is the intervals file right?

2023-04-12 09:38 UTC, maxulysse commented on modules/nf-core/gatk4/germlinecnvcaller/main.nf
> +        'broadinstitute/gatk:4.4.0.0' }"
```suggestion
    //Conda is not supported at the moment: https://github.com/broadinstitute/gatk/issues/7811
    container "broadinstitute/gatk:4.4.0.0" //Biocontainers is missing a package
```
cf: https://github.com/nf-core/modules/blob/266738f5c73809f0ef2742b0966f276856fe1b15/modules/nf-core/gatk4/cnnscorevariants/main.nf#L5-L6

2023-04-12 12:41 UTC, maxulysse approved these changes

2023-04-12 12:42 UTC, maxulysse commented
@nvnieuwk ?

2023-04-12 12:51 UTC, jemten approved these changes

2023-04-12 13:51 UTC, merged