add mergebamalignment
nf-core/modules pull request #259
Opened 2021-03-05 14:21 UTC by KevinMenden

Adding `gatk MergeBamAlignment` 

https://github.com/nf-core/modules/issues/227

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-03-11 13:26 UTC, drpatelh requested changes
Looks great @KevinMenden ! Couple of minor gripes.

2021-03-11 13:26 UTC, drpatelh commented on software/gatk4/mergebamalignment/main.nf
> +    path unmapped
```suggestion
    path unaligned
```

2021-03-11 13:26 UTC, drpatelh commented on software/gatk4/mergebamalignment/main.nf
> +    path unmapped
Maybe go with either `aligner` -> `unaligned` or `mapped` -> `unmapped`?

2021-03-11 13:26 UTC, drpatelh commented on software/gatk4/mergebamalignment/main.nf
> +    path  '*.version.txt'                       , emit: version
```suggestion
    tuple val(meta), path('*.merged.bam'), emit: bam
    path  '*.version.txt'                , emit: version
```

2021-03-11 13:26 UTC, drpatelh commented on software/gatk4/mergebamalignment/main.nf
> +    path  '*.version.txt'                       , emit: version
Aaannnndd he's back! 😅

2021-03-11 13:26 UTC, drpatelh commented on tests/data/README.md
> +        * 'test_unaligned.bam': unmapped BAM file create from 'test_1.fastq.gz' using GATK4 SamToFastq
```suggestion
        * 'test_unaligned.bam': unmapped BAM file created from 'test_1.fastq.gz' using GATK4 SamToFastq
```

2021-03-16 08:22 UTC, KevinMenden commented on software/gatk4/mergebamalignment/main.nf
> +    path  '*.version.txt'                       , emit: version
😁 

it's never gonna happen!!

2021-03-16 08:22 UTC, KevinMenden commented on software/gatk4/mergebamalignment/main.nf
> +    path unmapped
👍

2021-03-17 11:49 UTC, drpatelh commented on software/gatk4/mergebamalignment/meta.yml
> +  - unmapped:
```suggestion
  - unaligned:
```

2021-03-17 11:50 UTC, drpatelh approved these changes
Need to remove the updates to `.github/filters.yml` on the PR and add to `tests/config/pytest_software.yml` instead.

2021-03-17 14:56 UTC, merged