Add kraken2 run module
nf-core/modules pull request #266
Opened 2021-03-11 16:14 UTC by JoseEspinosa

Add kraken2 run module as a [requirement](https://github.com/nf-core/viralrecon/issues/149) of `nfcore/viralrecon` DSL2 implementation.

The previous [PR](https://github.com/nf-core/modules/pull/255) adding this module was closed since the structure of the test data was changed.

To construct the `kraken2` DB for testing purposes the `fasta` file on `tests/data/genomics/sarscov2/fasta/test_genome.fasta` was used after adding the coronavirus taxonomy ID the fasta header `|kraken:taxid|2697049`

Then the kraken2 custom database was created using these commands:

``` 
DBNAME='test_kraken2_DB'
kraken2-build --download-taxonomy --db $DBNAME --use-ftp
kraken2-build --add-to-library test_genome.fasta --db $DBNAME
kraken2-build --build --db $DBNAME
```

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-03-11 16:18 UTC, JoseEspinosa commented
I modified the header of the test `fasta` file on `tests/data/genomics/sarscov2/fasta/test_genome.fasta` since the taxonomy ID is needed by `kraken2` to build the DB (`|kraken:taxid|2697049`). However. I didn't make this change permanent to avoid possible problems with other tools that might parse the header, what do you think @drpatelh ?

2021-03-11 16:55 UTC, drpatelh requested changes
Yeah, leave the DB as it is for now @JoseEspinosa. Although, I think we will need to change it when we eventually add the Kraken2 DB index process 😅 We really need a workflow to generate all of this test data! Means we can use small adjustments like this and re-generate everything. Too much hassle at the moment to do it individually like @KevinMenden did 😎 !

Need to delete some files on the PR though.

2021-03-11 16:55 UTC, drpatelh commented on software/functions.nf
> + *  Utility functions used in nf-core DSL2 module files
Rogue file? Needs to be deleted.

2021-03-11 16:55 UTC, drpatelh commented on software/kraken2/run/meta.yml
> +
```suggestion
```

2021-03-11 16:55 UTC, drpatelh commented on software/main.nf
> +include { initOptions; saveFiles; getSoftwareName } from './functions'
Another rogue file that needs to be deleted?

2021-03-11 16:55 UTC, drpatelh commented on software/meta.yml
> +keywords:
Another rogue file that needs to be deleted?

2021-03-17 11:47 UTC, drpatelh commented
Needs a few changes still here @JoseEspinosa to bring it in line with the new structure and to remove rogue files.

2021-03-17 22:12 UTC, JoseEspinosa commented
@drpatelh I think I have addressed all the requested changes.

2021-03-18 13:08 UTC, drpatelh approved these changes
Thanks @JoseEspinosa !

2021-03-18 13:08 UTC, merged