Collectrnaseqmetrics
nf-core/modules pull request #2677
Opened 2022-12-17 02:30 UTC by anoronh4

Adding the module picard/collectrnaseqmetrics. allowed usage of a gene_pred file as an alternative to ref_flat. On further consideration, there are a few other strategies i can think of to generate the ref_flat file, but maybe the nf-core community should weigh in here.  

## PR checklist

Closes #2652 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfill software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-12-17 02:33 UTC, anoronh4 commented
a few strategies to provide necessary ref_flat file for collectrnaseqmetrics:
1. add file to nf-core/test-datasets repo
2. create a new module specifically to this purpose called ucsc/gtftorefflat. This would be a lot like the existing ucsc/gtftogenepred but would add an extra awk statement at the end to create a refflat file
3. have the collectrnaseqmetrics module take a gene_pred file as an alternative to the ref_flat file
4. modify the existing ucsc/gtftogenepred module to output an additional refflat channel.

2022-12-20 17:33 UTC, anoronh4 commented
> At the time of writing this comment I am stuck on the best way to add provide a ref_flat file for this module. a few strategies i've thought of include:
> 
> 1. add file to the `nf-core/test-datasets` repo
> 2. create a new module specifically to this purpose called `ucsc/gtftorefflat`. This would be a lot like the existing `ucsc/gtftogenepred` but would add an extra awk statement at the end to create a ref_flat file
> 3. have the `picard/collectrnaseqmetrics` module take a gene_pred file as an alternative to the ref_flat file
> 4. modify the existing `ucsc/gtftogenepred` module to output an additional channel containing the ref_flat file.

I have chosen the fourth option and the PR for updating `ucsc/gtftogenepred` was already created and merged (#2680)

2022-12-21 12:25 UTC, nvnieuwk requested changes

2022-12-21 17:11 UTC, anoronh4 commented on modules/nf-core/picard/collectrnaseqmetrics/main.nf
> +        log.info '[Picard CollectMultipleMetrics] Available memory not known - defaulting to 3GB. Specify process memory requirements to change this.'
Fixed, thanks for catching that!

2022-12-21 17:12 UTC, anoronh4 commented on modules/nf-core/picard/collectrnaseqmetrics/main.nf
> +    } else { strand = "--STRAND_SPECIFICITY NONE" }
i removed these statements and actually added `STRAND_SPECIFICITY` in the test config file.

2022-12-21 17:16 UTC, nvnieuwk approved these changes
LGTM!

2022-12-21 17:32 UTC, merged