Add spring/compress module
nf-core/modules pull request #2783
Opened 2023-01-26 11:55 UTC by xec-cm

## PR checklist

Closes #2770 

- [x] This comment contains a description of changes (with reason).
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x ] If necessary, include test data in your PR.
- [x ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-01-26 14:49 UTC, nvnieuwk requested changes

2023-01-26 14:49 UTC, nvnieuwk commented on modules/nf-core/spring/compress/main.nf
> +        """
```suggestion
    def input = meta.single_end ? "-i ${fastq1}" : "-i ${fastq1} ${fastq2}"

    """
    spring \\
        -c \\
        -g \\
        -t ${task.cpus} \\
        $args \\
        ${input} \\
        -o ${prefix}.spring

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        spring: ${VERSION}
    END_VERSIONS
    """
```

It's preffered to not have multiple scripts inside one process (especially if it's such a small difference)

2023-01-26 14:49 UTC, nvnieuwk commented on modules/nf-core/spring/compress/main.nf
> +    tuple val(meta), path(fastq)
```suggestion
    tuple val(meta), path(fastq1), path(fastq2)
```

This is a bit more clear

2023-01-26 14:49 UTC, nvnieuwk commented on modules/nf-core/spring/compress/main.nf
> +    tuple val(meta), path(fastq)
Can you also update the `meta.yml` for this?

2023-01-26 14:49 UTC, nvnieuwk commented on tests/modules/nf-core/spring/compress/main.nf
> +        [ file(params.test_data['sarscov2']['illumina']['test_1_fastq_gz'], checkIfExists: true), file(params.test_data['sarscov2']['illumina']['test_2_fastq_gz'], checkIfExists: true)]
```suggestion
        file(params.test_data['sarscov2']['illumina']['test_1_fastq_gz'], checkIfExists: true), 
        file(params.test_data['sarscov2']['illumina']['test_2_fastq_gz'], checkIfExists: true)
```

2023-01-26 14:49 UTC, nvnieuwk commented on tests/modules/nf-core/spring/compress/main.nf
> +        file(params.test_data['sarscov2']['illumina']['test_1_fastq_gz'], checkIfExists: true)
```suggestion
        file(params.test_data['sarscov2']['illumina']['test_1_fastq_gz'], checkIfExists: true),
        []
```

2023-01-27 10:42 UTC, xec-cm commented
Dear @nvnieuwk, 

Thanks for reviewing this PR! I really appreciate it. I just wanted to check, would it be alright if I created a new PR for the decompression feature and added it as a subfolder within the "spring" folder? Also, just to clarify, when I tried to open the linked issue, I couldn't add myself as an assignee, is that normal?

Thanks again

Best

2023-01-27 11:35 UTC, nvnieuwk commented
Yeah go ahead! To assign yourself to an issue you need to be a member of nf-core. You can ask to be added on Slack in the github-invitations channel 🙂

2023-01-30 07:30 UTC, nvnieuwk approved these changes
LGTM!

2023-10-02 13:43 UTC, SPPearce commented
Hi @xec-cm , 
It looks like this PR is quite close to being ready to merge, with just some additional lint changes since you put it together. Let me know if you need any help in finishing it off.

2023-10-03 08:09 UTC, xec-cm commented
@SPPearce done!

2023-10-03 08:38 UTC, SPPearce approved these changes
Looks good to me then!

2023-10-03 08:39 UTC, SPPearce commented
Can you press the Merge button, or do I need to do it for you?

2023-10-03 09:10 UTC, xec-cm commented
Hi @SPPearce

I do not have write access to this repository and therefore cannot merge the PR. Can you please do it?

2023-10-03 09:20 UTC, merged