Added new module: bbmap/sendsketch
nf-core/modules pull request #2791
Opened 2023-01-26 22:43 UTC by phanhung2

This is a module for the BBMap tool `sendsketch.sh`

## PR checklist

Closes #XXX 

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-01-30 07:55 UTC, nvnieuwk requested changes

2023-01-30 07:55 UTC, nvnieuwk commented on modules/nf-core/bbmap/sendsketch/main.nf
> +    tag "$file"
```suggestion
    tag "$meta.id"
```

This should use `meta.id` if meta is an input

2023-01-30 07:55 UTC, nvnieuwk commented on modules/nf-core/bbmap/sendsketch/main.nf
> +    def args = task.ext.args ?: ''
```suggestion
    def args = task.ext.args ?: ''
    def prefix =  task.ext.prefix ?: "${meta.id}"
```

2023-01-30 07:55 UTC, nvnieuwk commented on modules/nf-core/bbmap/sendsketch/main.nf
> +        out='results.txt' \\
```suggestion
        out=${prefix}.txt \\
```

2023-01-30 07:55 UTC, nvnieuwk commented on modules/nf-core/bbmap/sendsketch/main.nf
> +    tuple val(meta), path('results.txt')  , emit: hits
```suggestion
    tuple val(meta), path("*.txt")  , emit: hits
```

2023-01-30 07:55 UTC, nvnieuwk commented on modules/nf-core/bbmap/sendsketch/main.nf
> +        -Xmx${task.memory.toGiga()}g
It's better to add a check and see if the memory has been set (see this module for an example: https://github.com/nf-core/modules/blob/master/modules/nf-core/gatk4/combinegvcfs/main.nf)

2023-01-30 07:55 UTC, nvnieuwk commented on modules/nf-core/bbmap/sendsketch/meta.yml
> +  - results.txt:
```suggestion
  - hits:
```

2023-02-03 18:44 UTC, phanhung2 commented
Thank you @nvnieuwk! These changes have been very helpful and have been implemented to the module. If you could take a review and let me know, it would be greatly appreciated!

2023-02-06 08:23 UTC, nvnieuwk approved these changes
LGTM!

2023-02-10 20:30 UTC, merged