Sambamba markdup
nf-core/modules pull request #2838
Opened 2023-02-05 11:42 UTC by BioInf2305

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-02-06 08:29 UTC, nvnieuwk requested changes
Some small suggestions

2023-02-06 08:29 UTC, nvnieuwk commented on modules/nf-core/sambamba/markdup/main.nf
> +        tuple val(meta), path(bam)
```suggestion
    tuple val(meta), path(bam)
```

To stay consistent with the other modules

2023-02-06 08:29 UTC, nvnieuwk commented on modules/nf-core/sambamba/markdup/main.nf
> +    tuple val(meta), path("*.mrkDup.bam"), emit: bam
```suggestion
    tuple val(meta), path("*.bam"), emit: bam
```

It's preferred to not add custom suffixes to the filename. It's better to let the user do this via the `task.ext.prefix` variable. You can always add a check to see if the input filename is the same as the output filename (and let it throw an error if it is the same) => paragraph 6 here: https://nf-co.re/docs/contributing/modules#naming-conventions

2023-03-07 09:25 UTC, matthdsm commented on modules/nf-core/sambamba/markdup/main.nf
> +        ${prefix}.mrkDup.bam
```suggestion
        ${prefix}.bam
```

2023-03-07 09:26 UTC, matthdsm commented on modules/nf-core/sambamba/markdup/meta.yml
> +      pattern: "*.mrkDup.{bam,cram,sam}"
```suggestion
      pattern: "*.{bam,cram,sam}"
```

2023-03-07 09:52 UTC, nvnieuwk approved these changes
LGTM, I would also suggest to maybe add a check that looks if the input and output file have the same name (see [here](https://nf-co.re/docs/contributing/modules#naming-conventions) part 6)

2023-03-07 10:01 UTC, merged