New subworkflow vcf_impute_glimpse
nf-core/modules pull request #2858
Opened 2023-02-08 16:20 UTC by LouisLeNezet

## PR checklist

Here my first workflow for nf-core on glimpse imputation.

- [x] This comment contains a description of changes (with reason).
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-02-09 08:15 UTC, LouisLeNezet commented
Link to issue #2857

2023-02-09 11:02 UTC, nvnieuwk requested changes
Good job, here are some improvement suggestions

2023-02-09 11:02 UTC, nvnieuwk commented on subworkflows/nf-core/vcf_impute_glimpse/meta.yml
> +input:
Inputs in subworkflows should be seperated per input channel. You can describe in the descriptions of each channel what files should be in it (preferable with the structure), see here for an example: https://github.com/nf-core/modules/blob/master/subworkflows/nf-core/vcf_extract_relate_somalier/meta.yml

2023-02-09 11:02 UTC, nvnieuwk commented on subworkflows/nf-core/vcf_impute_glimpse/meta.yml
> +        e.g. [ id:'test' ]
Same for the output meta

2023-02-13 08:24 UTC, nvnieuwk requested changes

2023-02-13 08:24 UTC, nvnieuwk commented on modules/nf-core/glimpse/ligate/main.nf
> +    tuple val(meta), val(input_list)
```suggestion
    tuple val(meta), path(input_list)
```

This way the files get staged correctly (it's better when running with data stored on the cloud)

2023-02-13 10:50 UTC, nvnieuwk approved these changes
LGTM

2023-02-13 10:58 UTC, LouisLeNezet commented
Thanks a lot @nvnieuwk

2023-02-13 10:58 UTC, merged