Hicexplorer hicpca
nf-core/modules pull request #2933
Opened 2023-02-28 22:43 UTC by jianhong

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-06-26 10:24 UTC, sguizard requested changes
LGTM. 
Just added 2 suggestions and asked to add more keywords to meta file.

2023-06-26 10:24 UTC, sguizard commented on modules/nf-core/hicexplorer/hicpca/main.nf
> +    path("versions.yml")                              , emit:versions
```suggestion
    tuple val(meta), path("${prefix}_*")           , emit:results
    tuple val(meta), path("${prefix}_pca1.$format"), emit:pca1
    tuple val(meta), path("${prefix}_pca2.$format"), emit:pca2
    path("versions.yml")                           , emit:versions
```

2023-06-26 10:24 UTC, sguizard commented on modules/nf-core/hicexplorer/hicpca/main.nf
> +    format = 'bigwig'
```suggestion
    def args = task.ext.args ?: ''
    prefix   = task.ext.prefix ?: "${meta.id}"
    args     = args.tokenize()
    def idx  = args.findIndexOf{ it == '--format' | it == '-f' }
    format   = 'bigwig'
```

2023-06-26 10:24 UTC, sguizard commented on modules/nf-core/hicexplorer/hicpca/meta.yml
> +  - sort
More keywords needed please.

2023-07-14 11:04 UTC, jianhong commented
@sguizard Could you please take a second view?

2023-07-17 08:46 UTC, sguizard approved these changes

2023-07-17 11:43 UTC, merged