started adding AuthentiCT module
nf-core/modules pull request #2961
Opened 2023-03-03 10:28 UTC by scarlhoff

## PR checklist

Closes #2886 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-03 10:43 UTC, StephanePeyregne requested changes

2023-03-03 10:43 UTC, StephanePeyregne commented on modules/nf-core/authentict/deam2cont/main.nf
> +        'quay.io/biocontainers/authentict:1.0.0--py311h9f5acd7_0' }"
```suggestion
        'https://depot.galaxyproject.org/singularity/authentict:1.0.0--py311h9f5acd7_1':
        'quay.io/biocontainers/authentict:1.0.0--py311h9f5acd7_1' }"
```

2023-03-03 10:43 UTC, StephanePeyregne commented on modules/nf-core/authentict/deam2cont/main.nf
> +        $bam \\
```suggestion
```

2023-03-03 10:43 UTC, StephanePeyregne commented on modules/nf-core/authentict/deam2cont/main.nf
> +    AuthentiCT \\
```suggestion
    samtools view $args $bam | AuthentiCT \\
```

2023-03-03 10:43 UTC, StephanePeyregne commented on modules/nf-core/authentict/deam2cont/main.nf
> +    def args = task.ext.args ?: ''
```suggestion
    def args = task.ext.args ?: ''
    def args2 = task.ext.args2 ?: ''
```

2023-03-03 10:43 UTC, StephanePeyregne commented on modules/nf-core/authentict/deam2cont/main.nf
> +        $args \\
```suggestion
        $args2 \\
```

2023-03-03 11:04 UTC, scarlhoff commented
Samtools version in the container is broken, replace with a different version
remember MD fields required for input

2023-03-24 09:47 UTC, jfy133 requested changes
Almost there :)

2023-03-24 09:47 UTC, jfy133 commented on modules/nf-core/authentict/deam2cont/main.nf
> +        authentict: \$(echo \$(AuthentiCT --version 2>&1) )
Missing `samtools` version

2023-03-24 09:47 UTC, jfy133 commented on modules/nf-core/authentict/deam2cont/meta.yml
> +      pattern: "*"
Missing indication whether the files are mandatory or optional

2023-03-24 09:56 UTC, scarlhoff commented on modules/nf-core/authentict/deam2cont/meta.yml
> +      description: text file with positions that sequences should overlap
```suggestion
      description: Optional text file with positions that sequences should overlap
```

2023-03-24 09:58 UTC, jfy133 commented on modules/nf-core/authentict/deam2cont/meta.yml
> +      description: BAM/CRAM/SAM file
```suggestion
      description: BAM/CRAM/SAM file (Mandatory)
```

2023-03-24 09:58 UTC, jfy133 approved these changes

2023-03-24 10:32 UTC, StephanePeyregne approved these changes

2023-03-24 10:33 UTC, merged