update, unify cellranger module metadata
nf-core/modules pull request #2972
Opened 2023-03-06 22:13 UTC by klkeys

## PR checklist

Fixes missing `cellranger` module metadata from #2914. Slightly harmonizes the text between `cellranger` submodules.

2023-03-06 22:46 UTC, Emiller88 requested changes
I think these are technically all uppercase (according to wikipedia) but I've seen it all sorts of ways, as long as we're consistent across everything.

2023-03-06 22:46 UTC, Emiller88 commented on modules/nf-core/cellranger/mkref/meta.yml
> +      description: Reference genome FastA file
```suggestion
      description: Reference genome FASTA file
```

2023-03-06 22:46 UTC, Emiller88 commented on modules/nf-core/cellranger/mkfastq/meta.yml
> +description: Module to create FastQs needed by the 10x Genomics Cell Ranger tool. Uses the cellranger mkfastq command.
```suggestion
description: Module to create FASTQs needed by the 10x Genomics Cell Ranger tool. Uses the cellranger mkfastq command.
```

2023-03-07 05:06 UTC, klkeys reviewed
changes from @Emiller88 incorporated 👍🏼

2023-03-07 07:48 UTC, matthdsm approved these changes

2023-03-07 08:15 UTC, mashehu approved these changes

2023-03-07 08:34 UTC, merged