Subworkflow: parallelise vep
nf-core/modules pull request #3006
Opened 2023-03-09 07:44 UTC by matthdsm

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-09 07:45 UTC, matthdsm commented
@maxulysse , @nvnieuwk, time to start tearing this down!

2023-03-09 08:02 UTC, nvnieuwk commented
![gif](https://media.giphy.com/media/Nk6ogPmovLtGMkXm5j/giphy.gif)

2023-03-09 08:13 UTC, nvnieuwk requested changes
Good luck 😁

2023-03-09 09:14 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
>      vep_species       //   value: species to use
so fasta is no longer optionnal?
And do we really need tbis?

2023-03-09 09:14 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
why creating a `new_meta` if you're not using it

2023-03-09 09:15 UTC, maxulysse commented on tests/subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +    input = Channel.of([
<3

2023-03-09 09:16 UTC, nvnieuwk commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
>      vep_species       //   value: species to use
Fixed!

2023-03-09 09:17 UTC, nvnieuwk commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
I must have been distracted while reviewing this, sorry 😁, I'll change it!

2023-03-09 09:19 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
why calling it `new_meta` when it's actually only the number of elements in the list?

2023-03-09 09:21 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
I'd rather we do:
```suggestion
    BCFTOOLS_SPLIT(ch_vcf)
    ch_split_vcf = BCFTOOLS_SPLIT.out.split_vcf
        .map{ meta, vcf -> [ meta + [ size:vcf instanceof List ? vcf.size() : 1 ], vcf instanceof List ? vcf : [ vcf ] ] }.transpose()
```

2023-03-09 09:24 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
whit of course some added comments

2023-03-09 09:33 UTC, maxulysse commented
> The code itself looks fine, but you should add some explanation about the chunking in the docs. VEP has a large overhead to running which will affect the number of chunks (i.e., anyone using cloud processing will want to not split).

+1 can we had a boolean as an input to this subworkflow to disable splitting?

2023-03-09 09:34 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +            return [groupKey(meta - meta.subMap('chunks'), meta.chunks), vcf]
```suggestion
            return [groupKey(meta - meta.subMap('size'), meta.size), vcf]
```

2023-03-09 09:36 UTC, matthdsm commented
Actually, I'm considering dropping this altogether, since @nvnieuwk had a much better idea wrt parallelisation.
We can scan the tbi for contigs and then give those to vep to limit the regions. That way we avoid a bunch of IO and file shuffling

👍🏻  if you're pro
👎🏻  if you're against

2023-03-09 09:37 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
`count`?

2023-03-09 09:38 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
`split_count`

2023-03-09 09:38 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
`vcf_split_size`?

2023-03-09 09:40 UTC, nvnieuwk commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
I like that one!

2023-03-09 09:46 UTC, maxulysse commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> +        .transpose()
as long we remove it after the subworkflows, I'm happy

2023-03-09 11:25 UTC, matthdsm commented
> You're assuming quite a lot by splitting per contig
Well we're kind of doing the same right now with splitting the file by chr, no?

2023-03-13 07:04 UTC, matthdsm commented
For those interested: https://github.com/bioconda/bioconda-recipes/pull/39868

2023-05-05 07:04 UTC, closed without merging