Glimpse2 concordance
nf-core/modules pull request #3007
Opened 2023-03-09 11:17 UTC by LouisLeNezet

## PR checklist

Final module of GLIMPSE2.

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-09 15:12 UTC, nvnieuwk requested changes
Mainly some small suggestions to meta and outputs, otherwise very good job this didn't look like an easy one :)

2023-03-09 15:12 UTC, nvnieuwk commented on modules/nf-core/glimpse2/concordance/main.nf
> +    tuple val(meta2), path(groups), val(bins), val(ac_bins), val(allele_counts)
This is bit of a bummer situation but I don't see a better solution indeed, good job!

2023-03-09 15:12 UTC, nvnieuwk commented on modules/nf-core/glimpse2/concordance/main.nf
> +    tuple val(meta), path("*.rsquare.*.txt.gz"), emit: rsquare
Can you make a separate output for each `errors` or `rsquare` file created? It's usually easier to merge them than to split them on file name for example :)

2023-03-09 15:12 UTC, nvnieuwk commented on modules/nf-core/glimpse2/concordance/main.nf
> +    if (((groups ? 1:0) + (bins ? 1:0) + (ac_bins ? 1:0) + (allele_counts ? 1:0)) != 1) error "One and only one argument should be selected between groups, bins, ac_bins, allele_counts"
Smart!

2023-03-09 15:12 UTC, nvnieuwk commented on modules/nf-core/glimpse2/concordance/meta.yml
> +      description: Imputed data.
Can you make this description a bit more clear?

2023-03-09 15:12 UTC, nvnieuwk commented on modules/nf-core/glimpse2/concordance/meta.yml
> +      pattern: "*.{txt,tsv}"
Can you add the other inputs (`bins`, `ac_bins` and `allele_counts` too?)

2023-03-10 08:19 UTC, matthdsm commented on modules/nf-core/glimpse2/concordance/meta.yml
> +        Minimum coverage in validation data.
```suggestion
        Minimum coverage in validation data.
```

2023-03-10 08:23 UTC, merged