Centrifuge db build
nf-core/modules pull request #3008
Opened 2023-03-09 13:42 UTC by sarah-buddle

## PR checklist

Closes #2956   

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-09 14:16 UTC, sofstam requested changes
Nice work! A few suggestions :)

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +        'quay.io/biocontainers1.0.4--hd03093a_0' }"
```suggestion
        'quay.io/biocontainers/centrifuge:1.0.4--hd03093a_0' }"
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +    tuple val(meta), path("*.cf"), emit: cf
```suggestion
    tuple val(meta), path("*.cf").    , emit: cf
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +
```suggestion
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +    path taxonomy
```suggestion
    path taxonomy_tree
```

Looking at the documentation, I am thinking if we should rename taxonomy like that instead

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +    --taxonomy-tree $taxonomy \\
```suggestion
    --taxonomy-tree $taxonomy_tree \\
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/meta.yml
> +      description: fasta file containing sequences to be used in database
```suggestion
      description: Fasta file containing sequences to be used in centrifuge database.
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/meta.yml
> +      pattern: "*.{fasta}"
```suggestion
      pattern: "*.{fasta,fna}"
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/meta.yml
> +      description: a tab-separated sequence ID to taxonomy ID mapping
```suggestion
      description: A tab-separated file with sequence ID to taxonomy ID mapping
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/meta.yml
> +      description: \t|\t-separated file mapping taxonomy. Typically nodes.dmp from the NCBI taxonomy dump. Links taxonomy IDs to their parents
```suggestion
      description: A \t|\t-separated file mapping taxonomy. Typically nodes.dmp from the NCBI taxonomy dump. Links taxonomy IDs to their parents
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/meta.yml
> +      description: '|'-separated file mapping taxonomy IDs to a name. Typically names.dmp from the NCBI taxonomy dump. Links taxonomy IDs to their scientific name
```suggestion
      description: A '|'-separated file mapping taxonomy IDs to a name. Typically names.dmp from the NCBI taxonomy dump. Links taxonomy IDs to their scientific name
```

2023-03-09 14:16 UTC, sofstam commented on modules/nf-core/centrifuge/build/meta.yml
> +      description: Index files of the database
```suggestion
      description: Index files of the centrifuge database
```

2023-03-09 14:16 UTC, sofstam commented on tests/config/pytest_modules.yml
> +  - tests/modules/nf-core/kraken2/build/**
```suggestion
```

2023-03-09 14:16 UTC, sofstam commented on tests/config/pytest_modules.yml
> +  - tests/modules/nf-core/kraken2/build/**
```suggestion
```

2023-03-09 14:16 UTC, sofstam commented on tests/config/pytest_modules.yml
> +  - modules/nf-core/kraken2/build/**
```suggestion
```

2023-03-09 14:16 UTC, sofstam commented on tests/config/pytest_modules.yml
> +  - tests/modules/nf-core/metamix/**
```suggestion
```

2023-03-09 14:16 UTC, sofstam commented on tests/config/pytest_modules.yml
> +  - modules/nf-core/metamix/**
```suggestion
```

2023-03-09 14:16 UTC, sofstam commented on tests/config/pytest_modules.yml
> +metamix:
```suggestion
```

2023-03-09 14:16 UTC, sofstam commented on tests/modules/nf-core/centrifuge/build/main.nf
> +   //// params.test_data['sarscov2']['genome']['genome_fasta']
```suggestion

```

2023-03-09 14:22 UTC, sarah-buddle commented on tests/config/pytest_modules.yml
> +  - modules/nf-core/kraken2/build/**
Remove files from kraken test

2023-03-09 14:28 UTC, sarah-buddle commented on modules/nf-core/centrifuge/build/main.nf
> +    tuple val(meta), path("*.cf"), emit: cf
What is this for?

2023-03-09 14:44 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +    tuple val(meta), path("*.cf"), emit: cf
Sorry, the `.` is a typo.

2023-03-09 16:31 UTC, sofstam requested changes
A few minor comments and after the tests pass, we can merge 🎉

2023-03-09 16:31 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +    tuple val(meta), path("*.cf").    , emit: cf
```suggestion
    tuple val(meta), path("*.cf")   , emit: cf
```

I removed the unnecessary `.`

2023-03-09 16:31 UTC, sofstam commented on tests/config/pytest_modules.yml
> +kraken2/build:
```suggestion
```

This should be removed as well.

2023-03-09 16:31 UTC, sofstam commented on tests/config/pytest_modules.yml
> +
```suggestion
```

2023-03-09 16:31 UTC, sofstam commented on tests/modules/nf-core/centrifuge/build/main.nf
> +
```suggestion
```

2023-03-09 16:31 UTC, sofstam commented on tests/modules/nf-core/centrifuge/build/main.nf
> +
```suggestion
```

2023-03-09 16:31 UTC, sofstam commented on tests/modules/nf-core/centrifuge/build/main.nf
> +
```suggestion
```

2023-03-09 16:31 UTC, sofstam commented on tests/modules/nf-core/centrifuge/build/main.nf
> +
```suggestion
```

2023-03-09 16:31 UTC, sofstam commented on tests/modules/nf-core/centrifuge/build/main.nf
> +
```suggestion
```

2023-12-18 15:02 UTC, sofstam reviewed
🚀

2023-12-18 15:02 UTC, sofstam commented on modules/nf-core/centrifuge/build/main.nf
> +    path size_table
Is this used somewhere as argument?

2023-12-18 15:02 UTC, sofstam commented on modules/nf-core/centrifuge/build/tests/main.nf.test
> +                input[4] = []
Is this supposed to be empty?

2023-12-20 08:09 UTC, maxulysse commented on modules/nf-core/centrifuge/build/tests/main.nf.test
> +                input[4] = []
I'm guessing it's optional

2023-12-20 08:09 UTC, maxulysse commented on modules/nf-core/centrifuge/build/meta.yml
> +  - size_table:
shouldn't we say it's optional

2023-12-20 16:53 UTC, sateeshperi commented on modules/nf-core/centrifuge/build/tests/nextflow.config
> +
can remove empty file

2024-02-13 13:10 UTC, jfy133 commented on modules/nf-core/centrifuge/build/tests/main.nf.test
> +                input[4] = []
YEs correct! Updated meta

2024-02-13 14:16 UTC, sofstam approved these changes
🚀

2024-02-13 14:23 UTC, merged

2024-02-13 14:29 UTC, jfy133 commented
Thanks @sarah-buddle for doing the majority of the legwork on that one! We beat a year since beginning :laughing: