Clair3
nf-core/modules pull request #3058
Opened 2023-03-20 13:11 UTC by yuukiiwa

`conda` environment couldn't be resolved

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-11-04 21:47 UTC, sateeshperi requested changes

2023-11-04 21:47 UTC, sateeshperi commented on modules/nf-core/clair3/main.nf
> +        'quay.io/biocontainers/clair3:1.0.0--py39hb9dc472_1' }"
```suggestion
        'biocontainers/clair3:1.0.0--py39hb9dc472_1' }"
```

2023-11-04 21:47 UTC, sateeshperi commented on modules/nf-core/clair3/main.nf
> +    path "versions.yml"                  , emit: versions
```suggestion
    tuple val(meta), path("${meta.id}/*") , emit: vcf
    path "versions.yml"                   , emit: versions
```

2023-11-04 21:47 UTC, sateeshperi commented on modules/nf-core/clair3/main.nf
> +    """
recommend adding a `stub:` section

2023-11-04 21:47 UTC, sateeshperi commented on modules/nf-core/clair3/meta.yml
> +  - short-variant calling
```suggestion
  - germline
  - short-variant calling
  - long-reads
```

2025-03-10 14:55 UTC, SPPearce commented
Superceded by #7765

2025-03-10 14:55 UTC, closed without merging