Sniffles
nf-core/modules pull request #3061
Opened 2023-03-20 13:12 UTC by yuukiiwa

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-21 14:03 UTC, nvnieuwk requested changes

2023-03-22 06:00 UTC, yuukiiwa commented on tests/modules/nf-core/sniffles/main.nf
Thanks! Got that added

2023-03-22 06:01 UTC, yuukiiwa commented on modules/nf-core/sniffles/meta.yml
> +  - fasta:
added it in

2023-03-22 06:47 UTC, yuukiiwa commented on tests/modules/nf-core/sniffles/main.nf
> +workflow test_sniffles {
Thanks for the suggestion! I tried adding CRAM files locally for testing, but the test failed (please see screenshot attached below). I guess I won't be adding it then
![Screenshot from 2023-03-22 14-45-39](https://user-images.githubusercontent.com/41866052/226823647-7aa67278-9548-43bd-9c23-af1a3f43a39d.png)

2023-03-22 08:09 UTC, nvnieuwk commented on tests/modules/nf-core/sniffles/main.nf
> +workflow test_sniffles {
Something seems wrong with the reference causing Sniffles to not be able to read the CRAM file...

2023-03-22 08:10 UTC, nvnieuwk approved these changes

2023-03-23 01:33 UTC, merged