New Subworkflow: Bam_trim_primers_ivar
nf-core/modules pull request #3130
Opened 2023-03-27 13:26 UTC by Joon-Klaps

## PR checklist

Addresses first bullet from https://github.com/nf-core/viralrecon/issues/371  

adds the subworkflow bam_trim_primers_ivar used in nf-core/viralrecon to nf-core/modules

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-27 14:05 UTC, nvnieuwk requested changes

2023-03-27 14:05 UTC, nvnieuwk commented on subworkflows/nf-core/bam_trim_primers_ivar/main.nf
> +    fasta // channel: reference.fasta
```suggestion
    ch_bam   // channel: [ val(meta), path(bam), path(bai) ]
    ch_bed   // channel: [ path(bed) ]
    ch_fasta // channel: [ path(fasta) ]
```

Can you also change the output comments to this format? All channels should start with `ch_` (except for the output names of the subwf) and all values should start with `val_`

2023-03-27 14:11 UTC, Joon-Klaps commented on subworkflows/nf-core/bam_trim_primers_ivar/meta.yml
Aah... I forgot about this one

2023-03-27 14:13 UTC, nvnieuwk commented on subworkflows/nf-core/bam_trim_primers_ivar/meta.yml
No problem!

2023-03-28 07:43 UTC, nvnieuwk reviewed
One more small comment and then you are good to go!

2023-03-28 07:43 UTC, nvnieuwk commented on subworkflows/nf-core/bam_trim_primers_ivar/main.nf
> +    bam_orig = IVAR_TRIM.out.bam                    // channel: [ val(meta), bam   ]
```suggestion
    bam_orig = IVAR_TRIM.out.bam                    // channel: [ val(meta), path(bam) ]
```

Can you add paths to all the files in the comments (see above for an example :))

2023-03-28 07:43 UTC, nvnieuwk commented on subworkflows/nf-core/bam_trim_primers_ivar/meta.yml
> +        e.g. [ id:'test' ], BAM/CRAM/SAM file, index file for co-ordinate sorted BAM file
This is awesome! Thanks 🥳

2023-03-28 09:38 UTC, Joon-Klaps commented
Not Sure why conda test is failing though..

2023-03-28 09:44 UTC, nvnieuwk commented
It seems to be something tool specific. Maybe a wrong conda package?

2023-03-28 13:09 UTC, Joon-Klaps commented
> It seems to be something tool specific. Maybe a wrong conda package?

Yeah... doesn't seem something I'll be able to finish as part of this PR... https://github.com/andersen-lab/ivar/issues/93

2024-06-03 06:38 UTC, closed without merging