Metaphlan/makedb
nf-core/modules pull request #3138
Opened 2023-03-27 13:50 UTC by LilyAnderssonLee

## PR checklist

Closes #2954  

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-27 15:21 UTC, sofstam requested changes
Nice work!

2023-03-27 15:21 UTC, sofstam commented on modules/nf-core/metaphlan/makedb/meta.yml
> +description: Builds a METAPHLAN database
```suggestion
description: Build MetaPhlAn3 database for taxonomic profiling.
```

2023-03-27 15:21 UTC, sofstam commented on modules/nf-core/metaphlan/makedb/meta.yml
> +  - latest
```suggestion
  - metagenomics
```

2023-03-27 15:21 UTC, sofstam commented on modules/nf-core/metaphlan/makedb/meta.yml
> +      pattern: "*"
```suggestion
      pattern: "*/"
```

2023-03-27 18:26 UTC, LilyAnderssonLee commented on modules/nf-core/metaphlan/makedb/meta.yml
> +      pattern: "*"
OK

2023-03-27 18:49 UTC, LilyAnderssonLee commented on modules/nf-core/metaphlan/makedb/meta.yml
> +  - latest
Great!

2023-03-28 07:13 UTC, sofstam approved these changes
Two minor suggestions and ready to merge.

2023-03-28 07:13 UTC, sofstam commented on modules/nf-core/metaphlan/makedb/main.nf
> +    path "metaphlan_db_latest" , emit: db
```suggestion
    path "metaphlan_db_latest"      , emit: db
```

2023-03-28 07:13 UTC, sofstam commented on modules/nf-core/metaphlan/makedb/meta.yml
> +      description: Output directory containing the indexed METAPHLAN3 database
```suggestion
      description: Output directory containing the indexed MetaPhlAn3 database
```

2023-03-28 07:44 UTC, merged