Remove runOptions from docker profile
nf-core/modules pull request #315
Opened 2021-03-22 18:13 UTC by heuermh

WIP, removing `runOptions` from the test docker profile to see what fails, if anything

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `<SOFTWARE>.version.txt` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-03-22 18:16 UTC, heuermh commented
Hmm, our CI config is too clever 😉 

Is there any way to force CI all the module tests?

2021-03-22 23:59 UTC, Emiller88 requested changes
Just leaving this as a reminder to drop my commits before someone merges this while I'm asleep.

2021-03-22 23:59 UTC, Emiller88 commented on .github/workflows/pytest-workflow-all.yml
> +            /home/runner/pytest_workflow_*/*/log.err
Drop my commits before merging

2021-05-27 17:23 UTC, heuermh commented
Closing in favor of #525

2021-05-27 17:23 UTC, closed without merging