Addition of new module: Issue #3113 Survivor/filter
nf-core/modules pull request #3168
Opened 2023-03-28 10:26 UTC by LlaneroHiboreo

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-03-28 12:48 UTC, nvnieuwk requested changes
Good job! here are some comments

2023-03-28 12:48 UTC, nvnieuwk commented on modules/nf-core/survivor/filter/main.nf
> +    path(bed)           // file with regions to ignore (NA to disable)
Can you merge these two inputs (`tuple val(meta), path(vcf_file), path(bed)`) I think it's worth it here to be able to specify a separate BED file for each input

2023-03-28 12:48 UTC, nvnieuwk commented on modules/nf-core/survivor/filter/main.nf
> +}
Can you add a stub section?

2023-03-28 12:48 UTC, nvnieuwk commented on modules/nf-core/survivor/filter/main.nf
> +        ${prefix}.survivor_filter.vcf
```suggestion
        ${prefix}.vcf
```
It's preferred to add a check and keep the file names as flexible as possible. see [here](https://nf-co.re/docs/contributing/modules#naming-conventions) part 6 for more info :)

2023-03-28 12:48 UTC, nvnieuwk commented on tests/modules/nf-core/survivor/filter/main.nf
Can you also add a test with a BED file?

2023-03-28 21:55 UTC, LlaneroHiboreo commented
I have upgraded the code with the given suggestions. Thanks for reviewing.

2023-03-29 08:00 UTC, nvnieuwk commented on modules/nf-core/survivor/filter/main.nf
> +
Can you also add a check to see if the input and output VCF aren't called the same? (this will cause weird errors)

2023-03-29 09:52 UTC, LlaneroHiboreo commented
All requested changes should be present now!!

2023-03-29 10:58 UTC, nvnieuwk commented on modules/nf-core/survivor/filter/main.nf
> +        prefix = "${meta.id}_filtered"
```suggestion
        error "Input and output names are the same, set prefix in module configuration to disambiguate!"
```

We prefer it to give an error so the user knows what they are doing without having some suffixes that didn't want

2023-03-29 10:59 UTC, nvnieuwk commented on modules/nf-core/survivor/filter/main.nf
> +        prefix = "${meta.id}_filtered"
Can you also add this check to the stub section?

2023-03-29 10:59 UTC, nvnieuwk commented on modules/nf-core/survivor/filter/main.nf
> +    if( "$bed" == "${prefix}.bed" ){
```suggestion
    if( "$vcf_file" == "${prefix}.vcf" ){
```

2023-03-29 11:18 UTC, nvnieuwk approved these changes
LGTM!

2023-03-29 11:20 UTC, LlaneroHiboreo commented
> LGTM!

Pushed final changes. Thanks again

2023-03-30 05:10 UTC, merged