New Module: Seqtk cutN
nf-core/modules pull request #3239
Opened 2023-03-31 15:45 UTC by DLBPointon

## PR checklist

Closes #3221  

This PR adds the SeqTK cutN command, this command takes a fasta file and produces a summary bed file detailing the genomic co-ords of lengths of N.

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [X] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-04-05 10:44 UTC, priyanka-surana requested changes
Looks good. A couple changes to `meta.yml`

2023-04-05 10:44 UTC, priyanka-surana commented on modules/nf-core/seqtk/cutn/meta.yml
> +  - reads:
Change `reads` to `fasta` to match the `main.nf`
```suggestion
  - fasta:
```

2023-04-05 10:44 UTC, priyanka-surana commented on modules/nf-core/seqtk/cutn/meta.yml
> +  - reads:
Change `reads` to `fasta` to match the `main.nf`
```suggestion
  - bed:
```

2023-04-06 08:03 UTC, nvnieuwk approved these changes
One small nitpicky comment but otherwise LGTM!

2023-04-06 08:08 UTC, priyanka-surana approved these changes

2023-04-11 09:37 UTC, merged