Added the MD5 checksums for the delly/call tests
nf-core/modules pull request #3246
Opened 2023-04-01 04:33 UTC by muffato

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-04-03 07:30 UTC, nvnieuwk commented
These files contained time stamps, that's why they had no md5sum :)

2023-04-03 14:27 UTC, muffato commented
Oh. The MD5 checksums I put there worked this weekend (HPC + GitHub CI) and still work today.
I did notice that for instance Freebayes puts the date of the day in its VCF files, so I'm not surprised delly/call would do that too, but I can't replicate that. Would you mind giving it a try locally ?

2023-04-03 14:29 UTC, nvnieuwk commented
Oh cool, maybe they removed it in a newer version. I'll have a check locally but if it stays the same it should be fine :)

2023-04-03 14:30 UTC, muffato commented
OH wait a sec. I was wrong ! I was testing the wrong branch locally !
Can you please unapprove this PR, it shouldn't be merged !

2023-04-03 14:33 UTC, nvnieuwk requested changes
I found this in the header `##fileDate=20230403`

2023-04-03 14:34 UTC, nvnieuwk commented
Didn't see your comments 😁, I'm not sure comments are allowed... maybe ask over at slack :)

2023-04-04 07:25 UTC, nvnieuwk approved these changes
Awesome LGTM!

2023-04-04 08:28 UTC, merged