New Subworkflow: `fastq_ena_prep_adapterremoval`
nf-core/modules pull request #3295
Opened 2023-04-15 11:40 UTC by TCLamnidis

This reimplements [maxibor/enaprep](https://github.com/maxibor/enaprep) into a DSL2 subworkflow.

First, adapters are trimmed from FastQ files without any filtering or collapsing using AdapterRemoval. 
Then, the md5sums of the different trimmed FastQ files are calculated, collated and published in a file named `checksums.md5`.

## PR checklist

Closes #3294 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-04-15 11:41 UTC, TCLamnidis commented
- Should I rename the SWF to `_adapterremoval_md5sum`?

2023-04-28 07:01 UTC, jfy133 requested changes
I agree to the renaming to make it more 'general' but otherwise looks OK

2023-04-28 07:01 UTC, jfy133 commented on subworkflows/nf-core/fastq_ena_prep_adapterremoval/nextflow.config
> +    }
Make sure all other quality/and or lenght filtering is turned off: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/reads.html#fastq-format

2023-04-28 08:30 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_ena_prep_adapterremoval/main.nf
> +    ch_reads        // channel: [ val(meta), [ fastq ], val(phred_plus) ]
in 90% of cases I would not expect a mix, but why limit the SWF, when a dev will need to do very minor channel tweaks to add that field within the channel?

2023-05-04 12:46 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_ena_prep_adapterremoval/meta.yml
> +description: Trim adapters from FastQs to ENA specification, and calculate checksums.
Added that link to SWF description

2023-05-04 12:47 UTC, TCLamnidis commented
Renamed:
`fastq_ena_prep_adapterremoval` -> `fastq_ena_prep_adapterremoval_md5sum`

2023-08-04 09:17 UTC, closed without merging