Check that input and output names are different
nf-core/modules pull request #3355
Opened 2023-05-02 06:26 UTC by ekushele

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-05-02 09:37 UTC, nvnieuwk requested changes

2023-05-02 09:37 UTC, nvnieuwk commented on modules/nf-core/gnu/sort/main.nf
> +    if ("$input" == "$output_file") error "Input and output names are the same, use \"task.ext.prefix\" to disambiguate!"
Can you also add this to the stub?

2023-05-02 09:41 UTC, nvnieuwk approved these changes
LGTM!!

2023-05-02 09:42 UTC, nvnieuwk commented
Only linting fixes left to do

2023-05-02 17:20 UTC, ekushele commented
@nvnieuwk fixed linting issues

2023-05-03 06:16 UTC, nvnieuwk approved these changes

2023-05-03 06:58 UTC, merged