icount mini segment
nf-core/modules pull request #3372
Opened 2023-05-03 12:15 UTC by CharlotteAnne

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-05-03 14:36 UTC, chris-cheshire requested changes

2023-05-03 14:36 UTC, chris-cheshire commented on modules/nf-core/icountmini/segment/main.nf
> +
remove line

2023-05-03 14:36 UTC, chris-cheshire commented on modules/nf-core/icountmini/segment/main.nf
> +    tuple val(meta), path("*_seg.gtf")                  ,  emit: gtf
Sort out whitespace

2023-05-03 14:36 UTC, chris-cheshire commented on tests/config/test_data.config
> +                genome_21_gtf                                  = "${params.test_data_base}/data/genomics/homo_sapiens/genome/chr21/sequence/chr21_gencode.gtf"
Same comment as the clippy PR

2023-05-08 08:26 UTC, CharlotteAnne commented on modules/nf-core/icountmini/segment/main.nf
> +    tuple val(meta), path("*_seg.gtf")                  ,  emit: gtf
again, not seeing the issue, sorry?

2023-05-08 08:30 UTC, CharlotteAnne commented on tests/config/test_data.config
> +                genome_21_gtf                                  = "${params.test_data_base}/data/genomics/homo_sapiens/genome/chr21/sequence/chr21_gencode.gtf"
updated

2023-05-09 10:26 UTC, chris-cheshire approved these changes

2023-05-09 14:32 UTC, merged