Bump taxpasta version
nf-core/modules pull request #3586
Opened 2023-07-02 19:01 UTC by jfy133

As on the tin

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-07-02 19:53 UTC, pontus approved these changes

2023-07-02 20:50 UTC, Midnighter requested changes
You forgot the conda versions 😉 

Is the `pyhdfd78af` part already guaranteed? Or do we need to wait for the container to get confirmation on that?

2023-07-02 20:50 UTC, Midnighter commented on modules/nf-core/taxpasta/merge/main.nf
>      conda "bioconda::taxpasta=0.2.3"
```suggestion
    conda "bioconda::taxpasta=0.4.0"
```

2023-07-02 20:50 UTC, Midnighter commented on modules/nf-core/taxpasta/standardise/main.nf
>      conda "bioconda::taxpasta=0.2.3"
```suggestion
    conda "bioconda::taxpasta=0.4.0"
```

2023-07-02 20:50 UTC, Midnighter commented on modules/nf-core/taxpasta/merge/main.nf
> +        'https://depot.galaxyproject.org/singularity/taxpasta:0.4.0--pyhdfd78af_0 ':
```suggestion
        'https://depot.galaxyproject.org/singularity/taxpasta:0.4.0--pyhdfd78af_0':
```

2023-07-03 03:48 UTC, jfy133 commented
> You forgot the conda versions 😉 
> 
> Is the `pyhdfd78af` part already guaranteed? Or do we need to wait for the container to get confirmation on that?

The container was already built at 18:43 yesterday! I took the string directly from the galaxy depot website :)

2023-07-03 14:48 UTC, Midnighter approved these changes

2023-07-03 14:50 UTC, merged