Initialise mmseqs createtsv
nf-core/modules pull request #3603
Opened 2023-07-05 13:08 UTC by Joon-Klaps

## PR checklist

Create a summary tsv file of a query target and result MMseqs database

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-07-05 16:27 UTC, Joon-Klaps commented
See the test config to specify the selection of the cluster database (based on the knowledge that this database has the suffix `_clu.dbtype`).

2023-07-06 14:55 UTC, JoseEspinosa requested changes
LGTM! Just some small format suggestions

2023-07-06 14:55 UTC, JoseEspinosa commented on tests/modules/nf-core/mmseqs/createtsv/main.nf
> +    ch_result = UNTAR_RESULT( [[ id:'test_result', single_end:true ],input_file] ).untar
```suggestion
    ch_query = UNTAR_QUERY ([[ id:'test_query', single_end:true ], input_file] ).untar
    ch_target = UNTAR_TARGET( [[ id:'test_target', single_end:true ], input_file] ).untar
    ch_result = UNTAR_RESULT( [[ id:'test_result', single_end:true ], input_file] ).untar
```

2023-07-06 14:55 UTC, JoseEspinosa commented on tests/modules/nf-core/mmseqs/createtsv/main.nf
> +    ch_result = UNTAR_RESULT2( [[ id:'test_result', single_end:true ],input_file] ).untar
```suggestion
    ch_query = UNTAR_QUERY2 ([[ id:'test_query', single_end:true ], input_file] ).untar
    ch_result = UNTAR_RESULT2( [[ id:'test_result', single_end:true ], input_file] ).untar
```

2023-07-06 16:10 UTC, merged