Updated module: removed optional argument from mash/sketch
nf-core/modules pull request #3635
Opened 2023-07-12 22:26 UTC by margotl9

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-07-13 17:47 UTC, CarsonJM requested changes

2023-07-13 17:47 UTC, CarsonJM commented on modules/nf-core/mash/sketch/main.nf
> +    tuple val(meta), path(fasta)
I'm unsure what this variable name should be since FASTA and FASTQ files can both be used as input.

2023-07-13 17:47 UTC, CarsonJM commented on modules/nf-core/mash/sketch/meta.yml
> +      description: Input fasta file
```suggestion
      description: FASTQ or FASTA file that will be sketched
```

2023-07-13 17:47 UTC, CarsonJM commented on tests/modules/nf-core/mash/sketch/test.yml
Since this module is getting updated, perhaps we should add a -stub-run test as well?

2023-07-18 14:09 UTC, CarsonJM commented on modules/nf-core/mash/sketch/main.nf
```suggestion
val(reads)

```

2023-07-19 13:52 UTC, CarsonJM approved these changes

2024-05-14 13:51 UTC, SPPearce commented
Is this PR still wanted? It looks like @CarsonJM has updated the module including to nf-test recently.

2024-05-14 14:58 UTC, closed without merging