Add tests for hisat2 #95
nf-core/modules pull request #366
Opened 2021-03-24 12:24 UTC by ntoda03

## PR checklist

Closes #XXX 

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `<SOFTWARE>.version.txt` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-03-24 14:38 UTC, grst submitted a review, later dismissed
Can you please update this to use the new config file for test data?

2021-03-24 16:15 UTC, ntoda03 commented
Ok, it's been updated to use the new test config file.

2021-03-25 08:12 UTC, JoseEspinosa requested changes
Some `md5` for `bam` and `ht2` checks are failing since they include variable stuff inside (command used for instance).  Just check for them to exist, see [here](https://pytest-workflow.readthedocs.io/en/stable/#test-options).

2021-03-25 10:52 UTC, ntoda03 commented
> Some `md5` for `bam` and `ht2` checks are failing since they include variable stuff inside (command used for instance). Just check for them to exist, see [here](https://pytest-workflow.readthedocs.io/en/stable/#test-options).

Ok I got rid of the md5s for the bam files. For the ht2 checks I just had to update them with the new build method.

2021-03-25 20:03 UTC, JoseEspinosa approved these changes
LGTM

2021-03-25 20:53 UTC, drpatelh commented on software/hisat2/align/meta.yml
> +
```suggestion
```

2021-03-25 20:53 UTC, drpatelh commented on software/hisat2/align/meta.yml
> +
```suggestion
```

2021-03-25 20:53 UTC, drpatelh commented on software/hisat2/extractsplicesites/meta.yml
> +
```suggestion
```

2021-03-25 20:55 UTC, drpatelh approved these changes
Thank you for doing this @ntoda03 ! 😎

2021-03-25 21:08 UTC, merged