Add module mmseqs easysearch
nf-core/modules pull request #3699
Opened 2023-08-04 14:34 UTC by luisas

Add module mmseqs easysearch

Gets as input a fasta file and a database. 
Outputs a tsv file with the summary of the matches. 

## PR checklist

Closes https://github.com/nf-core/modules/issues/3698

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-08-06 15:59 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/easysearch/main.nf
> +    path "versions.yml"               , emit: versions
```suggestion
    path "versions.yml"                   , emit: versions
```

2023-08-06 16:02 UTC, Joon-Klaps commented on tests/modules/nf-core/mmseqs/easysearch/nextflow.config
> +
A small suggestion to clean up the output test.yml 
```suggestion
    withName: MMSEQS_CREATEDB_TARGET {
        publishDir = [ enabled: false ]
    }

```

2023-08-06 16:06 UTC, Joon-Klaps commented
LGTM, just a small edit regarding [the alignment](https://nf-co.re/docs/contributing/modules#what-is-the-harshil-alignment) and a small suggestion to clean up the test yml 🚀

2023-08-06 16:09 UTC, Joon-Klaps requested changes
LGTM, just a small edit regarding [the alignment](https://nf-co.re/docs/contributing/modules#what-is-the-harshil-alignment) and a small suggestion to clean up the test yml. Rerun test and 🚀

2023-08-06 16:09 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/easysearch/main.nf
> +    path "versions.yml"               , emit: versions
```suggestion
    path "versions.yml"                   , emit: versions
```

2023-08-06 16:11 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/easysearch/main.nf
> +    tuple val(meta),  path(fasta)
```suggestion
    tuple val(meta) , path(fasta)
```

2023-08-07 08:55 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/easysearch/main.nf
> +    DB_TARGET_PATH_NAME=\$(find -L "$db_target/" -maxdepth 1 -name "*.dbtype" | sed 's/\\.\\[^.\\]*\$//' | sed -e 'N;s/^\\(.*\\).*\\n\\1.*\$/\\1\\n\\1/;D' )
```suggestion
    DB_TARGET_PATH_NAME=\$(find -L "$db_target/" -maxdepth 1 -name "$args2" | sed 's/\\.\\[^.\\]*\$//' | sed -e 'N;s/^\\(.*\\).*\\n\\1.*\$/\\1\\n\\1/;D' )
```

2023-08-07 09:50 UTC, Joon-Klaps requested changes
Don't forget to rerun the `nf-core modules create-test-yml -t mmseqs/easysearch`

2023-08-07 09:58 UTC, luisas commented
> Don't forget to rerun the `nf-core modules create-test-yml -t mmseqs/easysearch`

Thanks, done now :)

2023-08-07 10:00 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/easysearch/main.nf
> +    def args = task.ext.args ?: ''
```suggestion
    def args = task.ext.args ?: ''
    def args2 = task.ext.args2 ?: "*.dbtype"
```

2023-08-07 10:01 UTC, Joon-Klaps approved these changes
Great work, thanks! 👍

2023-08-07 10:09 UTC, merged