add module for btyper3
nf-core/modules pull request #3817
Opened 2023-09-07 03:32 UTC by rpetit3

## PR checklist

Closes https://github.com/nf-core/modules/issues/3816 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-09-12 07:07 UTC, nvnieuwk reviewed
Some small comments :p

2023-09-12 07:07 UTC, nvnieuwk commented on modules/nf-core/btyper3/main.nf
> +    tuple val(meta), path("results/*_final_results.txt"), emit: tsv
Is the prefix defined from the fasta filename? And can you supply a custom one?

2023-09-12 07:07 UTC, nvnieuwk commented on tests/modules/nf-core/btyper3/main.nf
Can you also add a test with a gzipped fasta file?

2024-08-23 07:40 UTC, SPPearce commented on modules/nf-core/btyper3/meta.yml
> +      licence: "['GPL v3']"
```suggestion
      licence: ["GPL v3"]
```

2024-08-27 18:25 UTC, SPPearce commented on modules/nf-core/btyper3/main.nf
> +    conda "bioconda::btyper3=3.4.0"
```suggestion
    conda "${moduleDir}/environment.yml"
```

2024-12-10 08:12 UTC, famosab requested changes

2024-12-10 08:12 UTC, famosab commented on modules/nf-core/btyper3/environment.yml
> +  - defaults
```suggestion
```

2024-12-10 08:12 UTC, famosab commented on modules/nf-core/btyper3/main.nf
> +    def args = task.ext.args ?: ''
```suggestion
```

2024-12-10 08:12 UTC, famosab commented on modules/nf-core/btyper3/meta.yml
> +        e.g. `[ id:'test', single_end:false ]`
```suggestion
        e.g. `[ id:'test' ]`
```
Probably does not apply here?

2024-12-10 08:12 UTC, famosab commented on modules/nf-core/btyper3/meta.yml
> +        e.g. `[ id:'test', single_end:false ]`
```suggestion
        e.g. `[ id:'test' ]`
```

2024-12-10 08:12 UTC, famosab commented on modules/nf-core/btyper3/tests/main.nf.test
> +                }
Can you also assert whether the results folder is present? maybe even check the subfiles that are created in that folder.

2024-12-10 08:12 UTC, famosab commented on modules/nf-core/btyper3/tests/tags.yml
I think this file is not needed anymore

2024-12-10 08:12 UTC, famosab commented on modules/nf-core/btyper3/meta.yml
run `nf-core modules lint --fix` to bring this into the new format :)

2025-06-08 18:39 UTC, SPPearce commented
Closing due to inactivity. Feel free to reopen the PR if you (or anyone else) have some time to finish this.

2025-06-08 18:39 UTC, closed without merging