Glimpse phase nftest
nf-core/modules pull request #4045
Opened 2023-10-16 16:01 UTC by LouisLeNezet

## PR checklist

Add nf-test for glimpse_phase

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-10-18 08:41 UTC, sateeshperi requested changes
minor change

2023-10-18 08:41 UTC, sateeshperi commented on modules/nf-core/glimpse/phase/tests/main.nf.test
> +    script "modules/nf-core/glimpse/phase/main.nf"
```suggestion
    script "../main.nf"
```

2023-10-19 23:55 UTC, Emiller88 approved these changes
🤠

2023-10-19 23:55 UTC, Emiller88 commented on modules/nf-core/glimpse/phase/tests/main.nf.test
> +                .orElse(null)
Love it!

2023-10-20 09:07 UTC, merged