Add Haplotypecaller to Parabricks module
nf-core/modules pull request #4073
Opened 2023-10-17 11:11 UTC by Furentsu

New nf-core module: parabricks/haplotypecaller

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-10-17 15:07 UTC, mashehu commented
> This looks good but I don't think there's any good way of testing GPUs yet?

Now we do https://github.com/nf-core/modules/pull/4073/commits/1c8a5766c6df7cac819c8990b5a62223080ec6f5

2023-11-23 13:31 UTC, lescai requested changes
see suggestions

2023-11-23 14:03 UTC, Emiller88 requested changes
Looks good! I agree with @lescai's changes. I also think we need to remove the GPU CI.

2023-11-23 14:03 UTC, Emiller88 commented on .github/workflows/test.yml
> +
```suggestion
```
I think this is meant to run on a self-hosted gpu for testing(on your fork). Would this not just work without it?

2023-11-23 14:03 UTC, Emiller88 commented on modules/nf-core/parabricks/haplotypecaller/main.nf
> +    def copy_index_command = bam_index ? "cp -L $bam_index `readlink -f $bam`.bai" : ""
I think it has to be `.bai` if I remember correctly 🙃

2023-11-23 14:03 UTC, Emiller88 commented on modules/nf-core/parabricks/haplotypecaller/meta.yml
> +
```suggestion
maintainers:
  - "@Furentsu"
```

2023-12-12 15:26 UTC, closed without merging