Add call to action comment on pytest-workflow runs
nf-core/modules pull request #4151
Opened 2023-10-18 10:27 UTC by Emiller88

2023-10-18 10:30 UTC, maxulysse commented
I'm happy with that, but I think we'd need to add a link to website with docs on how we do things

2023-10-18 10:33 UTC, Emiller88 commented
https://github.com/nf-core/website/issues/2050 If someone could point to the work/PR on this issue then.

2023-10-19 08:59 UTC, maxulysse approved these changes

2023-10-19 09:05 UTC, mashehu requested changes
Not before we have docs on the website

2023-10-19 09:28 UTC, Emiller88 commented
Alright waiting on https://github.com/nf-core/website/issues/2050

2023-11-22 07:58 UTC, mashehu commented on .github/workflows/test.yml
> +              We would appreciate this test being rewritten in nf-test. If you aren't able to do that right now [raise an issue](https://github.com/nf-core/modules/issues/new?assignees=&labels=bug&pr
```suggestion
              We would appreciate this test being rewritten in nf-test. We have documented a step-by-step process to do so [here](https://nf-co.re/docs/contributing/modules#migrating-from-pytest-to-nf-test). If you aren't able to do that right now [raise an issue](https://github.com/nf-core/modules/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).
```

2023-11-22 07:58 UTC, mashehu approved these changes
Good to go for me, if we point to the conversion docs

2023-11-22 08:07 UTC, mirpedrol approved these changes

2023-11-22 08:12 UTC, nvnieuwk approved these changes

2023-11-22 10:01 UTC, merged