Pigzip
nf-core/modules pull request #4156
Opened 2023-10-18 10:56 UTC by lrauschning

Lint is complaining about no pytests, but that should be fine as the module has NFtests.
We decided against implementing a PIGZ/Compress module, for details see nf-core/multiplesequencealign#73
For singularity and biocontainers images, we are waiting on BioContainers/multi-package-containers#2792 to be merged.

## PR checklist

Closes #4106

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `nf-test <MODULE> --profile conda`

2023-10-19 09:12 UTC, mathysgrapotte requested changes
Requesting the commented changes before merging

2023-10-19 09:12 UTC, mathysgrapotte commented on modules/nf-core/pigz/uncompress/tests/main.nf.test
You need to add tags in main.nf.test, I suspect this is causing nf-test to fail. See [abricate module](https://github.com/nf-core/modules/blob/master/modules/nf-core/abricate/run/tests/main.nf.test) for example.

2023-10-19 09:12 UTC, mathysgrapotte commented on modules/nf-core/pigz/uncompress/main.nf
All TODOs need to be removed before merging to master, see line 7.

2023-10-19 14:58 UTC, mathysgrapotte approved these changes

2023-10-19 23:41 UTC, Emiller88 commented
Yeah I can't merge cowboy on docker tests...

2023-10-19 23:51 UTC, lrauschning commented
BioContainers/multi-package-containers#2792 was just merged this night, so a current version of pigz should soon be on singularity/biocontainers.
Added a slightly older version I just found now to test, will update to the new one when it's on the galaxy depot.

2023-10-20 09:03 UTC, Emiller88 commented
![image](https://github.com/nf-core/modules/assets/20095261/f7c51c28-cd1d-4130-8415-8b611a94598d)

2023-10-25 10:48 UTC, lrauschning commented
Updating to current master, all tests for pigzip are passing.

2023-10-25 11:17 UTC, lrauschning commented
The `prettier` issues are in some other modules, all tests run through. Can someone manually merge (I think automerge is blocked because of prettier reporting issues?

2023-11-08 11:52 UTC, merged