new module vcflib/vcfallelicprimitives
nf-core/modules pull request #4227
Opened 2023-10-25 07:41 UTC by nvnieuwk

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-10-25 08:04 UTC, chris-cheshire commented on modules/nf-core/vcflib/vcfallelicprimitives/main.nf
> +    tuple val(meta), path("*.vcf.gz")   , emit: vcf
Whitespace

2023-10-25 08:06 UTC, chris-cheshire commented
Looks good to me, there is some white space you could clean up around the emit statements but that's it

2023-10-25 08:10 UTC, nvnieuwk commented
Thanks @chris-cheshire !

2023-10-25 08:11 UTC, jonasscheid approved these changes
Only one nitpick. Feel free to merge afterwards

2023-10-25 08:11 UTC, jonasscheid commented on modules/nf-core/vcflib/vcfallelicprimitives/meta.yml
> +description: Realign reference and alternate alleles with WFA or SW, parsing out the primitive alleles into multiple VCF records. New records have IDs that reference the source record ID.  Genotypes
```suggestion
description: Realign reference and alternate alleles with WFA or SW, parsing out the primitive alleles into multiple VCF records. New records have IDs that reference the source record ID. Genotypes are handled. Deletion alleles will result in haploid (missing allele) genotypes.
```

2023-10-25 08:23 UTC, nvnieuwk commented on modules/nf-core/vcflib/vcfallelicprimitives/meta.yml
> +description: Realign reference and alternate alleles with WFA or SW, parsing out the primitive alleles into multiple VCF records. New records have IDs that reference the source record ID.  Genotypes
Thank you!

2023-12-19 07:21 UTC, SPPearce requested changes
Need to move the conda environment, but the rest looks good

2023-12-19 07:21 UTC, SPPearce commented on modules/nf-core/vcflib/vcfallelicprimitives/main.nf
> +    conda "bioconda::vcflib=1.0.9"
This needs to be separate environment file now.

2024-03-18 13:34 UTC, closed without merging