Add panacus histgrowth module
nf-core/modules pull request #4260
Opened 2023-10-31 14:47 UTC by heringerp

Adds a module for the panacus histgrowth command. This is needed to add panacus statistics to the pangenome pipeline.

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-11-02 08:30 UTC, subwaystation requested changes
This looks really good already! Please fix the EOL and the explanations. Then make it a real PR @heringerp

2023-11-02 08:30 UTC, subwaystation commented on modules/nf-core/panacus/histgrowth/meta.yml
> +      description: TSV file containing the statistics
Could you please mention here that either a TSV or an HTML will be the output?

2023-11-02 08:30 UTC, subwaystation commented on tests/modules/nf-core/panacus/histgrowth/main.nf
> +workflow test_panacus_histgrowth {
My wild guess here is that this is not in accordance with the new nf-test rules, but we will find out once you make this a real PR.

2023-11-02 08:30 UTC, subwaystation commented on tests/modules/nf-core/panacus/histgrowth/nextflow.config
> +}
Missing EOL.

2023-11-30 15:49 UTC, subwaystation commented
@mashehu The trick didn't work......

2023-12-01 08:10 UTC, subwaystation commented
@heringerp It seems the md5sums of Singularity and Docker differ. A little bit strange. Can you test locally?
If you get the desired result regardless if the md5sums are fitting, then revert the test back to just check if the expected files exist. Thanks!

2023-12-01 10:31 UTC, mashehu requested changes
still has some relics from pytests 🙂

2023-12-01 10:31 UTC, mashehu commented on tests/config/pytest_modules.yml
> +
```suggestion
```
This was just needed for pytest, your tests are with nf-tests and will be picked up based on their tags.

2023-12-01 10:31 UTC, mashehu commented on tests/modules/nf-core/panacus/visualize/test.yml
this file is not needed for nf-test

2023-12-01 10:31 UTC, mashehu commented on tests/modules/nf-core/panacus/histgrowth/test.yml
this file is not needed for nf-test

2023-12-01 13:43 UTC, subwaystation commented
Cool, looks good to me now :)

2023-12-01 13:43 UTC, subwaystation approved these changes

2023-12-01 13:47 UTC, merged