Add DESeq2 model to output
nf-core/modules pull request #4329
Opened 2023-11-14 08:00 UTC by WackerO

This PR adds an output file to DESeq2 that contains the model that was used

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-11-14 09:12 UTC, pinin4fjords requested changes
Looking good- but you need to resolve whatever git issue is causing you to hit other modules.

2023-11-14 09:34 UTC, WackerO commented
Alright, did that. But now the linting is failing again, can we ignore that? It's because those other two modules have incorrectly written environment.ymls

2023-11-14 14:12 UTC, pinin4fjords commented
Could you maybe do the limma one at the same time and save us a PR?

2023-11-15 09:22 UTC, pinin4fjords approved these changes
Looks good- thanks Oskar

2023-11-15 09:22 UTC, pinin4fjords commented on modules/nf-core/limma/differential/meta.yml
> +      pattern: "limma.model.tsv"
```suggestion
      pattern: "*.limma.model.tsv"
```

2023-11-15 09:22 UTC, pinin4fjords commented on modules/nf-core/limma/differential/meta.yml
> +      pattern: "limma.model.tsv"
Just for consistency with the other entries here

2023-11-15 11:30 UTC, merged