Mmseqs createdb and linclust container version upgrade + nf-tests
nf-core/modules pull request #4368
Opened 2023-11-21 13:11 UTC by vagkaratzas

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-11-21 13:28 UTC, JoseEspinosa approved these changes
LGTM! But why are some tests not running? Feel free to merge once they pass

2023-11-21 13:32 UTC, Joon-Klaps requested changes
Awesome 🚀! Small comments, looks like you forgot the `tags.yml` file. 

Thanks as well for fixing some of my typos in the docs.

2023-11-21 13:32 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/createdb/tests/main.nf.test
> +                outdir = "$outputDir"
Don't need it if you aren't checking for published files.

2023-11-21 15:57 UTC, Joon-Klaps approved these changes
Great work!

2023-11-21 16:01 UTC, merged

2023-11-22 13:38 UTC, sateeshperi commented on modules/nf-core/mmseqs/createdb/tests/main.nf.test
> +                { assert process.out.versions }
not including versions in snapshot ? @vagkaratzas @Joon-Klaps