4457 new module chewbaccaallelecall
nf-core/modules pull request #4479
Opened 2023-11-28 21:46 UTC by anwarMZ

## PR checklist

Closes #4457  

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-11-28 21:47 UTC, anwarMZ commented
This is a draft PR, requires a sister module to produce the schema in order to avoid adding schema to modules test dataset

2025-03-07 14:37 UTC, SPPearce commented
Hi @anwarMZ,
Are you still interested in getting this module merged in?
It will need converting to the more recent specifications that are being used in the modules repo, which may include:

- using nf-test instead of pytest
- conda definition in a environment.yml file separate from the main.nf
- adding a stub
- updating the meta.yml file to reflect the latest specification (better reflecting the channel output rather than a flat list)

If you need help we can provide that, but if you aren't going to work on it in the near future then we will close this PR next week (it can be reopened in the future if someone wants to work on it again).

2025-03-07 17:23 UTC, anwarMZ commented
Hi @SPPearce, thanks for the reminder. Yes, I will update this PR soon and ask for quick help where needed.

2025-03-07 20:21 UTC, anwarMZ commented
@SPPearce I have updated the module, please let me know if you have any concerns.

2025-03-07 20:53 UTC, SPPearce requested changes
Good job!
Three things:
The meta.yml doesn't need pattern on the metas, and the type of should be file not meta for the file outputs.
If the fasta files need to be inside a folder, then you could use stageAs to ensure that they are put into a folder for the tool.
Can you test some kind of content of the output files, not just the existence?

2025-03-07 20:53 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          pattern: "*_results_statistics.tsv"
```suggestion
```

2025-03-07 20:53 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          pattern: "*_results_contigsInfo.tsv"
```suggestion
```

2025-03-07 20:53 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          pattern: "*_results_alleles.tsv"
```suggestion
```

2025-03-07 20:53 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          pattern: "*_logging_info.txt"
```suggestion
```

2025-03-07 20:53 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          type: map
```suggestion
          type: file
```

2025-03-07 20:53 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          type: map
```suggestion
          type: file
```

2025-03-07 20:53 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          type: map
```suggestion
          type: file
```

2025-03-07 21:44 UTC, anwarMZ commented
@SPPearce updated accordingly. Thank you for the feedback

2025-03-09 21:00 UTC, SPPearce reviewed
Wow, that is a lot of assertions in that test! Which is good and fine, but I should probably have been more explicit, apologies. 
We generally just check the md5sum of any file that is stable, then more general test (e.g. contains or file existence) for files that aren't.
It is generally fine, but please do include the versions information snapshot.

2025-03-09 21:01 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +        pattern: "*/"
Oh, I guess they are the output of another subtool, so probably fine as a folder.

2025-03-20 22:39 UTC, anwarMZ commented on modules/nf-core/chewbbaca/allelecall/meta.yml
> +          e.g. `[ id:'test', single_end:false ]`
resolved with https://github.com/nf-core/modules/pull/4479/commits/cf958498684116015fd1a3ddf65dcebaf8950b44

2025-03-24 20:05 UTC, SPPearce commented on modules/nf-core/chewbbaca/allelecall/tests/main.nf.test
> +                    path(process.out.versions[0]).yaml
```suggestion
                    process.out.versions,
                    path(process.out.versions[0]).yaml
```
To make the linter happy. Need to regenerate the snapshot.

2025-03-25 08:40 UTC, SPPearce reviewed
Thanks. Almost there I think. 
Just noticed that some of your output channels are optional, but you are using mv to rename the files - this will fail and error if the file isn't generated I think. 
You can wrap it in an existence check or maybe use an argument for mv, not sure (and reviewing on my phone)

2025-03-26 12:42 UTC, anwarMZ commented
> Thanks. Almost there I think. Just noticed that some of your output channels are optional, but you are using mv to rename the files - this will fail and error if the file isn't generated I think. You can wrap it in an existence check or maybe use an argument for mv, not sure (and reviewing on my phone)

updated with [6ec7e03](https://github.com/nf-core/modules/pull/4479/commits/6ec7e031d2b194706e2378528cd5ab1b79f52f5b)

2025-03-26 13:13 UTC, SPPearce approved these changes
Ok, let's get it merged!

2025-03-26 21:48 UTC, merged