Add nf-test for bcl_demultiplex, remove old pytest
nf-core/modules pull request #4501
Opened 2023-11-29 15:56 UTC by karthikram-takara

## PR checklist

Closes #4495  

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2023-11-29 16:04 UTC, LeuThrAsp requested changes
snap file does not include files

2023-11-29 16:04 UTC, LeuThrAsp commented on subworkflows/nf-core/bcl_demultiplex/tests/main.nf.test.snap
> +            [
no test files

2023-11-29 17:04 UTC, karthikram-takara commented on subworkflows/nf-core/bcl_demultiplex/tests/main.nf.test.snap
> +            [
Thanks, fixed this in later commits.

2024-05-07 14:56 UTC, SPPearce commented
Closing as superceded by #4842

2024-05-07 14:56 UTC, closed without merging