[WIP] Move shinyngs modules across to nftest
nf-core/modules pull request #4681
Opened 2024-01-07 22:56 UTC by pinin4fjords

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2024-01-08 08:11 UTC, koenbossers requested changes
Looks good to me! Only a small note on test naming conventions.

2024-01-08 08:11 UTC, koenbossers commented on modules/nf-core/shinyngs/app/tests/main.nf.test
> +    test("multi - tsv") {
From [the migration guide to nf-test](https://nf-co.re/docs/contributing/modules#migrating-from-pytest-to-nf-test): provide a test name preferably indicating the test-data and file-format used. Example: test("homo_sapiens - [bam, bai, bed] - fasta - fai")

2024-01-08 08:11 UTC, koenbossers commented on modules/nf-core/shinyngs/app/tests/main.nf.test
> +    test("single - tsv") {
See previous remark on naming conventions

2024-06-13 20:42 UTC, SPPearce commented
Bumping to see if we can get this merged in

2024-06-14 09:41 UTC, pinin4fjords commented
Apologies, I think this is an orphan, I must have forgotten about it and did the work again elsewhere.

2024-06-14 09:41 UTC, closed without merging

2024-06-14 10:08 UTC, SPPearce commented
No worries, happy to clean up another PR ;)