New last/lastdb module to index sequences before alignment.
nf-core/modules pull request #476
Opened 2021-04-30 01:56 UTC by charles-plessy

The `lastdb` command creates a sequence index for the [LAST aligner](https://gitlab.com/mcfrith/last). Input can be in FASTA or FASTQ format, and compression is handled automagically.  DNA or protein sequences can be indexed.

The sequence index is a collection of files sharing the same basename. This module sets the basename to the sample identifier (`$meta.id`) and creates the index in a directory always called `lastdb`.  The module's output channel then conveys a copy of the metadata and the path to the `lastdb` directory.

Other modules will follow (see Issue #464).  The LAST aligner can align proteins to proteins, DNA to DNA and can translate DNA align to proteins.

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `<SOFTWARE>.version.txt` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-04-30 13:58 UTC, drpatelh requested changes
Looks awesome overall @charles-plessy 😍 Mainly minor changes that are possibly because you need to use the `dev` version of nf-core/tools to create the module file at the moment. You can do this by installing it with the command:

```console
pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev
nf-core modules create
```

2021-04-30 13:58 UTC, drpatelh commented on tests/config/pytest_software.yml
> +last_lastdb:
```suggestion
last/lastdb:
```

2021-04-30 13:58 UTC, drpatelh commented on tests/software/last/lastdb/test.yml
> +    - last_lastdb
```suggestion
    - last/lastdb
```

2021-04-30 13:58 UTC, drpatelh commented on tests/software/last/lastdb/test.yml
> +    - last_lastdb
```suggestion
    - last/lastdb
```

2021-04-30 13:58 UTC, drpatelh commented on software/last/lastdb/main.nf
> +
```suggestion
    def software = getSoftwareName(task.process)
    def prefix   = options.suffix ? "${meta.id}${options.suffix}" : "${meta.id}"
```

2021-04-30 13:58 UTC, drpatelh commented on software/last/lastdb/main.nf
> +        lastdb/${meta.id} \\
```suggestion
        lastdb/${prefix} \\
```

2021-04-30 13:58 UTC, drpatelh commented on software/last/lastdb/main.nf
> +        ${options.args} \\
```suggestion
        $options.args \\
```

2021-04-30 13:58 UTC, drpatelh commented on software/last/lastdb/main.nf
> +        -P ${task.cpus} \\
```suggestion
        -P $task.cpus \\
```

2021-04-30 13:58 UTC, drpatelh commented on software/last/lastdb/main.nf
> +        ${fastx}
```suggestion
        $fastx
```

2021-04-30 13:58 UTC, drpatelh commented on software/last/lastdb/main.nf
> +        saveAs: { filename -> saveFiles(filename:filename, options:params.options, publish_dir:getSoftwareName(task.process), publish_id:meta.id) }
```suggestion
        saveAs: { filename -> saveFiles(filename:filename, options:params.options, publish_dir:getSoftwareName(task.process), meta:meta, publish_by_meta:['id']) }
```

2021-04-30 13:58 UTC, drpatelh commented on software/last/lastdb/functions.nf
> + * -----------------------------------------------------
This file needs to be replace with [this one](https://raw.githubusercontent.com/nf-core/modules/master/software/lib/functions.nf). It was updated recently.

2021-05-02 02:08 UTC, charles-plessy reviewed
Thanks for the changes: I accepted all and updated `functions.nf`

2021-05-02 08:55 UTC, drpatelh commented on tests/software/last/lastdb/test.yml
> +    - last
```suggestion
    - last
    - last/lastdb
```

2021-05-02 08:56 UTC, drpatelh commented on tests/software/last/lastdb/test.yml
> +    - last
Sorry, can't push commits to your fork @charles-plessy but would you mind making this change too? I think that is why the linting is failing.

2021-05-02 10:36 UTC, drpatelh approved these changes

2021-05-02 10:36 UTC, drpatelh commented
💥 Thanks @charles-plessy !

2021-05-02 10:36 UTC, merged