Add new submodule MMseqs/taxonomy
nf-core/modules pull request #4980
Opened 2024-02-23 18:20 UTC by Darcy220606

## PR checklist

Closes #4970

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [x] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-02-24 11:05 UTC, jasmezz requested changes
Looks great overall :tada: Just 1 major question for the `main.nf.test` plus a few minor tweaks.

2024-02-24 11:05 UTC, jasmezz commented on modules/nf-core/mmseqs/taxonomy/tests/main.nf.test.snap
> +        "timestamp": "2024-02-23T15:31:53.321266978"
Interesting that there is no `versions.yml` mentioned although you check for it in main.nf.test. I don't understand that, but apparently the tests pass :shrug:

2024-02-26 09:27 UTC, Darcy220606 commented on modules/nf-core/mmseqs/taxonomy/meta.yml
> +      description: The created MMseqs2 database with taxonomic classifications
its a dtabase in this case, which stilln eeds to be converted to a table with another module

2024-02-26 09:30 UTC, Darcy220606 commented on modules/nf-core/mmseqs/taxonomy/tests/main.nf.test
> +                { assert snapshot(process.out.db_taxonomy.collect { file(it[1]).getName() }).match() },
Yes i checked that, but there was always 'Empty file with md5sum' error coming up when i linted the module. A way around this is to to check for the ouput names instead.

2024-02-26 12:56 UTC, Darcy220606 commented on modules/nf-core/mmseqs/taxonomy/tests/main.nf.test
> +                { assert snapshot(process.out.db_taxonomy.collect { file(it[1]).getName() }).match() },
ok changed it now to output the file names instead

2024-02-26 13:58 UTC, Darcy220606 commented on modules/nf-core/mmseqs/taxonomy/tests/main.nf.test
> +                { assert process.out.versions }
That doesnt work unfortunately. Only when i compare teh names does it work for some reason.

2024-02-26 14:13 UTC, jasmezz approved these changes
Looks good! :partying_face: After tests succeeded, you can just add my suggestion with [skip ci]. (Don't trigger tests again because the blank line does not change the code)

2024-02-26 14:35 UTC, Darcy220606 commented on modules/nf-core/mmseqs/taxonomy/tests/main.nf.test
> +    test("mmseqs/taxonomy - bacteroides_fragilis - genome_nt") {
Big thanks @jasmezz for the reviews !!!

2024-02-27 09:46 UTC, merged