Glimpse2 splitreference: Change python test to nf-test
nf-core/modules pull request #5076
Opened 2024-03-07 12:27 UTC by LouisLeNezet

## PR checklist

Glimpse2 splitreference: Change python test to nf-test

- [ ] This comment contains a description of changes (with reason).
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`

2024-03-07 12:42 UTC, maxulysse commented on modules/nf-core/glimpse2/splitreference/tests/main.nf.test
> +                    file("https://github.com/nf-core/test-datasets/raw/modules/data/delete_me/glimpse/1000GP.chr21.noNA12878.s.bcf.csi", checkIfExists: true),
```suggestion
                    file(params.modules_testdata_base_path + "delete_me/glimpse/1000GP.chr21.noNA12878.s.bcf", checkIfExists: true),
                    file("params.modules_testdata_base_path + "delete_me/glimpse/1000GP.chr21.noNA12878.s.bcf.csi", checkIfExists: true),
```

2024-03-07 12:43 UTC, maxulysse commented on modules/nf-core/glimpse2/splitreference/tests/main.nf.test
> +                input[1]= [[ id:'map'],file("https://github.com/nf-core/test-datasets/raw/modules/data/delete_me/glimpse/chr21.b38.gmap.gz", checkIfExists: true)]
```suggestion
                input[1]= [[ id:'map'],file(params.modules_testdata_base_path + "delete_me/glimpse/chr21.b38.gmap.gz", checkIfExists: true)]
```

2024-03-07 13:27 UTC, LouisLeNezet commented
Thanks @maxulysse.
I'll update the other modules the same way !

2024-03-07 14:18 UTC, maxulysse commented on modules/nf-core/glimpse2/splitreference/tests/nextflow.config
>      publishDir = { "${params.outdir}/${task.process.tokenize(':')[-1].tokenize('_')[0].toLowerCase()}" }
```suggestion
```

2024-03-07 14:28 UTC, maxulysse commented on modules/nf-core/glimpse2/splitreference/tests/main.nf.test
> +        config "modules/nf-core/glimpse2/splitreference/tests/nextflow.config"
```suggestion
        config "./nextflow.config"
```

2024-03-07 14:28 UTC, maxulysse commented on modules/nf-core/glimpse2/splitreference/tests/main.nf.test
> +        config "modules/nf-core/glimpse2/splitreference/tests/nextflow.config"
```suggestion
        config "./nextflow.config"
```

2024-03-13 13:18 UTC, matthdsm approved these changes

2024-03-13 13:19 UTC, mashehu requested changes

2024-03-13 13:19 UTC, mashehu commented on modules/nf-core/glimpse2/splitreference/meta.yml
> +        e.g. [ map:'GRCh38' ]
```suggestion
        e.g. `[ map:'GRCh38' ]`
```

2024-03-13 13:19 UTC, mashehu commented on modules/nf-core/glimpse2/splitreference/tests/main.nf.test
> +            )
version snapshot is missing

2024-03-13 13:19 UTC, mashehu commented on modules/nf-core/glimpse2/splitreference/tests/main.nf.test
> +                { assert file(process.out.bin_ref[0][1]).name == "ref1000GP_chr21_16600000_16800000.bin" }
version snapshot is missing

2024-03-13 13:58 UTC, LouisLeNezet commented
@mashehu: Is it good now ?

2024-03-13 14:12 UTC, mashehu approved these changes

2024-03-13 14:18 UTC, merged