Fix mmseqs/createtsv and add nf-test
nf-core/modules pull request #5096
Opened 2024-03-11 13:15 UTC by Darcy220606

##PR checklist

Closes #5014  

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-11 13:31 UTC, Joon-Klaps approved these changes
Well spotted! Great work, small suggestions. You can merge if tests pass 🚀

2024-03-11 13:31 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/createtsv/main.nf
> +    def args2 = task.ext.args ?: "*.dbtype" // database generated by mmyseqs/cluster
```suggestion
    def args2 = task.ext.args ?: "*.dbtype" // database generated by mmyseqs cluster | search | taxonomy | ...
```

2024-03-11 13:34 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/createtsv/tests/main.nf.test
> +                        file(params.test_data['bacteroides_fragilis']['genome']['genome_fna_gz'], checkIfExists: true),
Just noticed test failing due to memory issues. Consider using instead sars-cov-2 contigs for clustering.

2024-03-11 16:45 UTC, Joon-Klaps requested changes

2024-03-11 16:45 UTC, Joon-Klaps commented on modules/nf-core/mmseqs/createtsv/tests/main.nf.test
> +            script "modules/nf-core/mmseqs/createdb/main.nf"
Sorry missed something, please make all the script locations relative.

2024-03-12 11:29 UTC, Darcy220606 commented
Hi @Joon-Klaps, so the cluster nf-tests would always run out of memory on github no matter what assertions i tried, so i used the tarr(ed) mmseqs testdataset files as you have done previously for this module pytests.  Do please have a look again at the PR and let me know if there is soemthing else to change. Thanks a bunch :)

2024-03-12 12:12 UTC, Joon-Klaps approved these changes
Very nice! LGTM! 🚀

2024-03-12 15:05 UTC, merged