update pyrodigal arguments to v 3.3.0
nf-core/modules pull request #5134
Opened 2024-03-15 15:06 UTC by Darcy220606

## PR checklist

This PR updates pyrodigal arguments to allow it to output different formats not only `gff`. This is now applicable in version 3.3.0

Closes #5128 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-16 16:54 UTC, louperelo approved these changes
Looks good to me, but a check is not passing - Conda ....
I just think `gene_annotations` is a bit long for an emit tag, but I don't really have a good alternative, maybe `annot` or `annotations`?

2024-03-17 20:51 UTC, Darcy220606 commented
> Looks good to me, but a check is not passing - Conda .... I just think `gene_annotations` is a bit long for an emit tag, but I don't really have a good alternative, maybe `annot` or `annotations`?

Thanks @louperelo ! I changed it to annotations instead. I dont know whats the issue with conda failing with CI tests on github, because locally its running on all three docker, conda and singularity without failing. Any suggestions what to do here?

2024-03-18 10:43 UTC, jasmezz requested changes
Pigz is apparently missing in the CI test environment, so I added is via the previous commit. Here some more suggestions to clarify the meta.yml. But otherwise ready to go :rocket:

2024-03-18 10:43 UTC, jasmezz commented on modules/nf-core/pyrodigal/meta.yml
> +      description: Output format ("gbk"/"gff")
```suggestion
      description: Output format
      pattern: "{gbk,gff}"
```

2024-03-18 10:43 UTC, jasmezz commented on modules/nf-core/pyrodigal/meta.yml
> +      description: gene annotations in output format given as input
```suggestion
      description: gene annotations. The file format is specified via input channel "output_format".
```
Just updated the wording, I was confused by "gene annotations in output format given as input"

2024-03-18 10:43 UTC, jasmezz commented on modules/nf-core/pyrodigal/meta.yml
> +      pattern: "*.{output_format}.gz"
```suggestion
      pattern: "*.{gbk,gff}.gz"
```

2024-03-18 13:24 UTC, jasmezz approved these changes

2024-03-18 15:04 UTC, merged