Added meta map to module and tests
nf-core/modules pull request #5191
Opened 2024-03-18 14:09 UTC by itrujnara

## PR checklist

Closes #5152 

- [x] Added meta map to input and output to facilitate batch processing.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If necessary, include test data in your PR.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`

2024-03-18 14:25 UTC, JoseEspinosa approved these changes
Just a small format suggestion, otherwise awesome! 🚀 
Feel free to merge once addressed

2024-03-18 14:29 UTC, JoseEspinosa reviewed
Seems I forgot to push the button 😛

2024-03-18 14:29 UTC, JoseEspinosa commented on modules/nf-core/fastme/main.nf
> +    tuple val(meta), path("*.bootstrap")  , emit: bootstrap , optional: true
```suggestion
    tuple val(meta), path("*.nwk")       , emit: nwk
    tuple val(meta), path("*_stat.txt")  , emit: stats
    tuple val(meta), path("*.matrix.phy"), emit: matrix    , optional: true
    tuple val(meta), path("*.bootstrap") , emit: bootstrap , optional: true
```

2024-03-18 14:35 UTC, Joon-Klaps requested changes
Very nice work! 
A couple of suggestions that should have been included in the initial PR:
- Add  stub test
- With the boostrapping test
      - Try to do the following for the outputs, I know bootstrapping is non-deterministic but the nwk file and stats file will contain the sample names in there so : [check if a string is contained](https://nf-co.re/docs/contributing/tutorials/nf-test_assertions#file-contains-check) >  [check if the file exists](https://nf-co.re/docs/contributing/tutorials/nf-test_assertions#file-exists-check) > [check if file name matches](https://nf-co.re/docs/contributing/tutorials/nf-test_assertions#snapshot-selective-file-names--content) 
      - Include stats & versions in assertAll clause

2024-03-18 16:00 UTC, itrujnara commented
@Joon-Klaps is this what you meant? I have not been able to adapt the "file exists" example, nor do I know how to approach the one with sample name (recalculate prefix in test?). I have not yet added the stub test.

2024-03-18 16:18 UTC, itrujnara commented
Stub test is now added

2024-03-19 07:25 UTC, Joon-Klaps requested changes

2024-03-19 07:25 UTC, Joon-Klaps commented on modules/nf-core/fastme/tests/main.nf.test
> +                { assert process.out.versions }
```suggestion
                { assert path(process.out.nwk[0][1]).text.contains("1atx:") },
                { assert path(process.out.matrix[0][1]).text.contains("1apf") },
                { assert path(process.out.bootstrap[0][1]).text.contains("1atx:") },
                { assert path(process.out.stats[0][1]).readLines()[0..12]).match("stats_boot") },
                { assert snapshot(process.out.versions).match("versions") }
```

I meant something like this. If you look at the [output.zip](https://github.com/nf-core/modules/files/14646877/fastme_out.zip), you can see that some strings are contained across runs and we can check for it 😊. Also don't forget to include a snapshot for the versions. The current test clause, doesn't include any snapshots and it won't be written to the `main.nf.test.snap` file. 

Double check the test for errors, update snapshot and then 🚀

2024-03-19 09:12 UTC, itrujnara commented
There was a minor issue in one test (`snapshot()` missing), but I fixed it and now it's passing locally. Can you have another look @Joon-Klaps?

2024-03-19 09:20 UTC, Joon-Klaps approved these changes
Great work 🚀! Sorry for nitpicking.

2024-03-19 09:39 UTC, merged