added new module lofraq/viterbi; solves new module: lofreq/viterbi #5158
nf-core/modules pull request #5197
Opened 2024-03-18 14:47 UTC by MarieLataretu

## PR checklist

Closes #5158 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-18 15:09 UTC, MarieLataretu commented
Why is it running so many lofreq-unrelated tests? 😱

2024-03-18 15:25 UTC, FloWuenne commented
> Why is it running so many lofreq-unrelated tests? 😱

The reason why it runs unrelated tests is that it compares your PR changes to master and so any others changes done while you made your feature branch will be run as tests as well. Usually, clicking Update branch at the bottom of the PR should bring it to only running your tests!

2024-03-18 16:31 UTC, MarieLataretu commented
okay, the problem with the failing conda test:

The `samtools` version differs in the conda (1.19.2) environment and the container (1.17). This leads to a different header line in the BAM file, even if the build version is the same.

2024-03-18 17:39 UTC, FloWuenne commented
@MarieLataretu Great catch! I was also looking at the difference in conda vs container environment. This is really strange, as the biocontainers build from bioconda should be exactly the same no? Would this be fixed by using a different build? 
Otherwise I see two options:
1) Disable conda
2) Generate a custom container image with the samtools version corresponding to the conda environment

2024-03-19 09:06 UTC, MarieLataretu commented
I checked to which build the conda env was resolved, and adapted the singularity container accordingly (so far only locally - I don't know how conda decides on the build 🤔 )

My best guess is that in conda, samtools always resolves to the latest version when you build the environment. The same is true for the container, only that it's frozen to the latest samtools version when the container is built.

I checked out a third option, but I don't know if follows the nf-core standards: I added the samtools version from the container as a dependency to the yml:
```
dependencies:
  - bioconda::lofreq=2.1.5
  - bioconda::samtools=1.17
 ```

Locally the tests pass!

2024-03-19 09:23 UTC, FloWuenne commented
> I checked to which build the conda env was resolved, and adapted the singularity container accordingly (so far only locally - I don't know how conda decides on the build 🤔 )
> 
> My best guess is that in conda, samtools always resolves to the latest version when you build the environment. The same is true for the container, only that it's frozen to the latest samtools version when the container is built.
> 
> I checked out a third option, but I don't know if follows the nf-core standards: I added the samtools version from the container as a dependency to the yml:
> 
> ```
> dependencies:
>   - bioconda::lofreq=2.1.5
>   - bioconda::samtools=1.17
> ```
> 
> Locally the tests pass!

I just tested your patch with specifying the samtools version in the `environment.yml` file and nf-test still produces different md5sums with conda than the ones produced by docker and singularity, which suggests to me also potential other differences than just the samtool version?

2024-03-19 09:33 UTC, FloWuenne requested changes
I spend some time in Gitpod trying to modify the conda dependencies so that they would output the same md5sum tests as docker and singularity, but was also unable to do so. For the PR to pass, this is the main thing to resolve...

2024-03-19 09:33 UTC, FloWuenne commented on modules/nf-core/lofreq/viterbi/environment.yml
> +# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
```suggestion
```

2024-03-19 09:33 UTC, FloWuenne commented on modules/nf-core/lofreq/viterbi/environment.yml
> +# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
I would remove these comments from the environment.yml for a clean yml file.

2024-03-19 10:13 UTC, MarieLataretu commented
(I'm struggling with git 😅 )

2024-03-19 10:38 UTC, FloWuenne approved these changes
LGTM ⭐️

2024-03-19 16:03 UTC, merged