Sigprofilerextractor
nf-core/modules pull request #5235
Opened 2024-03-19 11:48 UTC by pawelqs

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-19 12:41 UTC, itrujnara requested changes
Thanks for the contribution. The process itself is quite good, although you can consider moving the Python script into the container. The container must be hosted remotely, as it is used by the AWS worker for Github CI.
It seems you forgot about the documentation (meta.yml), this part is very important as it is the main source of information for future users. Finally, please remove template comments and TODOs once you no longer need them.

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    container "sigprofilerextractor"
The container must be hosted on Quay (quay.io) to work here, see some other modules (really, any) to see the correct way to link the containers

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    val(genome)
Is the genome the same for every sample in a pipeline run? If not, consider merging into the tuple. Feel free to keep it as-is if the genome is constant.

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    // TODO nf-core: List required Conda package(s). Software MUST be pinned to channel (i.e. "bioconda"), version (i.e. "1.10").
Remove all todos once addressed

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    tuple val(meta), path("results"), emit: results
If there are not too many output files, consider specific output channels for them (e.g. `tuple val(meta), path("*.bam"), emit: bam`)

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    #!/usr/bin/env python
It is unusual to include a Python script this way, although it is not necessarily wrong. You can consider packaging the script in the container and calling it with command line parameters. Feel free to argue here.

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    def outdir = "results"
Align equal signs

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    def outdir = "results"
Align equal signs

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/main.nf
> +    // Complex example: https://github.com/nf-core/modules/blob/818474a292b4860ae8ff88e149fbcda68814114d/modules/nf-core/bedtools/split/main.nf#L38-L54
Remove template comments

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/meta.yml
> +description: write your description here
Add documentation here, I see this file is unchanged from template

2024-03-19 12:41 UTC, itrujnara commented on modules/nf-core/sigprofiler/extractor/tests/main.nf.test
> +    // test("sarscov2 - bam - stub") {
Create a stub test for your process and remove the template comments

2024-03-19 13:21 UTC, pawelqs commented
Hi @itrujnara ! I am sorry for not notifying you, but the PR was not yet ready, I just hoped that Github Actions will deploy the container when I open it, as I was advised by colleagues. I will fix it as soon as possible and ask you to review it again when its ready

2024-03-28 07:51 UTC, pawelqs commented
Unfortunatelly I may not be able to complete this module in the nearest future. I will make a summary below in case that someone would like to take it over.

- SigProfilerExtractor does not take a reference genome as an input file, but takes a genome name and expects it to be installed by SigProfilerMatrixGenerator somewhere in the library directories, where it cannot be installed in Docker
- this genome installation is only required for the VCF input, not for matrix input. It should be possible then to implement sigprofiler/matrixgenerator module which would create the matrix files, which would be passed to sigprofiler/extractor module
- genome issue should not be relevant for sigprofiler/matrixgenerator module - this tool can be run in shell and this script can install genome to the working directory
```
#!/usr/bin/bash
mkdir -p tsb
SigProfilerMatrixGenerator install -v . ${genome}
```
- hopefully, SigProfilermatrixGenerator can use this genome to build the matrix file. SigProfilerExtractor cannot (or at least I was not able to make it running)
- Yes, everytime the process is run it will install the genome *de novo*. There is no way to install it once and pass the files

I may come back to this sooner or later, but feel free to contact me if you want to take it over earlier.

2025-03-11 09:09 UTC, famosab commented
I will close the issue for now. If you get back to it feel free to reopen. If someone else picks this up they will still be able to find the PR :)

2025-03-11 09:09 UTC, closed without merging