Add subworkflow mapAD
nf-core/modules pull request #5239
Opened 2024-03-19 12:12 UTC by jch-13

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-19 12:14 UTC, matthdsm commented
Can you fix your git history 😅 Nobody's going to want to review 1K+ files

2024-03-19 12:33 UTC, TCLamnidis requested changes
tests should be migrated to nf-tests instead of pytest.
Value channels should be removed and provided via `ext.args` to module. 
Remove unused channels.

I would suggest updating the mapAD_Map module to not have value channels in the input block, to simplify calling the module.

2024-03-19 12:33 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_align_mapad/main.nf
> +
These channels are not used anywhere, right? If so, they should be deleted.

2024-03-19 12:33 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_align_mapad/main.nf
> +    val_indel_rate
Only file channels should be taken in. Values can be supplied to modules using `ext.args` instead.

2024-03-19 12:33 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_align_mapad/main.nf
> +    MAPAD_MAP ( ch_preppedinput_for_mapad.reads, ch_preppedinput_for_mapad.index, val_mismatch_parameter, val_double_stranded_library, val_five_prime_overhang, val_three_prime_overhang, val_deam_rate
Updating the module to use `ext.args` instead of value channels will simplify this call also.

2024-03-19 12:33 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_align_mapad/main.nf
> +    bam_orig = MAPAD_MAP.out.bam                    // channel: [ val(meta), path(bam) ]
maybe give the channel a more informative name like `bam_unsorted` ? Also requires updating in meta.yml

2024-03-19 12:47 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_align_mapad/main.nf
> +    val_indel_rate
apparently newer module guidelines allow values for required options, so nevermind that!

2024-03-20 11:45 UTC, TCLamnidis approved these changes
one minor comment, otherwise LGTM!

2024-03-20 11:45 UTC, TCLamnidis commented on subworkflows/nf-core/fastq_align_mapad/main.nf
> +    versions = ch_versions                          // channel: [ path(versions.yml) ]
Harshil align

2024-03-20 12:09 UTC, merged