Author: @MartaSantanaSilva
nf-core/modules pull request #5274
Opened 2024-03-19 15:37 UTC by MartaSantanaSilva

Initial pull for module grabix/check
Addition of one test (total: 1)

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-19 15:50 UTC, nvnieuwk requested changes

2024-03-19 15:50 UTC, nvnieuwk commented on modules/nf-core/grabix/check/main.nf
> +    path "versions.yml"    , emit: versions
```suggestion
    env COMPRESS_BGZIP  , emit: compress_bgzip
    path "versions.yml" , emit: versions
```
Aligning this makes it easier to be read :)

2024-03-19 15:50 UTC, nvnieuwk commented on modules/nf-core/grabix/check/main.nf
> +    path(input)
```suggestion
    tuple val(meta), path(input)
```

nf-core pipelines usually use meta fields alongside their files to keep track of which file it is

2024-03-19 15:50 UTC, nvnieuwk commented on modules/nf-core/grabix/check/main.nf
> +    env COMPRESS_BGZIP  , emit: compress_bgzip
```suggestion
    tuple val(meta), env(COMPRESS_BGZIP)  , emit: compress_bgzip
```
So you output with the same meta as the input to be able to see for what kind of data you just ran the process

2024-03-19 15:50 UTC, nvnieuwk commented on modules/nf-core/grabix/check/main.nf
> +}
Can you add a stub to this module? You can have a look at almost all other modules to have an example for this

2024-03-19 15:50 UTC, nvnieuwk commented on modules/nf-core/grabix/check/meta.yml
> +      description: file to check compression
```suggestion
      pattern: "*.gz"
      description: file to check compression 
```

2024-03-19 15:50 UTC, nvnieuwk commented on modules/nf-core/grabix/check/tests/main.nf.test.snap
Your output channel isn't in the snapshot :grin:

2024-05-21 15:52 UTC, maxulysse commented on modules/nf-core/grabix/check/environment.yml
> +  - "bioconda::grabix=0.1.8"
```suggestion
  - bioconda::grabix=0.1.8
```

2024-05-21 15:52 UTC, maxulysse commented on modules/nf-core/grabix/check/environment.yml
> +name: "grabix_check"
```suggestion
name: grabix_check
```

2024-05-21 15:53 UTC, maxulysse commented on modules/nf-core/grabix/check/main.nf
> +    path "versions.yml"       , emit: versions
```suggestion
    tuple val(meta), stdout, emit: compress_bgzip
    path "versions.yml"    , emit: versions
```

2024-05-21 15:54 UTC, maxulysse commented on modules/nf-core/grabix/check/meta.yml
> +      description: environemental variable with value "yes" or "no"
yes/no? why not true/false?

2024-05-21 16:00 UTC, maxulysse commented on modules/nf-core/grabix/check/meta.yml
> +      description: environemental variable with value "yes" or "no"
```suggestion
      description: environmental variable with value "yes" or "no"
```

2024-05-21 16:03 UTC, maxulysse approved these changes

2024-05-21 17:06 UTC, nvnieuwk approved these changes

2024-05-21 17:38 UTC, merged