Decoupler module
nf-core/modules pull request #5317
Opened 2024-03-20 12:06 UTC by Nic-Nic

## PR checklist

Closes #5098 

Adds nf-core module for running decoupler-py, a python package suite for omic data enrichment analysis

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR. -> [Here](https://github.com/nf-core/test-datasets/pull/1137)
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-20 12:56 UTC, kbestak requested changes

2024-03-20 13:01 UTC, vicpaton commented on tests/config/pytest_modules.yml
it was triggering an error in the linting

2024-03-20 13:03 UTC, vicpaton commented on .gitignore
yes, we can discard them. We were running the process for debugging and we did not want the output files to be pushed to the repo

2024-03-20 13:10 UTC, vicpaton commented on modules/nf-core/decoupler/tests/nextflow.config
you mean the enabled=true? i think we can remove this

2024-03-20 13:15 UTC, kbestak commented on modules/nf-core/decoupler/tests/nextflow.config
The whole docker profile block

2024-03-20 14:03 UTC, vicpaton commented on modules/nf-core/decoupler/tests/nextflow.config
empirically, yes ahahah. I don't know why though

2024-03-20 14:36 UTC, vicpaton commented on modules/nf-core/decoupler/main.nf
> +    def methods = task.ext.methods ?: 'None'
adressed

2024-03-21 13:02 UTC, Nic-Nic commented on modules/nf-core/decoupler/tests/nextflow.config
Fixed in a8eace7

2024-03-21 16:20 UTC, kbestak approved these changes
LGTM!
Great work

2024-03-21 16:49 UTC, merged