Added MetaPlAn subworkflow
nf-core/modules pull request #5356
Opened 2024-03-20 21:19 UTC by LaurenGonsalves

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-20 22:55 UTC, CarsonJM requested changes
Nice! Great work! Just a few changes

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/main.nf
> +    METAPHLAN3_MERGEMETAPHLANTABLES ( METAPHLAN_METAPHLAN.out.profile.map{ [ [id:'all_samples'], it[1] ] }.groupTuple( sort: 'deep') )
```suggestion
    METAPHLAN_MERGEMETAPHLANTABLES ( METAPHLAN_METAPHLAN.out.profile.map{ [ [id:'all_samples'], it[1] ] }.groupTuple( sort: 'deep') )
```

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/main.nf
> +include { METAPHLAN3_MERGEMETAPHLANTABLES     } from '../../../modules/nf-core/metaphlan3/mergemetaphlantables/main'
```suggestion
include { METAPHLAN_MERGEMETAPHLANTABLES     } from '../../../modules/nf-core/metaphlan/mergemetaphlantables/main'
```

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/main.nf
> +    merged_taxa      = METAPHLAN3_MERGEMETAPHLANTABLES.out.txt
```suggestion
    merged_taxa      = METAPHLAN_MERGEMETAPHLANTABLES.out.txt
```

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/main.nf
> +    ch_versions = ch_versions.mix(METAPHLAN3_MERGEMETAPHLANTABLES.out.versions.first())
```suggestion
    ch_versions = ch_versions.mix(METAPHLAN_MERGEMETAPHLANTABLES.out.versions.first())
```

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/meta.yml
> +input:
```suggestion

input:
```
Personal preference, I'll leave it to you

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/tests/main.nf.test
> +// nf-core subworkflows test fastq_taxonomic_profile_metaphlan
```suggestion
```

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/tests/main.nf.test
> +                // TODO nf-core: define inputs of the workflow here.
```suggestion
```

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/tests/nextflow.config
> +
```suggestion
```

2024-03-20 22:55 UTC, CarsonJM commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/tests/nextflow.config
> +
```suggestion
```

2024-03-21 12:55 UTC, maxulysse commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/tests/main.nf.test
> +                //TODO nf-core: Add all required assertions to verify the test output.
```suggestion
```

2024-03-21 12:55 UTC, maxulysse commented on subworkflows/nf-core/fastq_taxonomic_profile_metaphlan/tests/nextflow.config
> +
```suggestion
```

2024-03-21 12:56 UTC, maxulysse approved these changes
Minor suggestions

2024-03-21 12:57 UTC, maxulysse approved these changes

2024-03-21 13:12 UTC, maxulysse commented
I can see that `all_samples.txt` doesn't have a common md5 between conda and docker, can you check the content?
I'm assuming that some specific lines would be specific to conda, so either a path to the lib, in which case, I'd suggest snapshotting some of this file's lines, or maybe a different version of a dependency, in which case, I'd add this as a dependency in the environment.yml, similarly to what we've done already with samtools

2024-03-25 22:51 UTC, CarsonJM approved these changes

2024-03-25 23:05 UTC, merged