port `manta-germline` to nf-test
nf-core/modules pull request #5362
Opened 2024-03-21 12:47 UTC by famosab

## PR checklist

Closes #5360 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-03-21 13:51 UTC, maxulysse approved these changes

2024-03-21 14:28 UTC, nvnieuwk requested changes

2024-03-21 14:28 UTC, nvnieuwk commented on modules/nf-core/manta/germline/tests/main.nf.test.snap
Can you regenerate the snapshot? It doesn't match what you have in your test file

2024-03-21 14:32 UTC, famosab commented on modules/nf-core/manta/germline/tests/main.nf.test.snap
I am running nf-core modules test locally and its taking ages ... hopefully I can add it soon.

2024-03-21 14:33 UTC, nvnieuwk commented on modules/nf-core/manta/germline/tests/main.nf.test.snap
Thank you for your effort, `manta` isn't the fastest tool indeed :grin:

2024-03-21 14:38 UTC, famosab commented on modules/nf-core/manta/germline/tests/main.nf.test.snap
ok locally I run into errors with 

Test Process GATK4_SVCLUSTER

2024-03-22 12:49 UTC, nvnieuwk approved these changes

2024-03-22 13:33 UTC, merged