PR for lofreq/indelqual module
nf-core/modules pull request #539
Opened 2021-06-19 17:03 UTC by kaurravneet4123

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `<SOFTWARE>.version.txt` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-06-19 17:32 UTC, kaurravneet4123 commented
Hi @drpatelh, I hope all is well.  I have made a PR for this new module: LOFREQ/INDELQUAL. It is passing all the tests, except a linting test. The error I am getting is that 'new version of functions.nf is available'. After forking and cloning the modules repo, I typed the following command in the modules dir: 'pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev' to download the latest module template. I am just wondering if this is the correct way to get the latest module template. Kindly if you can guide me. Many thanks, Rav

2021-07-01 09:59 UTC, drpatelh commented
Hi @kaurravneet4123 . The linting is failing because you need to update the `functions.nf` to the latest available on [`dev`](https://github.com/nf-core/tools/blob/dev/nf_core/module-template/software/functions.nf)

2021-07-01 10:05 UTC, kaurravneet4123 commented
Thanks for getting back to me @hpatel.
I will update it and push the changes.
Kind regards,
Rav


signature   Ravneet 

    On Thursday, July 1, 2021, 10:59:22 AM GMT+1, Harshil Patel ***@***.***> wrote:  
 
 


Hi @kaurravneet4123 . The linting is failing because you need to update the functions.nf to the latest available on dev

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-01 10:05 UTC, drpatelh requested changes
Looks great @kaurravneet4123 . Some minorish updates required.

2021-07-01 10:05 UTC, drpatelh commented on software/lofreq/indelqual/main.nf
> +    path "*.version.txt"                    , emit: version
```suggestion
    tuple val(meta), path("*.bam"), emit: bam
    path "*.version.txt"          , emit: version
```

2021-07-01 10:05 UTC, drpatelh commented on software/lofreq/indelqual/main.nf
> +        --dindel \\
Is `--dindel` a mandatory argument? If not, it should be provided via `options.args`

2021-07-01 10:05 UTC, drpatelh commented on software/lofreq/indelqual/main.nf
> +        -o ${prefix}_indelqual.bam \\
```suggestion
        -o ${prefix}.bam \\
```

2021-07-01 10:05 UTC, drpatelh commented on software/lofreq/indelqual/meta.yml
> +      pattern: "*_indelqual.{bam}"
```suggestion
      pattern: "*.{bam}"
```

2021-07-01 10:05 UTC, drpatelh commented on tests/software/lofreq/indelqual/test.yml
> +    - path: output/lofreq/test_indelqual.bam
```suggestion
    - path: output/lofreq/test.indelqual.bam
```

2021-07-01 10:05 UTC, drpatelh commented on tests/software/lofreq/indelqual/main.nf
> +include { LOFREQ_INDELQUAL } from '../../../../software/lofreq/indelqual/main.nf' addParams( options: [:] )
```suggestion
include { LOFREQ_INDELQUAL } from '../../../../software/lofreq/indelqual/main.nf' addParams( options: ['suffix':'.indelqual'] )
```

2021-07-01 10:05 UTC, drpatelh commented on software/lofreq/indelqual/main.nf
> +    path "*.version.txt"                    , emit: version
We try not to customise the output files as much as possible to leave it to developers to do this.

2021-07-05 09:17 UTC, drpatelh approved these changes
Perfect 👌🏽

2021-07-05 09:17 UTC, merged

2021-07-05 09:34 UTC, kaurravneet4123 commented
Thanks @drpatelh :-) . Please can I check one thing: if I am working on 2 modules at the same time and want to make PRs for both of them, how should I go about it? Can I make 2 PRs from the same forked repo (or do I need to fork the modules repo twice and make the PR separately)? Your guidance would be much appreciated!

2021-07-05 09:43 UTC, drpatelh commented
We some docs for using `git` in this way in the main README under [nf-core modules create](https://github.com/nf-core/modules#nf-core-modules-create). But basically you need to start working off branches which means you only fork the repo once and do your work on separate named branches per module - that way the changes are independent of each other.

2021-07-05 10:00 UTC, kaurravneet4123 commented
Ok. Got it. Many thanks @drpatelh :-)