sageproteomics/sage
nf-core/modules pull request #5677
Opened 2024-05-22 20:34 UTC by dgemperline-lilly

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [X] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [X] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-05-23 15:47 UTC, dgemperline-lilly reviewed
addressed via commit

2024-06-11 17:47 UTC, FloWuenne commented
Hey @dgemperline-lilly is this ready to be reviewed? If yes, I would update the branch, do a final pass and then approve if everything checks out!

2024-06-11 18:52 UTC, dgemperline-lilly commented
> Hey @dgemperline-lilly is this ready to be reviewed? If yes, I would update the branch, do a final pass and then approve if everything checks out!

Yes good to go I think?

David

2024-06-12 14:28 UTC, dgemperline-lilly commented
@adamrtalbot I addressed the proposed changes via additional commit. Any way you can approve?

2024-06-12 15:49 UTC, FloWuenne requested changes

2024-06-12 15:49 UTC, FloWuenne commented on modules/nf-core/sageproteomics/sage/tests/config-cli.json
We are just having a discussion about this in the maintainers team whether putting the file directly here is ok or whether you need to put it somewhere else. Does this file exist somewhere on github already?

2024-06-12 15:50 UTC, FloWuenne commented
@dgemperline-lilly I have added some review comments to fix remaining linting warnings. 
The last thing we need to wait on before merging is where to put the test file. I will get back to you here once we have decided whether including it in the modules folder is ok or not!

2024-06-13 13:56 UTC, dgemperline-lilly commented on modules/nf-core/sageproteomics/sage/tests/config-cli.json
Yes it does - originally had it linked on github publicly. We can revert if that is what is recommended.

2024-06-13 14:09 UTC, FloWuenne commented
@dgemperline-lilly The result from discussions between the maintainers team was pretty clear that test files cannot be in modules directly. Can you please make a PR to : https://github.com/nf-core/test-datasets/tree/modules with your test data? Feel free to ping me to review and approve!

2024-06-13 14:10 UTC, FloWuenne commented on modules/nf-core/sageproteomics/sage/tests/config-cli.json
Finally, please remove the file from this repo and move it to test-datasets. Sorry for the confusion!

2024-06-13 18:11 UTC, dgemperline-lilly commented
@FloWuenne  Opened pull request here: https://github.com/nf-core/test-datasets/pull/1234 with the new file added. Will add in another commit once pull request goes through.

2024-06-13 18:44 UTC, FloWuenne commented
@dgemperline-lilly Just approved the PR on test-datasets. Should be able to query that data in here now 😃 ! Thanks for adding the data to test-datasets David!

2024-06-13 19:23 UTC, dgemperline-lilly commented
Added key to test_dataset.config. Need approval here:

https://github.com/nf-core/modules/pull/5803

2024-06-13 22:14 UTC, FloWuenne commented
OK last thing is to remove the old test file and make the two changes I suggested and we are good! 👍🏻

2024-06-13 22:16 UTC, FloWuenne requested changes

2024-06-13 22:16 UTC, FloWuenne commented on modules/nf-core/sageproteomics/sage/tests/main.nf.test
> +		    file('${moduleTestDir}/config-cli.json', checkIfExists: true)
```suggestion
		    file(params.test_data['proteomics']['parameter']['sage_base_config'], checkIfExists: true)
```

2024-06-13 22:16 UTC, FloWuenne commented on modules/nf-core/sageproteomics/sage/tests/main.nf.test
> +		    file('${moduleTestDir}/config-cli.json', checkIfExists: true)
```suggestion
		   file(params.test_data['proteomics']['parameter']['sage_base_config'], checkIfExists: true)
```

2024-06-14 11:58 UTC, FloWuenne approved these changes
LGTM now ⭐ !

2024-06-14 12:05 UTC, merged