Add PASTA
nf-core/modules pull request #6095
Opened 2024-08-02 12:40 UTC by lrauschning

Closes nf-core/modules#3759.
TODO write module for PASTA guidetree mode as well.

2024-08-02 12:41 UTC, lrauschning commented
Making the PR, as I do not have access to a machine with singularity right now.

2024-08-14 08:33 UTC, SPPearce commented
You may want to try setting `--temporaries ./tmp`

2024-12-10 08:07 UTC, famosab requested changes

2024-12-10 08:07 UTC, famosab commented on modules/nf-core/pasta/guidetree/meta.yml
> +        e.g. `[ id:'test', single_end:false ]`
```suggestion
        e.g. `[ id:'test' ]`
```

2024-12-10 08:07 UTC, famosab commented on modules/nf-core/pasta/align/tests/tags.yml
I think this file is not needed anymore

2024-12-10 08:08 UTC, famosab commented
Maybe you can also swap to https://seqera.io/containers/ to create the mulled containers - its easier and there seems to be an issue with finding the container at the moment :)

2025-03-11 09:13 UTC, luisas commented
I was working with @lrauschning and this was supposed to be integrated in nf-core/multiplesequencealign but plans changed - so we can close this for now. 

We can reopen if plans change again :)

2025-03-11 09:13 UTC, closed without merging