Add Sentieon CoverageMetrics module
nf-core/modules pull request #6122
Opened 2024-08-06 17:07 UTC by adamrtalbot

Additions:
  - Adds Sentieon CoverageMetrics module.
  - Supports intervals and gene_lists files (untested because I don't have one)
  - Adds tests for blocking the outputs, using intervals, supporting multiple BAMs and using different partitions.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-08-06 17:13 UTC, FriederikeHanssen requested changes
Meta yaml is still boilerplate stuff

2024-08-06 17:13 UTC, FriederikeHanssen commented on modules/nf-core/sentieon/coveragemetrics/meta.yml
> +## TODO nf-core: Add a description of the module and list keywords
```suggestion
```

2024-08-06 19:35 UTC, DonFreed commented on modules/nf-core/sentieon/coveragemetrics/main.nf
> +    tuple val(meta), path("*.sample_summary")                , optional: true, emit: sample_summary
Yes, the name of the output files will change with different `--partition` arguments. Many of the output metrics will be suffixed with a `_` separated list of `sample`, `library`, `platform`, and `center`, in that order. You can also use `--partition readgroup`, and `readgroup` cannot be combined with other partitions. The default is `--partition sample`.

Here is a basic command:
```sh
sentieon driver -i input.bam -r ref.fasta --algo CoverageMetrics --omit_base_output output_coverage_metrics
```
This command produces the files:
```sh
output_coverage_metrics
output_coverage_metrics.sample_cumulative_coverage_counts
output_coverage_metrics.sample_cumulative_coverage_proportions
output_coverage_metrics.sample_interval_statistics
output_coverage_metrics.sample_interval_summary
output_coverage_metrics.sample_statistics
output_coverage_metrics.sample_summary
```

Running the same command with `--partition sample,platform,library,center` produces the files:
```sh
output_coverage_metrics
output_coverage_metrics.sample_library_platform_center_cumulative_coverage_counts
output_coverage_metrics.sample_library_platform_center_cumulative_coverage_proportions
output_coverage_metrics.sample_library_platform_center_interval_statistics
output_coverage_metrics.sample_library_platform_center_interval_summary
output_coverage_metrics.sample_library_platform_center_statistics
output_coverage_metrics.sample_library_platform_center_summary
```

FYI, this matches the behavior of the GATK DepthOfCoverage tool.

2024-08-06 20:52 UTC, DonFreed requested changes
Not sure how you would like to handle the output file name. Some other minor changes.

2024-08-06 20:52 UTC, DonFreed commented on modules/nf-core/sentieon/coveragemetrics/meta.yml
> +      homepage: "None"
https://www.sentieon.com/

2024-08-06 20:52 UTC, DonFreed commented on modules/nf-core/sentieon/coveragemetrics/meta.yml
> +      documentation: "None"
https://www.sentieon.com/support/#documentation

2024-08-07 08:45 UTC, FriederikeHanssen commented on modules/nf-core/sentieon/coveragemetrics/main.nf
> +    tuple val(meta) , path(interval)
Ah sorry, I guess this is an intervals file that has all of them listed. In that case, `meta` -> `meta2`

2024-08-07 08:46 UTC, FriederikeHanssen commented on modules/nf-core/sentieon/coveragemetrics/meta.yml
> +## TODO nf-core: Add a description of all of the variables used as output
```suggestion
```

2024-08-07 10:48 UTC, FriederikeHanssen commented on modules/nf-core/sentieon/coveragemetrics/main.nf
> +    tuple val(meta), path("*.sample_summary")                , optional: true, emit: sample_summary
honestly prefer the verbose method :D I never quite understood why we are using `*` everywhere if we 'know' the output name

2024-08-07 10:53 UTC, FriederikeHanssen approved these changes

2024-08-07 14:31 UTC, DonFreed requested changes
Looks good. Just one minor documentation change.

2024-08-07 14:31 UTC, DonFreed commented on modules/nf-core/sentieon/coveragemetrics/meta.yml
> +description: write your description here
This might be `Accelerated implementation of the GATK DepthOfCoverage tool`.

2024-08-07 17:19 UTC, DonFreed approved these changes

2024-08-07 17:39 UTC, merged