Foldmason
nf-core/modules pull request #6355
Opened 2024-08-26 16:02 UTC by luisas

## PR checklist

Add foldmason easy-msa module.

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`

2024-08-26 19:41 UTC, SPPearce commented on modules/nf-core/foldmason/easymsa/main.nf
> +    touch ${prefix}.fa${compress ? '.gz' : ''}
nf-test doesn't like gz files that aren't actually made by gzip, it gives a weird error (printing the full file paths in the snapshot). This is our workaround:
```suggestion
    echo "" | gzip > ${prefix}.fa${compress ? '.gz' : ''}
```

2024-08-26 19:41 UTC, SPPearce commented on modules/nf-core/foldmason/easymsa/tests/main.nf.test
> +                    input[0] = UNTAR.out.untar.map { meta,dir -> [[ id:'test' ], file(dir).listFiles().collect()]}
I feel like this should be the same?
```suggestion
                    input[0] = UNTAR.out.untar.map { meta,dir -> [meta, file(dir).listFiles().collect()]}
```

2024-08-26 19:41 UTC, SPPearce commented on modules/nf-core/foldmason/easymsa/tests/main.nf.test
> +                { assert snapshot(process.out.versions).match("versions0") }
Might need aligning properly, but can you put them into one snapshot:
```suggestion
                { assert snapshot(
                  process.out.msa3di,
                  process.out.msaAA,
                  process.out.versions).match() }
```

2024-08-27 14:43 UTC, SPPearce commented
Looks generally fine, just we only use lower_snake_case for emit channels, would `msa_aa` suffice?

2024-08-27 14:45 UTC, luisas commented
@SPPearce thanks a lot for the comments :) I updated what you suggested and I could use a review when you have some spare time!

2024-08-27 14:48 UTC, luisas commented
It would :) I updated it now

2024-08-27 17:42 UTC, SPPearce submitted a review, later dismissed

2024-08-27 17:46 UTC, SPPearce requested changes
Sorry, pressed approve too fast.
Can you please add a stub test too.

2024-08-27 17:46 UTC, SPPearce commented on modules/nf-core/foldmason/easymsa/tests/main.nf.test
> +                )
```suggestion
                { assert snapshot(process.out).match() }
                )
```

2024-08-27 17:46 UTC, SPPearce commented on modules/nf-core/foldmason/easymsa/tests/main.nf.test
> +                { assert snapshot(process.out.versions).match("versions1") }
```suggestion
                { assert snapshot(process.out).match() }
```

2024-08-27 17:46 UTC, SPPearce commented on modules/nf-core/foldmason/easymsa/tests/main.nf.test.snap
This doesn't look like it has been regenerated.

2024-08-28 08:53 UTC, luisas commented on modules/nf-core/foldmason/easymsa/environment.yml
> +  - "bioconda::foldmason=1.763a428"
It was a mistake! Thanks for spotting it

2024-08-28 09:20 UTC, luisas commented on modules/nf-core/foldmason/easymsa/tests/main.nf.test.snap
Now this is fixed too

2024-08-28 09:23 UTC, SPPearce approved these changes
Thank you!

2024-08-28 09:32 UTC, merged