Added nf-test for cnvpytor/partition
nf-core/modules pull request #6513
Opened 2024-09-01 23:11 UTC by GallVp

Added nf-test for cnvpytor/partition with #6226

2024-09-03 08:32 UTC, SPPearce requested changes
Think this module needs some looking at, not sure how functional it really is.
Be worth checking if we can get prefix working too, rather than relying on pytor.baseName.

2024-09-03 08:32 UTC, SPPearce commented on modules/nf-core/cnvpytor/callcnvs/main.nf
>      """
This has no args.

2024-09-03 08:32 UTC, SPPearce commented on modules/nf-core/cnvpytor/partition/tests/main.nf.test
> +                input[1] = []
Think we need a test checking that this works, given that it didn't previously.

2024-09-03 08:32 UTC, SPPearce commented on modules/nf-core/cnvpytor/partition/tests/nextflow.config
Don't think this is doing anything as args is missing, and suspect it should be in the value channel anyway.

2024-09-03 08:32 UTC, SPPearce commented on modules/nf-core/cnvpytor/partition/main.nf
No args here either.

2024-09-04 02:59 UTC, GallVp commented
Thank you @SPPearce 

This one needs some serious fixing. The test data produces empty outputs.

```bash
cnvpytor -root test.dup.pytor -partition 100 1000 10000
```

Currently the module is not creating any output. It is simply passing the input as output.

2025-03-10 20:16 UTC, closed without merging