Added nf-test for kat/hist
nf-core/modules pull request #6532
Opened 2024-09-02 02:55 UTC by GallVp

Added nf-test for kat/hist with #6226

2024-09-02 07:36 UTC, mahesh-panchal submitted a review, later dismissed

2024-09-02 07:42 UTC, mahesh-panchal commented
I'm wondering if this module should be deprecated now. I don't think Kat is maintained anymore and there's both Merqury and MerquryFK now.

2024-09-02 08:00 UTC, GallVp commented
> I'm wondering if this module should be deprecated now. I don't think Kat is maintained anymore and there's both Merqury and MerquryFK now.

Thanks @mahesh-panchal 

The conda is also failing. If we agree to deprecate it, I'll remove the conda, add the deprecation message and ping you again for another look.

2024-09-02 08:13 UTC, mahesh-panchal commented
Do you know why conda is failing? I can't see what the error message is from the PR logs, but running in Gitpod, it's to do with needing to use the classic conda solver. 

Bernardo hasn't made a release since 2018, and while the issues do seem active on the repository, I think the tool is in maintenance mode at best. The problem is, I'm also not sure how to do the deprecation note. Merqury is the maintained version of the tool, but only does a subset of what KAT does. MerquryFK does more, but isn't really maintained.

2024-09-02 23:20 UTC, GallVp commented
> Do you know why conda is failing? I can't see what the error message is from the PR logs, but running in Gitpod, it's to do with needing to use the classic conda solver.
> 
> Bernardo hasn't made a release since 2018, and while the issues do seem active on the repository, I think the tool is in maintenance mode at best. The problem is, I'm also not sure how to do the deprecation note. Merqury is the maintained version of the tool, but only does a subset of what KAT does. MerquryFK does more, but isn't really maintained.

It says, 

>   Plotting K-mer frequency distributions ... done.  Saved to: None
>
> corrupted double-linked list
> .command.sh: line 6:  9563 Aborted                 (core dumped) kat hist --threads 2 --output_prefix test.hist -d test2_1.fastq.gz

It might be a memory related issue. But then docker and singularity have the same amount of memory. I'll try to pin the dependency versions to see if that helps.

2024-09-03 06:49 UTC, mahesh-panchal commented
Yeah, I don't know how to solve that. I've never come across it before.

2025-02-11 14:14 UTC, vagkaratzas requested changes
Just a minor comment. Other than the `java.lang.NullPointerException: Cannot invoke method getAt() on null object for Docker and Conda`, it looks good.

2025-02-11 14:14 UTC, vagkaratzas commented on modules/nf-core/kat/hist/environment.yml
> +  - conda-forge::matplotlib=3.3.1 # Locked with the container
Do you need to specify these separately here? Are they not included in the `bioconda::kat` environment anyway?
What does `# Locked with the container` imply?

2025-03-10 20:16 UTC, closed without merging