new module gatk/variants2table
nf-core/modules pull request #6619
Opened 2024-09-10 10:20 UTC by lindenb

This modules implements gatk/variants2table ( was https://nfcore.slack.com/archives/CJRH30T6V/p1725906645564699 )

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] If necessary, include test data in your PR.
- [X] Remove all TODO statements.
- [X] Emit the `versions.yml` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [X] `nf-core modules test <MODULE> --profile singularity`
    - [X] `nf-core modules test <MODULE> --profile conda`

2024-09-10 11:54 UTC, fellen31 requested changes

2024-09-10 11:54 UTC, fellen31 commented on modules/nf-core/gatk4/variantstotable/meta.yml
> +      description: GATK output
```suggestion
      description: Tab-delimited table of extracted fields from VCF
```

2024-09-10 11:54 UTC, fellen31 commented on modules/nf-core/gatk4/variantstotable/tests/main.nf.test
> +                { assert snapshot(process.out).match()}
```suggestion
                { assert snapshot(process.out).match() }
```

2024-09-10 12:12 UTC, lindenb commented on modules/nf-core/gatk4/variantstotable/main.nf
> +        log.info '[GATK VariantFiltration] Available memory not known - defaulting to 3GB. Specify process memory requirements to change this.'
ah sorry, for all those copy-n-paste

2024-09-10 12:15 UTC, lindenb commented on modules/nf-core/gatk4/variantstotable/tests/main.nf.test
> +                    [ id:'test' , gatk_args: '-F CHROM -F POS -F TYPE -GF AD' ], // meta map
while I know one can set the arguments in  a nextflow.config, I also like to be able to set the parameters in a channel to try multiple parameters for the same vcf:
```
ch = Channel.of(
   ' --split-multi-allelic -F CHROM -F POS -F TYPE -GF AD',
   ' -GF AD',
   '-F CHROM -F POS -F TYPE ' )
etc...
```

2024-09-10 12:18 UTC, lindenb commented on modules/nf-core/gatk4/variantstotable/tests/main.nf.test
@fellen31 what is a **stub** test ?

2024-09-10 12:31 UTC, fellen31 commented on modules/nf-core/gatk4/variantstotable/tests/main.nf.test
> +                    [ id:'test' , gatk_args: '-F CHROM -F POS -F TYPE -GF AD' ], // meta map
These arguments needs to be supplied via `ext.args` and not an input channel.

2024-09-10 13:18 UTC, lindenb commented
@fellen31 back to you. Thanks for the review, I can remove this `meta.gatk_args` if needed but I like the flexibility of my implementation :-)

2024-09-10 13:24 UTC, fellen31 commented on modules/nf-core/gatk4/variantstotable/tests/main.nf.test
> +                    [ id:'test' , gatk_args: '-F CHROM -F POS -F TYPE -GF AD' ], // meta map
I see. I don't think any other module in nf-core implements this, you can check the 1.3 and 1.6 of the [module guidelines](https://nf-co.re/docs/guidelines/components/modules). 

You could: either use `nf-core modules patch` to change the module locally as you wish (after adding it to nf-core), or include the process 4 different times, e.g.:

```
include { GATK4_VARIANTSTOTABLE as VARIANTSTOTABLE_AF } from '...'
include { GATK4_VARIANTSTOTABLE as VARIANTSTOTABLE_GNOMAD_AF } from '...'
include { GATK4_VARIANTSTOTABLE as VARIANTSTOTABLE_EXOME_AF } from '...'
include { GATK4_VARIANTSTOTABLE as VARIANTSTOTABLE_UKBB_AF } from '...'
```
each with it's own `ext.args` in the config.

2024-09-10 13:51 UTC, cmatKhan commented
Regarding a channel for input arguments -- it would be better to include the [--arguments_file](https://gatk.broadinstitute.org/hc/en-us/articles/360036896892-VariantsToTable#--arguments_file) as input. It technically should be anyway:

https://nf-co.re/docs/guidelines/components/modules#required-and-optional-input-files

> All mandatory and optional input files MUST be included in input channel definitions.

I'd also advocate including the [--intervals](https://gatk.broadinstitute.org/hc/en-us/articles/360036896892-VariantsToTable#--intervals) and [--exclude-intervals](https://gatk.broadinstitute.org/hc/en-us/articles/360036896892-VariantsToTable#--intervals) as file input. You would only set these when they are not null -- otherwise, the `-L` and `-XL` arguments can be passed in `task.args`

2024-09-10 13:54 UTC, lindenb commented
Oh , I got this suggestion https://nfcore.slack.com/archives/CJRH30T6V/p1725975854237139?thread_ts=1725974540.609939&cid=CJRH30T6V

```
    ext.args = { meta.gatk_args }
```

I understand now, I'll update my code.

@cmatKhan I'll add both arguments.

2024-09-11 13:41 UTC, fellen31 reviewed
NIce, thanks for removing the custom meta. There's two args in the module, could you just remove one of them?

2024-09-11 13:41 UTC, fellen31 commented on modules/nf-core/gatk4/variantstotable/main.nf
> +        $args
```suggestion
        VariantsToTable \\
        ${args} \\
        --variant $vcf \\
        --output ${prefix}.tsv \\
        --reference $fasta \\
        --tmp-dir . \\
        $arguments_file_arg \\
        $include_intervals \\
        $exclude_intervals
```

2024-09-11 13:41 UTC, fellen31 commented on modules/nf-core/gatk4/variantstotable/main.nf
> +    touch "${prefix}.tsv"
```suggestion
    touch ${prefix}.tsv
```

2024-09-12 11:36 UTC, fellen31 approved these changes
👍

2024-09-12 12:02 UTC, merged