Add deepsomatic module scaffolding
nf-core/modules pull request #6622
Opened 2024-09-10 17:04 UTC by vaxyzek

This is a first version of PR to add deepsomatic capabilities into nf-core/modules. Currently this PR contains code changes only (without tests and most of metadata) and created to gather the initial feedback.

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-09-12 09:49 UTC, maxulysse commented
@nf-core-bot fix linting pretty please :pray:

2024-09-12 10:07 UTC, maxulysse commented on modules/nf-core/deepsomatic/environment.yml
This file can be deleted since there is no bioconda recipe for this yet

2024-09-12 12:04 UTC, maxulysse commented on modules/nf-core/deepsomatic/tests/main.nf.test
I'm hoping we should be able to use the same data that is used on the mutect2 tests:
https://github.com/nf-core/modules/blob/master/modules/nf-core/gatk4/mutect2/tests/main.nf.test

2024-10-23 20:16 UTC, vaxyzek commented on modules/nf-core/deepsomatic/environment.yml
Removed

2024-10-23 20:17 UTC, vaxyzek commented on modules/nf-core/deepsomatic/tests/main.nf.test
Added similar test data as in mutect2

2024-11-01 08:43 UTC, maxulysse commented
@nf-core-bot fix linting pretty please :pray:

2024-11-01 08:53 UTC, maxulysse commented
Please @nf-core-bot fix linting pretty please :pray: :pray:

2024-11-01 08:56 UTC, maxulysse commented on modules/nf-core/deepsomatic/main.nf
> +
```suggestion

```

2024-11-01 08:56 UTC, maxulysse commented on modules/nf-core/deepsomatic/main.nf
> +
```suggestion
```

2024-11-01 09:50 UTC, maxulysse commented on modules/nf-core/deepsomatic/main.nf
> +    tuple val(meta2), path(input_tumor), path(index_tumor)
```suggestion
    tuple val(meta), path(input_normal), path(index_normal), path(input_tumor), path(index_tumor)
```

2024-11-01 09:50 UTC, maxulysse commented on modules/nf-core/deepsomatic/main.nf
> +    tuple val(meta6), path(gzi)
```suggestion
    tuple val(meta2), path(intervals)
    tuple val(meta3), path(fasta)
    tuple val(meta4), path(fai)
    tuple val(meta5), path(gzi)
```

2024-11-01 09:51 UTC, maxulysse commented on modules/nf-core/deepsomatic/meta.yml
> +          e.g. [ id:'test', single_end:false ]
```suggestion
```

2024-11-01 09:52 UTC, maxulysse commented on modules/nf-core/deepsomatic/meta.yml
> +  - - meta6:
```suggestion
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - intervals:
        type: file
        description: file containing intervals
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.fasta"
  - - meta4:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: Index of reference fasta file
        pattern: "*.fai"
  - - meta5:
```

2024-11-01 09:53 UTC, maxulysse commented on modules/nf-core/deepsomatic/tests/main.nf.test
> +                ]
```suggestion
                    [ id:'tumor_vs_normal' ],
                    file(params.modules_testdata_base_path + 'genomics/homo_sapiens/illumina/bam/test.paired_end.recalibrated.sorted.bam', checkIfExists: true),
                    file(params.modules_testdata_base_path + 'genomics/homo_sapiens/illumina/bam/test.paired_end.recalibrated.sorted.bam.bai', checkIfExists: true),
                    file(params.modules_testdata_base_path + 'genomics/homo_sapiens/illumina/bam/test2.paired_end.recalibrated.sorted.bam', checkIfExists: true),
                    file(params.modules_testdata_base_path + 'genomics/homo_sapiens/illumina/bam/test2.paired_end.recalibrated.sorted.bam.bai', checkIfExists: true)
                ]
```

2024-11-01 09:54 UTC, maxulysse commented on modules/nf-core/deepsomatic/tests/main.nf.test
> +                input[5] = [
```suggestion
                input[1] = [
                    [ id:'intervals' ],
                    []
                ]
                input[2] = [
                    [ id:'genome' ],
                    file(params.modules_testdata_base_path + 'genomics/homo_sapiens/genome/chr21/sequence/genome.fasta', checkIfExists: true)
                ]
                input[3] = [
                    [ id:'genome' ],
                    file(params.modules_testdata_base_path + 'genomics/homo_sapiens/genome/chr21/sequence/genome.fasta.fai', checkIfExists: true)
                ]
                input[4] = [
```

2024-11-01 09:54 UTC, maxulysse commented on modules/nf-core/deepsomatic/tests/main.nf.test
> +                        process.out.f1r2,
```suggestion
```

2024-11-01 09:55 UTC, maxulysse commented on modules/nf-core/deepsomatic/tests/main.nf.test.snap
> +            null,
```suggestion
```

2024-11-01 10:01 UTC, maxulysse requested changes
Made a couple of suggestions to rearrange the input channel of the modules, in the way we usually do in nf-core.
And a suggestion to remove some assertions in the tests that shouldn't have been there.

Could you add a couple of lines around here to exclude the conda and singularity tests from the suite of tests, as we don't have conda for this tool and converting the container from docker to singularity seems to be causing memory issues?
https://github.com/nf-core/modules/blob/master/.github/workflows/test.yml#L279-L280

2024-11-05 21:18 UTC, vaxyzek commented
hi @maxulysse, I've committed proposed input channels re-arrangement and excluded deepsomatic from conda and singularity tests.

2024-11-11 17:03 UTC, maxulysse commented
@nf-core-bot fix linting pretty please :pray:

2024-11-11 17:06 UTC, maxulysse commented on modules/nf-core/deepsomatic/meta.yml
> +      - ${prefix}.vcf.gz:
```suggestion
      - "${prefix}.vcf.gz":
```

2024-11-11 17:06 UTC, maxulysse commented on modules/nf-core/deepsomatic/meta.yml
> +      - ${prefix}.vcf.gz.tbi: {}
```suggestion
      - "${prefix}.vcf.gz.tbi": {}
```

2024-11-11 17:06 UTC, maxulysse commented on modules/nf-core/deepsomatic/meta.yml
> +      - ${prefix}.g.vcf.gz:
```suggestion
      - "${prefix}.g.vcf.gz":
```

2024-11-11 17:07 UTC, maxulysse commented on modules/nf-core/deepsomatic/meta.yml
> +      - ${prefix}.g.vcf.gz.tbi: {}
```suggestion
      - "${prefix}.g.vcf.gz.tbi": {}
```

2024-11-11 17:14 UTC, maxulysse commented on modules/nf-core/deepsomatic/tests/main.nf.test.snap
> +                "normal_out.vcf.gz"
```suggestion
                "tumor_vs_normal_out.vcf.gz"
```

2024-11-11 17:15 UTC, maxulysse commented on .github/workflows/test.yml
> +          - profile: conda
```suggestion
```

2024-11-11 17:20 UTC, maxulysse approved these changes

2024-11-11 17:22 UTC, maxulysse commented on modules/nf-core/deepsomatic/tests/main.nf.test
> +                        process.out.vcf.collect { file(it[1]).getName() },
If I remember well the VCF is empty, so not super useful here.
I'll play around that in Sarek

2024-11-11 18:07 UTC, merged