Lighter
nf-core/modules pull request #6626
Opened 2024-09-11 10:38 UTC by vtorda

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-09-23 14:55 UTC, nvnieuwk requested changes
Some comments, but overall good job on this one :partying_face:

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/main.nf
> +    val output_dir
Are these required values for the module to run?

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/main.nf
> +    path "versions.yml"           , emit: versions
```suggestion
    tuple val(meta), path("*.fq.gz"), emit: outfastq
    path "versions.yml"             , emit: versions
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/main.nf
> +        -od ${output_dir} \\
```suggestion
        -od ${prefix} \\
```

I think it makes more sense to use the prefix here

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/meta.yml
> +## TODO nf-core: Add a description of the module and list keywords
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/meta.yml
> +## TODO nf-core: Add a description of all of the variables used as input
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/meta.yml
> +  ## TODO nf-core: Delete / customise this example input
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/meta.yml
> +      pattern: "*.{fastq.gz,fq.gz}"
```suggestion
  - fastqs:
      type: list
      description: A list of compressed fastq files holding adaptor free reads
      pattern: "*.{fastq.gz,fq.gz}"
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/meta.yml
> +## TODO nf-core: Add a description of all of the variables used as output
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/meta.yml
> +  ## TODO nf-core: Delete / customise this example output
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/tests/main.nf.test
> +// nf-core modules test lighter
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/tests/main.nf.test
> +        // You can find more information about how to use a 'setup' method in the docs (https://nf-co.re/docs/contributing/modules#steps-for-creating-nf-test-for-chained-modules).
```suggestion
    test("sarscov2 - illumina - fastq") {

```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/tests/main.nf.test
> +                // TODO nf-core: define inputs of the process here. Example:
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/tests/main.nf.test
> +                // See https://nf-co.re/docs/contributing/tutorials/nf-test_assertions for more information and examples.
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/tests/main.nf.test
> +    // TODO nf-core: Change the test name preferably indicating the test-data and file-format used but keep the " - stub" suffix.
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/tests/main.nf.test
> +                // TODO nf-core: define inputs of the process here. Example:
```suggestion
```

2024-09-23 14:55 UTC, nvnieuwk commented on modules/nf-core/lighter/tests/main.nf.test
> +                //TODO nf-core: Add all required assertions to verify the test output.
```suggestion
```

2025-03-11 13:53 UTC, vtorda commented
Thanks for asking! Sorry but I'm not planning to work on this anymore.
Thanks!

On Tue, 11 Mar 2025, 12:48 Luisa Santus, ***@***.***> wrote:

> @vtorda <https://github.com/vtorda> Are you planning to work on this one?
>
> We are doing the nf-core spring cleaning and are trying to close PRs that
> are not used anymore. They can be reopened in the future if needed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nf-core/modules/pull/6626#issuecomment-2714073170>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKKDIXHCW6VUNYVRFZE6EM32T3LQBAVCNFSM6AAAAABOAVGKAOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMJUGA3TGMJXGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
> [image: luisas]*luisas* left a comment (nf-core/modules#6626)
> <https://github.com/nf-core/modules/pull/6626#issuecomment-2714073170>
>
> @vtorda <https://github.com/vtorda> Are you planning to work on this one?
>
> We are doing the nf-core spring cleaning and are trying to close PRs that
> are not used anymore. They can be reopened in the future if needed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nf-core/modules/pull/6626#issuecomment-2714073170>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKKDIXHCW6VUNYVRFZE6EM32T3LQBAVCNFSM6AAAAABOAVGKAOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMJUGA3TGMJXGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-03-11 14:01 UTC, luisas commented
@vtorda No worries! I will close the PR then. 

If you want to work on this in the future, you can always reopen it.

2025-03-11 14:01 UTC, closed without merging