Migrate umitools/group to nf-test
nf-core/modules pull request #6653
Opened 2024-09-16 20:12 UTC by SPPearce

2024-09-19 10:03 UTC, Joon-Klaps requested changes
Minor suggestions

2024-09-19 10:03 UTC, Joon-Klaps commented on modules/nf-core/umitools/group/tests/main.nf.test
> +    test("with_umi - bam") {
```suggestion
    test("with_umi - create only bam") {
```

2024-09-19 10:03 UTC, Joon-Klaps commented on modules/nf-core/umitools/group/tests/main.nf.test
> +    test("with_umi - tsv") {
```suggestion
    test("with_umi - create bam and tsv") {
```

2024-09-19 10:03 UTC, Joon-Klaps commented on modules/nf-core/umitools/group/tests/main.nf.test
> +                    process.out.tsv,
```suggestion
                    process.out.tsv,
                    bam(process.out.bam[0][1]).getReadsMD5(),
```

2024-11-20 15:48 UTC, SPPearce commented
Thanks @Joon-Klaps

2024-11-20 15:56 UTC, merged