Be consistent in GHA names
nf-core/modules pull request #6766
Opened 2024-10-10 14:46 UTC by maxulysse

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-10-11 09:24 UTC, mashehu requested changes

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up Prettier
this is a install step
```suggestion
      - name: Install Prettier
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up editorconfig-checker
```suggestion
      - name: Install editorconfig-checker
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up pip
```suggestion
      - name: Update pip
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up nf-core tools development version
```suggestion
      - name: Install nf-core tools development version
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up pip
```suggestion
      - name: Update pip
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up pip
not sure if we actually need this step anymore

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up nf-core tools development version
```suggestion
      - name: Install nf-core tools development version
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up Python dependencies
```suggestion
      - name: Install Python dependencies
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
>            conda install -n base conda-libmamba-solver
this setup step can be removed if we add the `conda-solver:` to the setup-minoconda step

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up Python dependencies
```suggestion
      - name: Install Python dependencies
```

2024-10-11 09:24 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up Conda
same as above

2025-02-03 15:54 UTC, mashehu commented on .github/workflows/test.yml
> +      - name: Set up apptainer
```suggestion
      - name: Set up Apptainer
```

2025-02-03 15:54 UTC, mashehu approved these changes

2025-02-03 15:57 UTC, maxulysse commented
I need to solve the conflicts, I'd say this PR is a bit too old

2025-02-03 17:41 UTC, mashehu approved these changes

2025-03-10 09:22 UTC, merged