pypgx/runngspipeline
nf-core/modules pull request #6823
Opened 2024-10-22 11:48 UTC by Jorisvansteenbrugge

## PR checklist

Closes #5987
This PR adds a new module: pypgx/runngspipeline

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`

2024-10-31 11:44 UTC, famosab commented
Can you run the test locally with the conda profile?
`nf-core modules test pypgx/runngspipeline --profile conda -u

2024-11-01 07:45 UTC, Jorisvansteenbrugge commented
> Can you run the test locally with the conda profile? `nf-core modules test pypgx/runngspipeline --profile conda -u`

@famosab Thank you for taking a look! I get the same error unfortunately.. I wonder if this is the same issue as #4234 opened by @edmundmiller . 
> I see this error appears when running tests for subworkflows. Could be that we need to add a name to environment.yml? If two modules in a subworkflow have exactly the same environment.yml I suspect the environment names may clash

While this is not a subworkflow, the nf-test for this module is chained with other modules that use the exact same `environment.yml`. I am however not sure what the solution is.

2024-11-29 13:37 UTC, LouisLeNezet requested changes
Thanks for the contribution.
I'm just a bit concerned on how the output is given back.
Is there a need for it to be in a zip format ?

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    val(assembly_version)
Is this argument mandatory ?

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +        --depth-of-coverage ${coverage} \\
It seems that the `depth-of-coverage` and the `control-statistics` are not mandatory.
Could you add a check in the script to output the command only if the path is provided ?
Such as

```
def depth_coverage_cmd = coverage ? "--depth-of-coverage ${coverage}" : ""
```

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +        pattern: "*.{vcf.gz}"
Can it not be `.bcf` files ?

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +        pattern: "*.{vcf.gz.tbi}"
Can it be `.csi` ?

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +        description: ZIP compressed file with depth of coverage information. Output
Could you add that they are optional ?

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +        description: Pharmacogene to genotype/phenotype.
Could you expand a bit the description ?
What does the gene name should correspond to, is there a list of them from which to chose ?

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    tuple val(meta), val(pgx_gene), path("*pypgx_output"), emit: outdir
I don't think that the `val(pgx_gene)` should be here.
What is the rational behind this choice ?

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +      - "*pypgx_output":
Could you provide a list of what to expect from the output directory ?
A more nf-core way of writing this, would be to list in different channel the different output file depending on their extension.

2024-11-29 13:37 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/tests/main.nf.test
> +                    metaFile,
Is there only a `results.zip` inside the output ?
Could you snapshot all the files names present inside the zip file ?

2025-01-10 08:12 UTC, Jorisvansteenbrugge commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    val(assembly_version)
Hi @LouisLeNezet Thank you for your thorough review, and sorry for replying late! Which argument are you referring to exactly?

2025-01-10 08:20 UTC, Jorisvansteenbrugge commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +        pattern: "*.{vcf.gz}"
The variants are calculated in another step of the same program [pypgx/createinputvcf](https://github.com/nf-core/modules/blob/master/modules/nf-core/pypgx/createinputvcf/main.nf), which happens to be VCF format. The documentation also only mentions VCF files. I did not test if the tool works with BCF but it might not be relevant since the recommended approach is to use the creatinputvcf output.  What do you think?

2025-01-10 08:25 UTC, Jorisvansteenbrugge commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    tuple val(meta), val(pgx_gene), path("*pypgx_output"), emit: outdir
Ah yes you are most likely right.  I added that so I could easily group the outputs (on pgx_gene) of this process later in my own pipeline, but it might not be nf-core style. If you agree then I will remove it.

2025-01-10 09:21 UTC, Jorisvansteenbrugge commented on modules/nf-core/pypgx/runngspipeline/tests/main.nf.test
> +                    metaFile,
There are multiple output files (mostly ZIP) in the output directory. But `results.zip` is the main output, which always contains only `metadata.txt` and `data.tsv`. If those snapshots match then the output of the pipeline is the same between runs as well.

2025-01-10 10:25 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    val(assembly_version)
I was talking about the `assembly_version`

2025-01-10 10:26 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +        pattern: "*.{vcf.gz}"
That does make sense to me, I was just thinking if the tool was able to produce something else.
You can keep it like that 😉

2025-01-10 10:26 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/meta.yml
> +        pattern: "*.{vcf.gz.tbi}"
Okay, fine for me

2025-01-10 10:28 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    tuple val(meta), val(pgx_gene), path("*pypgx_output"), emit: outdir
Even in your pipeline, the recommended approach would be to add this parameter through the config file of the module.
This way the user can clearly see what's is added to each module.

2025-01-10 10:28 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/tests/main.nf.test
> +                    metaFile,
Okay, this is fine for me !

2025-01-10 13:08 UTC, Jorisvansteenbrugge commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    val(assembly_version)
I have set a default in the process as
`def assembly = assembly_version ?: "GRCh38"` (https://github.com/nf-core/modules/blob/pypgx/runngspipeline/modules/nf-core/pypgx/runngspipeline/main.nf#L26)

This is in line with how I pass the assembly_version value channel to other processes of the same tool (which are already in master):
- https://github.com/nf-core/modules/blob/master/modules/nf-core/pypgx/createinputvcf/main.nf#L28
- https://github.com/nf-core/modules/blob/master/modules/nf-core/pypgx/computecontrolstatistics/main.nf#L26
- https://github.com/nf-core/modules/blob/master/modules/nf-core/pypgx/preparedepthofcoverage/main.nf#L26

Do you propose something else?

2025-01-10 13:09 UTC, Jorisvansteenbrugge commented
> Thanks for the contribution. I'm just a bit concerned on how the output is given back. Is there a need for it to be in a zip format ?

The zip files are simply what the tool outputs, it is not something I added myself

2025-01-10 14:49 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    val(assembly_version)
I'm not sure that `def assembly = assembly_version ?: "GRCh38"` is the best thing to do.
I was just wondering if the tool needed this string and if so you could just use: `assert assembly : "Assembly name should be provided"`. From my point of view the specie should not be set as default, but if your previous PR was accepted as such this is fine for me.

2025-01-10 14:50 UTC, LouisLeNezet commented
> > Thanks for the contribution. I'm just a bit concerned on how the output is given back. Is there a need for it to be in a zip format ?
> 
> @LouisLeNezet The zip files are simply what the tool outputs, it is not something I added myself

That's fine for me then.

2025-01-10 14:57 UTC, LouisLeNezet approved these changes
From looking at the other modules of this tool, this is ready to merge !
LGTM

2025-01-13 07:54 UTC, merged

2025-01-13 07:55 UTC, Jorisvansteenbrugge commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    val(assembly_version)
I think I understand what you mean. I guess in hindsight it sounds indeed be better to retrieve the assembly_version from the config file instead. I will keep it in mind, perhaps I can do an update of all pypgx modules at a later time to streamline this.

2025-01-13 07:59 UTC, LouisLeNezet commented on modules/nf-core/pypgx/runngspipeline/main.nf
> +    val(assembly_version)
No worry, but this would indeed be a better approach as all modules try to be agnostic to the specie studied 😉