Fix bug in gffread
nf-core/modules pull request #686
Opened 2021-09-03 08:42 UTC by jfnavarro

Closes #684  https://github.com/nf-core/modules/issues/684

The module will fail if the input has .gtf as extension.

2021-09-09 07:21 UTC, jfy133 approved these changes

2021-09-15 16:07 UTC, drpatelh requested changes
Thanks @jfnavarro ! The best way to fix this would be to use the `prefix` variable so developers can pick whatever suffix they want to use as opposed to using `out` as hard-coded. 

You will also need to change the line below:
https://github.com/nf-core/modules/blob/561f16fe7430eefce5b668afccde7c20790dda0f/tests/modules/gffread/main.nf#L5

to

```
include { GFFREAD } from '../../../modules/gffread/main.nf' addParams( options: [suffix: '.out'] )
```

and it should work 🤞🏽

2021-09-15 16:07 UTC, drpatelh commented on modules/gffread/meta.yml
> +      pattern: "*.{out.gtf}"
```suggestion
      pattern: "*.{gtf}"
```

2021-09-15 18:54 UTC, drpatelh approved these changes

2021-09-15 18:55 UTC, merged