update bowtie2 v2.5.4 in bowtie2/build
nf-core/modules pull request #6870
Opened 2024-10-28 12:59 UTC by LucilleAugusta

## PR checklist

Closes #6821  

- [ x] This comment contains a description of changes (with reason).
- [ x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ x] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`

2024-10-29 14:57 UTC, fmalmeida commented
Hi @LucilleAugusta ,
Looking at the error, although strange, it looks like for some reason, the lines collected are not exactly the same, probably due the order of some reads.

To try to solve that, I have changed the 'sorting' value to true in the nf-test file, so that we ensure to have always the same order, and then increased a little bit the amount of lines from output collected.

Let's see if this help. If so, something similar has to be done for the other tests that fail.

2024-10-31 13:35 UTC, LucilleAugusta commented
Thanks for taking a look @fmalmeida. 

The tests failing seems to be related to subwokflows - `fastq_align_dna` and `fastq_align_bowtie2`. 
It is not clear to me if this is related to I the changes I made. 
Can you help me define the next steps?

2024-11-04 09:02 UTC, fmalmeida commented
Hi @LucilleAugusta ,

I seems that the other workflows are just complaining in the `versions.yml` snapshot which makes sense since we updated the bowtie2 version.

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/e801878b-4e75-4981-b033-8f2ba6f77da0">

So, probably just running them with `--update-snapshot` should do the trick.

😄

2024-12-11 21:16 UTC, edmundmiller requested changes

2024-12-11 21:16 UTC, edmundmiller commented on modules/nf-core/bowtie2/align/main.nf
> +        'oras://community.wave.seqera.io/library/bowtie2_samtools_pigz:19e9ad812f803021' :
```suggestion
        'oras://community.wave.seqera.io/library/bowtie2_samtools_pigz:19e9ad812f803021' :
```

We're not supporting oras yet. There's a script https://github.com/nf-core/modules/blob/master/.github/scripts/wave_singularity.py for this if anyone beats me to it, just going through Seqera container issues.

2025-01-08 08:21 UTC, SPPearce commented
@LucilleAugusta , do you need help to get this finished off?

2025-03-11 12:57 UTC, famosab commented
@LucilleAugusta Bump :)

2025-06-08 18:47 UTC, SPPearce commented
Closing as this has already been completed in the meantime.

2025-06-08 18:47 UTC, closed without merging