Add STIMULUS/CHECKTORCHMODEL
nf-core/modules pull request #6898
Opened 2024-10-29 16:00 UTC by itrujnara

Closes #6872 
Closes nf-core/deepmodeloptim#197

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`

2024-10-29 16:01 UTC, itrujnara commented
The nf-test fails because the current version of the Python script expects a JSON and the test data is YAML. It will be fixed soon.

2024-10-30 11:46 UTC, alessiovignoli commented on modules/nf-core/stimulus/checktorchmodel/tests/main.nf.test
> +// TODO nf-core: Once you have added the required tests, please run the following command to build this file:
```suggestion
```

2025-02-11 18:29 UTC, vagkaratzas requested changes
Some comments here and there. Not sure about the container, if it can be in nf-core modules with just that. Is there a similar module?

2025-02-11 18:29 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    def weights_arg = initial_weights ? "--initial_weights ${initial_weights}" : ""
Is this used somewhere?

2025-02-11 18:29 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    path(data)
no meta? :(

2025-02-11 18:29 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    container "docker.io/mathysgrapotte/stimulus-py:0.2.4.dev"
since there is an environment.yml, shouldn't you have a conda declaration here as well?

2025-02-11 18:29 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    # wait or it to start
```suggestion
    # wait for it to start
```

2025-02-11 18:29 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    container "docker.io/mathysgrapotte/stimulus-py:0.2.4.dev"
If it's very container specific, probably remove the environment.yml? Not sure about this

2025-02-12 15:10 UTC, itrujnara commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    def weights_arg = initial_weights ? "--initial_weights ${initial_weights}" : ""
Nice catch, I probably removed it by accident

2025-02-12 15:11 UTC, itrujnara commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    path(data)
I've found a way to put it back in, it might be useful

2025-02-12 15:46 UTC, itrujnara commented
I've addressed the comments. I'm still working on the Conda tests.

2025-02-13 07:54 UTC, vagkaratzas requested changes
Almost there. Some more comments, and to find out why the test are failing!

2025-02-13 07:54 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    tuple val(meta), path(model), path(model_config), path(initial_weights)
```suggestion
    tuple val(meta) , path(data), path(data_config)
    tuple val(meta2), path(model), path(model_config), path(initial_weights)
```

2025-02-13 07:54 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    tag "$data_config - $data"
Why not just:
`tag "$meta.id"`

2025-02-13 07:54 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/main.nf
> +    prefix          = task.ext.prefix ?: model.baseName.replaceFirst(/\.py/, "")
Just a suggestion here. Instead of trying to parse the model's file name, shouldn't we just use the `meta.id` as in every other module? You can feed the module the python filename as a meta then, when calling the module.

2025-02-13 07:54 UTC, vagkaratzas commented on modules/nf-core/stimulus/checktorchmodel/meta.yml
> +  - - meta:
```suggestion
  - - meta2:
```

2025-02-13 15:50 UTC, vagkaratzas approved these changes
Good!

2025-02-14 07:19 UTC, vagkaratzas requested changes
I'll be on standby to do a final check after the conda env is fixed.

2025-03-11 10:06 UTC, luisas commented
@itrujnara I assume you are planning to work on this one and it should be therefore stay open right? 

asking for the nf-core spring cleaning

2025-03-11 12:31 UTC, luisas commented
Great! Thanks for replying :)

2026-04-15 20:06 UTC, SPPearce commented
Closing due to lack of response. Please reopen if you (or anyone else) have any plans to continue.

2026-04-15 20:06 UTC, closed without merging