Add scds module
nf-core/modules pull request #6907
Opened 2024-10-30 10:52 UTC by cakirb

This PR introduces a module for **scds** to address issue https://github.com/nf-core/scdownstream/issues/118. Most of the code in this module is adapted from a local module in the scdownstream pipeline originally developed by @nictru ([link](https://github.com/nf-core/scdownstream/tree/dev/modules/local/doublet_detection/scds)).

While the module is functionally complete and ready for use, testing is currently impacted by a syntax issue in scds related to the xgboost version (see proposed fix: https://github.com/kostkalab/scds/pull/9).

This PR should be retested once the scds package supports both older and newer xgboost versions, allowing compatibility across environments.

## PR checklist
- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-10-30 20:26 UTC, nictru requested changes

2024-10-30 20:26 UTC, nictru commented on modules/nf-core/scds/main.nf
> +        'community.wave.seqera.io/library/bioconductor-scds_r-seurat:0a9b33d0ff3ee819' }"
```suggestion
        'https://depot.galaxyproject.org/singularity/bioconductor-scds:1.18.0--r43hdfd78af_0':
        'biocontainers/bioconductor-scds:1.18.0--r43hdfd78af_0' }"
```

2024-10-30 20:26 UTC, nictru commented on modules/nf-core/scds/environment.yml
> +  - conda-forge::r-seurat=5.1.0
```suggestion
  - bioconda::bioconductor-scds=1.18.0
  - conda-forge::r-seurat=5.1.0
  - conda-forge::r-xgboost=1.7.6
```

2024-10-30 20:29 UTC, nictru requested changes

2024-10-30 20:29 UTC, nictru commented on modules/nf-core/scds/templates/scds.R
> +################################################
```suggestion
################################################

```

2024-10-30 20:39 UTC, nictru requested changes
Improve stub and version capture

2024-10-30 20:39 UTC, nictru commented on modules/nf-core/scds/main.nf
> +    def args = task.ext.args ?: ''
```suggestion
```

2024-10-30 20:39 UTC, nictru commented on modules/nf-core/scds/main.nf
> +    touch versions.yml
```suggestion
    
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        scds: \$(Rscript -e "library(scds); cat(as.character(packageVersion('scds')))")
    END_VERSIONS
```

2024-10-30 20:39 UTC, nictru commented on modules/nf-core/scds/templates/scds.R
> +        paste('    R:', r.version),
```suggestion
```

2025-01-09 16:49 UTC, LeonHafner commented
Proof that the linting works locally:
![Screenshot 2025-01-09 at 17 48 40](https://github.com/user-attachments/assets/57f3d45a-4d1a-4e80-ac35-09086c13909f)

2025-01-10 09:40 UTC, itrujnara reviewed
Very nice module, just one small doubt to address

2025-01-10 09:40 UTC, itrujnara commented on modules/nf-core/scds/main.nf
> +    tuple val(meta), path("*.rds"), emit: rds
You should test for input and output file names being identical, unless you are 100% positive the tool prevents this

2025-01-10 10:39 UTC, LeonHafner commented on modules/nf-core/scds/main.nf
> +    tuple val(meta), path("*.rds"), emit: rds
Thanks, I didn't have that in mind :-)

2025-01-10 10:50 UTC, itrujnara approved these changes
Looks good to me, but you still need to get approval from Nico

2025-01-10 11:15 UTC, nictru approved these changes
Thanks everyone!

2025-01-10 11:55 UTC, merged