Initial addition
nf-core/modules pull request #6908
Opened 2024-10-30 11:10 UTC by ramirobarrantes

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-10-30 11:13 UTC, ramirobarrantes commented
@nf-core-bot fix linting

2024-10-30 11:24 UTC, itrujnara requested changes
Picky comments for module code, the meta file requires some improvements

2024-10-30 11:24 UTC, itrujnara commented on modules/nf-core/coptr/index/main.nf
> +    def args = task.ext.args ?: ''
Align equal signs

2024-10-30 11:24 UTC, itrujnara commented on modules/nf-core/coptr/index/main.nf
> +    def args = task.ext.args ?: ''
As above

2024-10-30 11:24 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +        description: Fasta file(s) ending in [.fasta, .fna, .fa]
Can you make it slightly more descriptive?

2024-10-30 11:24 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +          ontologies: &id001
The whole ontologies entry is wrong (and not needed for meta)

2024-10-30 11:24 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +            Groovy Map containing genome information
This description is not for this file

2024-10-30 11:24 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +          ontologies: *id001
The above ontologies entry should go here, the id string is unnecessary

2024-10-30 13:06 UTC, ramirobarrantes commented
@nf-core-bot fix linting

2024-10-31 16:29 UTC, ramirobarrantes commented
@nf-core-bot fix linting

2024-10-31 18:05 UTC, ramirobarrantes commented
@nf-core-bot fix linting

2024-11-01 14:03 UTC, itrujnara requested changes
Thanks for addressing some of the comments. There are still some issues in the meta.yml. I have also suggested splitting the two modules into separate PRs for convenience.

2024-11-01 14:03 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +        description: Name of the reference genome index
Change this back, I meant the indexfasta description. Meta description is standardized.

2024-11-01 14:03 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +        description: Fasta file(s) ending in [.fasta, .fna, .fa]
Same thing again

2024-11-01 14:03 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +          description: name of the reference genome index
As above, don't change the meta description

2024-11-01 14:03 UTC, itrujnara commented on modules/nf-core/coptr/index/meta.yml
> +            - edan: "http://edamontology.org/data_3210"
```suggestion
            - edam: "http://edamontology.org/data_3210"
```

2024-11-01 14:03 UTC, itrujnara commented on modules/nf-core/coptr/map/main.nf
> +process COPTR_MAP {
Can you please move all coptr/map code to a different PR and ping me there? Will be easier for me to review

2024-11-01 20:39 UTC, ramirobarrantes commented
@nf-core-bot fix linting

2024-11-04 09:26 UTC, itrujnara approved these changes
Nice job! Good to go on this one. Please let me know when you create the other PR.

2024-11-04 09:32 UTC, merged