Diamond
nf-core/modules pull request #710
Opened 2021-09-16 01:34 UTC by spficklin

This PR adds the Diamond tool (https://github.com/bbuchfink/diamond) which is an accelerated replacement for blast as a brand new module.   Publishd here:  https://www.nature.com/articles/s41592-021-01101-x  

To generate this module I followed the instructions (can't guarantee I didn't make a mistake), compared it to the existing blast modules for comparison  as it runs very similarly and all tests are working.  

I'm hoping to use this module for a functional annotation workflow I'm helping construct.

## PR checklist

- [X] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [X] Remove all TODO statements.
- [X] Emit the `<SOFTWARE>.version.txt` file.
- [X] Follow the naming conventions.
- [X] Follow the parameters requirements.
- [X] Follow the input/output options guidelines.
- [X] Add a resource `label`
- [X] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [X] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [X] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [X] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-09-21 19:13 UTC, drpatelh commented on modules/diamond/blastp/main.nf
> +    path '*.version.txt', emit: version
```suggestion
    tuple val(meta), path('*.txt'), emit: txt
    path '*.version.txt'          , emit: version
```

2021-09-21 19:13 UTC, drpatelh commented on modules/diamond/blastp/main.nf
> +
```suggestion
```

2021-09-21 19:14 UTC, drpatelh commented on modules/diamond/blastp/main.nf
> +        --threads $task.cpus \\
```suggestion

    diamond \\
        blastp \\
        --threads $task.cpus \\
```

2021-09-21 19:14 UTC, drpatelh commented on modules/diamond/blastp/main.nf
> +    echo \$(diamond --version 2>&1) | tail -n 1 | sed 's/^diamond version //' > ${software}.version.txt
```suggestion
        --out ${prefix}.txt

    echo \$(diamond --version 2>&1) | tail -n 1 | sed 's/^diamond version //' > ${software}.version.txt
```

2021-09-21 19:15 UTC, drpatelh commented on modules/diamond/blastp/meta.yml
> +    type: file
Indents are off in this section.

2021-09-21 19:16 UTC, drpatelh commented on modules/diamond/blastx/main.nf
> +options    = initOptions(params.options)
```suggestion
params.options = [:]
options        = initOptions(params.options)
```

2021-09-21 19:17 UTC, drpatelh commented on modules/diamond/blastx/main.nf
> +        --out ${prefix}.diamond_blastx.txt
```suggestion
        --out ${prefix}.txt

```

2021-09-21 19:18 UTC, drpatelh commented on modules/diamond/makedb/main.nf
> +    diamond makedb \\
```suggestion
    diamond \\
        makedb \\
```

2021-09-21 19:18 UTC, drpatelh commented on modules/diamond/makedb/main.nf
> +    echo \$(diamond --version 2>&1) | tail -n 1 | sed 's/^diamond version //' > ${software}.version.txt
```suggestion

    echo \$(diamond --version 2>&1) | tail -n 1 | sed 's/^diamond version //' > ${software}.version.txt
```

2021-09-21 19:19 UTC, drpatelh commented on tests/modules/diamond/blastp/main.nf
> +    DIAMOND_BLASTP( [ [id:'test'], fasta ], DIAMOND_MAKEDB.out.db )
```suggestion
    DIAMOND_BLASTP ( [ [id:'test'], fasta ], DIAMOND_MAKEDB.out.db )
```

2021-09-21 19:19 UTC, drpatelh commented on tests/modules/diamond/blastx/main.nf
> +    DIAMOND_BLASTX( [ [id:'test'], fasta ], DIAMOND_MAKEDB.out.db )
```suggestion
    DIAMOND_BLASTX ( [ [id:'test'], fasta ], DIAMOND_MAKEDB.out.db )
```

2021-09-21 19:23 UTC, drpatelh commented on tests/modules/diamond/blastx/main.nf
> +include { DIAMOND_BLASTX } from '../../../../modules/diamond/blastx/main.nf' addParams( options: [:] )
```suggestion
include { DIAMOND_MAKEDB } from '../../../../modules/diamond/makedb/main.nf' addParams( options: [:]                           )
include { DIAMOND_BLASTX } from '../../../../modules/diamond/blastx/main.nf' addParams( options: [ suffix: '.diamond_blastx' ] )
```

2021-09-21 19:23 UTC, drpatelh commented on tests/modules/diamond/blastp/main.nf
> +include { DIAMOND_BLASTP } from '../../../../modules/diamond/blastp/main.nf' addParams( options: [:] )
```suggestion
include { DIAMOND_MAKEDB } from '../../../../modules/diamond/makedb/main.nf' addParams( options: [:]                           )
include { DIAMOND_BLASTP } from '../../../../modules/diamond/blastp/main.nf' addParams( options: [ suffix: '.diamond_blastp' ] )
```

2021-09-21 19:26 UTC, drpatelh requested changes
Hi @spficklin ! Thanks for adding these modules! Was going to ask if you could split this PR into one module per PR but I reviewed here anyway so maybe one for next time :) Looks great overall just a few minor changes. I don't have permissions to push to your org otherwise I would have tried to get it in.

2021-09-22 08:11 UTC, drpatelh commented on modules/diamond/blastp/meta.yml
> +    pattern: "*.{version.txt}"
```suggestion
        pattern: "*"

output:
  - txt:
        type: file
        description: File containing blastp hits
        pattern: "*.{blastp.txt}"
  - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
```

2021-09-22 17:55 UTC, spficklin commented
Thanks @drpatelh for the suggested changes!  I've merged them into the PR.  I will be aware next time separate out the modules into separate PRs even if they are for the same tool.  

I think I've merged in all your suggested changes I'm happy to make more changes if there's anything else or I missed something.

2021-09-23 08:12 UTC, drpatelh approved these changes

2021-09-23 08:12 UTC, drpatelh commented
No this is 👌🏽 Thank you :)

2021-09-23 08:13 UTC, merged

2021-09-23 18:40 UTC, spficklin commented
This was my first module submission and the process was great! Thank you.