Add sylph/profile module
nf-core/modules pull request #7118
Opened 2024-11-28 14:48 UTC by sofstam

## PR checklist

Moves the local module `sylph/profile` to nf-core modules. Closes https://github.com/nf-core/seqinspector/pull/65
Removes unnecessary pattern from `sylph/sketch` meta file.

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-12-05 14:17 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/meta.yml
> +            e.g. [ id:'test', single_end:false ]
The description needs correcting

2024-12-05 14:17 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/meta.yml
> +  - - pre_sketched_files:
This says a Presketched db, but your test input supplies a fasta file.

2024-12-11 13:00 UTC, famosab requested changes
Suggested to be a bit more specific about the created csv :)

2024-12-11 13:00 UTC, famosab commented on modules/nf-core/sylph/profile/main.nf
> +
```suggestion
```

2024-12-11 13:00 UTC, famosab commented on modules/nf-core/sylph/profile/main.nf
> +
```suggestion
```

2024-12-11 13:00 UTC, famosab commented on modules/nf-core/sylph/profile/main.nf
> +    def args = task.ext.args ?: ''
```suggestion
```

2025-01-08 08:10 UTC, SPPearce commented
@sofstam , do you need a hand to get this finished off?

2025-01-08 10:52 UTC, sofstam commented
@SPPearce Was on holidays, looking at the comments now :)

2025-01-08 11:58 UTC, sofstam commented on modules/nf-core/sylph/profile/meta.yml
> +            e.g. [ id:'test', single_end:false ]
Corrected!

2025-01-08 12:01 UTC, sofstam commented on modules/nf-core/sylph/sketch/meta.yml
>              e.g. [ id:'test', single_end:false ]
Removed it, do you have any suggestion on that one?

2025-01-08 14:51 UTC, sofstam commented on modules/nf-core/sylph/profile/meta.yml
> +  - - pre_sketched_files:
The documentation says:

`Pre-sketched *.syldb/*.sylsp files. Raw single-end fastq/fasta are allowed and will be automatically sketched to .sylsp/.syldb. `

That is why I supplied a fasta file. Updated the `meta.yml` file with this info too.

2025-01-08 15:02 UTC, sofstam commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                    process.out.profile_out.collect { file(it[1]).readLines().contains("complete genome") },
Do you mean to count the columns of the output file?

2025-01-09 08:50 UTC, famosab commented on modules/nf-core/sylph/sketch/meta.yml
>              e.g. [ id:'test', single_end:false ]
you can probably leave it as is, but if there is something that is nice to store in the map you can add it as example

2025-01-09 08:52 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                    process.out.profile_out.collect { file(it[1]).readLines().contains("complete genome") },
anything that makes sense - counting columns or asserting column header both seems fine to me

2025-01-09 09:46 UTC, sofstam commented on modules/nf-core/sylph/sketch/meta.yml
>              e.g. [ id:'test', single_end:false ]
Will leave it as it is.

2025-01-16 15:29 UTC, sofstam commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                    process.out.profile_out.collect { file(it[1]).readLines().contains("complete genome") },
Updated this now.

2025-01-16 20:22 UTC, SPPearce commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                            [ file(params.test_data['sarscov2']['illumina']['test_1_fastq_gz'], checkIfExists: true) ]
Can you swap these to the more recent file paths please

2025-01-16 20:22 UTC, SPPearce commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert snapshot(process.out.versions).match("versions_paired") },
```suggestion
                { assert snapshot(process.out.versions).match("") },
```

2025-01-16 20:27 UTC, SPPearce commented
One of my comments may have been related to some previous code, can't see the comment on my phone

2025-01-17 08:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/main.nf
> +
```suggestion
```

2025-01-17 08:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/meta.yml
> +        pattern: "*.{syldb,sylsp}"
Update this pattern too.

2025-01-17 08:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/meta.yml
> +  - - pre_sketched_files:
I would suggest making this variable name more general given it could be fasta. Something like `database` ( since the manual uses the same term too ).

2025-01-17 08:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert output_content.size() > 1 }
Is there not a specific file or contents to test for here?

2025-01-21 15:43 UTC, sofstam commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                            [ file(params.test_data['sarscov2']['illumina']['test_1_fastq_gz'], checkIfExists: true) ]
I updated the file paths.

2025-01-21 15:53 UTC, sofstam commented on modules/nf-core/sylph/profile/meta.yml
> +  - - pre_sketched_files:
Updated it.

2025-01-21 15:53 UTC, sofstam commented on modules/nf-core/sylph/profile/meta.yml
> +        pattern: "*.{syldb,sylsp}"
Updated.

2025-01-22 09:00 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert output_content.size() > 1 }
Could you update this test so there's a specific file to test please?

2025-01-22 09:24 UTC, famosab reviewed
Just some questions about the assertions. Looks good to me otherwise :)

2025-01-22 09:24 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert snapshot(process.out).match("stub_output") }
```suggestion
                { assert snapshot(process.out).match() }
```

2025-01-22 09:24 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert process.out.profile_out.get(0).size() > 1 }
Is there a way to bring this assertion into the snapshot? Can we maybe assert the headers of the tsv or something similar?

2025-01-22 09:24 UTC, famosab commented on modules/nf-core/sylph/sketch/meta.yml
>              e.g. [ id:'test', single_end:false ]
```suggestion
            e.g. [ id:'test']
```

2025-01-22 09:25 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert process.out.profile_out.get(0).size() > 1 }
Maybe like @SPPearce suggested:
```groovy
                { assert snapshot(
                    process.out.versions,
                    file(output_content).readLines()[0..4]
                    ).match() }
 ```

2025-01-23 13:19 UTC, sofstam commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert process.out.profile_out.get(0).size() > 1 }
I update this now.

2025-01-24 09:58 UTC, famosab commented
Seems like on singularity the output differs for some reason:
```bash

  Test [4a19ff37] 'sarscov2 illumina paired-end [fastq_gz]' 
    > Nextflow 24.10.4 is available - Please consider updating your version to it
    > N E X T F L O W  ~  version 24.10.2
    > Launching `/opt/actions-runner/_work/modules/modules/.nf-test-4a19ff3737b98fffc0939e2c3241fe8c.nf` [extravagant_einstein] DSL2 - revision: bc66d7e8e0
    > Pulling Singularity image https://depot.galaxyproject.org/singularity/sylph:0.7.0--h919a2d8_0 [cache /opt/actions-runner/_work/modules/modules/.singularity/depot.galaxyproject.org-singularity-sylph-0.7.0--h919a2d8_0.img]
    > [2b/7c3d37] Submitted process > SYLPH_PROFILE (test)
    FAILED (18.656s)

  java.lang.RuntimeException: Different Snapshot:
  [													[
      [													    [
          "versions.yml:md5,7b5a545483277cc0ff9189f8891e737f"						        "versions.yml:md5,7b5a545483277cc0ff9189f8891e737f"
      ],													    ],
      [													    [
          "Sample_file\tGenome_file\tTaxonomic_abundance\tSequence_abundance\tAdjusted_ANI\tEff_co	        "Sample_file\tGenome_file\tTaxonomic_abundance\tSequence_abundance\tAdjusted_ANI\tEff_co
          "test_2.fastq.gz\tgenome.fasta\t100.0000\t100.0000\t98.71\t0.444\t96.68-101.00\t0.444\t0   |	        "test_1.fastq.gz\tgenome.fasta\t100.0000\t100.0000\t99.86\t0.250\tNA-NA\t0.250\tNA-NA\t1
      ]													    ]
  ]	
  ```

2025-01-24 10:02 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                    file(process.out.profile_out[0][1]).readLines()[0..1]
maybe this would be enough
```suggestion
                    file(process.out.profile_out[0][1]).readLines()[0]
```

2025-01-24 10:02 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                    file(process.out.profile_out[0][1]).readLines()[0..1]
```suggestion
                    file(process.out.profile_out[0][1]).readLines()[0]
```

2025-01-24 12:46 UTC, sofstam commented
@famosab The tests are passing now

2025-01-24 12:47 UTC, sofstam commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +                { assert output_content.size() > 1 }
I updated the tests

2025-01-24 13:05 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/main.nf
> +    sylph profile \\
You're missing `--threads`

2025-01-24 13:28 UTC, sofstam commented on modules/nf-core/sylph/profile/main.nf
> +    sylph profile \\
Added it now.

2025-01-24 13:46 UTC, famosab reviewed
Looks good, was just wondering why you removed the `{ assert process.success },` statements from the nf-test. I would add it back in and then approve this :)

2025-01-24 13:46 UTC, famosab commented on modules/nf-core/sylph/profile/main.nf
> +          -o ${prefix}.tsv
Nitpick: can you align the commands nicely? 🙈

2025-01-24 13:46 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +        }
```suggestion
        then {
               { assert process.success },
               { assert snapshot(
                    process.out.versions,
                    file(process.out.profile_out[0][1]).readLines()[0]
                    ).match() }
        }
```

2025-01-24 13:46 UTC, famosab commented on modules/nf-core/sylph/profile/tests/main.nf.test
> +        }
```suggestion
        then {
            { assert process.success },
            { assert snapshot(
                    process.out.versions,
                    file(process.out.profile_out[0][1]).readLines()[0]
                    ).match() }
        }
```

2025-01-24 13:46 UTC, famosab commented on modules/nf-core/sylph/profile/main.nf
> +    def args = task.ext.args ?: ''
This can be removed for now as suggested :)

2025-01-24 13:47 UTC, mahesh-panchal approved these changes
Few small things still, but otherwise fine by me
The options should also be `--` format, but `-t` doesn't have one it seems.

2025-01-24 13:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/main.nf
> +          -o ${prefix}.tsv
```suggestion
    sylph profile \\
        -t $task.cpus \\
        $args \\
        $reads \\
        $database\\
        -o ${prefix}.tsv
```

2025-01-24 13:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/main.nf
> +        sylph: \$(sylph -V|awk '{print \$2}')
```suggestion
        sylph: \$(sylph -V | awk '{print \$2}')
```

2025-01-24 13:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/main.nf
> +        sylph: \$(sylph -V|awk '{print \$2}')
```suggestion
        sylph: \$(sylph -V | awk '{print \$2}')
```

2025-01-24 13:47 UTC, mahesh-panchal commented on modules/nf-core/sylph/profile/meta.yml
> +          type: map
```suggestion
          type: file
```

2025-01-24 13:49 UTC, sofstam commented on modules/nf-core/sylph/profile/main.nf
> +          -o ${prefix}.tsv
Oops yes, @mahesh-panchal just commited those changes.

2025-01-28 19:54 UTC, SPPearce commented
@mashehu , do you want the change to the `get-shards` action to be merged in?

2025-01-29 00:55 UTC, famosab approved these changes
LGTM 🚀

2025-01-29 09:05 UTC, sofstam commented
@SPPearce I will wait with merging then.

2025-01-30 10:00 UTC, merged