Add module custom_tabulargseatochip
nf-core/modules pull request #7218
Opened 2024-12-13 14:13 UTC by suzannejin

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-12-16 16:08 UTC, pinin4fjords requested changes
Looking pretty good, thanks for the work, just a couple of minor things. Files are always supposed to have metas in the modules repo.

Not sure why this wasn't migrated before.

2024-12-16 16:08 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/main.nf
> +    path tabular
```suggestion
    tuple val(meta), path(tabular)
```

2024-12-16 16:08 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/meta.yml
> +  - - tabular:
Also meta here

2024-12-16 16:08 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/meta.yml
> +      description: "Make a GSEA class file (.chip) from tabular inputs"
```suggestion
      description: "Make a GSEA annotation file (.chip) from tabular inputs"
```

2024-12-17 09:26 UTC, pinin4fjords commented
> @pinin4fjords Thank you for the review! Just one more question about the versioning... I copied it from the local version so I am not sure why VERSION=9.1?

Fair question, for which I don't remember the answer. But since we're using the gawk container, maybe you should just do what the gawk container does instead: https://github.com/nf-core/modules/blob/master/modules/nf-core/gawk/main.nf

2024-12-17 12:49 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/main.nf
> +    def VERSION = '9.1' // WARN: Version information not provided by tool on CLI. Please update this string when bumping container versions.
You can strip this now

2024-12-17 12:49 UTC, pinin4fjords reviewed
Almost there would you mind adding a stub? Really easy for this one

2024-12-17 13:48 UTC, suzannejin commented
@pinin4fjords I have just added the stub :)

2024-12-18 08:17 UTC, pinin4fjords reviewed
Sorry, just remembered we should also have a prefix

2024-12-18 08:17 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/main.nf
> +    script:
```suggestion
    script:
    def prefix = task.ext.prefix ?: "${meta.id}"
```
Sorry, forgot that we should actually do the outputs this way

2024-12-18 08:17 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/main.nf
> +    outfile=\$(echo $tabular | sed 's/\\(.*\\)\\..*/\\1/').chip
```suggestion
    outfile=${prefix}.chip
```

2024-12-18 08:17 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/main.nf
> +    outfile=\$(echo $tabular | sed 's/\\(.*\\)\\..*/\\1/').chip
```suggestion
    outfile=${prefix}.chip
```

2024-12-18 08:18 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/tests/main.nf.test.snap
> +                        "id": "test"
```suggestion
                        "id": "SRP254919.salmon.merged.gene_counts.top1000cov"
```

2024-12-18 08:18 UTC, pinin4fjords commented on modules/nf-core/custom/tabulartogseachip/tests/main.nf.test.snap
> +                        "id": "test"
```suggestion
                        "id": "SRP254919.salmon.merged.gene_counts.top1000cov"
```

2024-12-18 12:02 UTC, pinin4fjords approved these changes
Looks good, thanks!

2024-12-18 12:07 UTC, merged