try porting to nf-test
nf-core/modules pull request #7231
Opened 2024-12-17 07:17 UTC by famosab

## PR checklist

Closes #XXX 
Related to #7211 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

I tried porting but I always run into the following error:
```bash
│                                                                                                                                                                                                                                                                                                                                                                        │
│   Assertion failed:                                                                                                                                                                                                                                                                                                                                                    │
│                                                                                                                                                                                                                                                                                                                                                                        │
│   2 of 2 assertions failed                                                                                                                                                                                                                                                                                                                                             │
│                                                                                                                                                                                                                                                                                                                                                                        │
│   Nextflow stdout:                                                                                                                                                                                                                                                                                                                                                     │
│                                                                                                                                                                                                                                                                                                                                                                        │
│   ERROR ~ Script compilation error                                                                                                                                                                                                                                                                                                                                     │
│   - file : /Users/famke/02-nf-core/modules/.nf-test-1f5468570864d0273649d793a99b787b.nf                                                                                                                                                                                                                                                                                │
│   - cause: The LHS of an assignment should be a variable or a field accessing expression @ line 56, column 22.                                                                                                                                                                                                                                                         │
│                      input[0] = MMSEQS_CREATEDB_QUERY.out.db,                                                                                                                                                                                                                                                                                                          │
│                           ^                                                                                                                                                                                                                                                                                                                                            │
│                                                                                                                                                                                                                                                                                                                                                                        │
│   1 error                                                                                                                                                                                                                                                                                                                                                              │
│                                                                                                                                                                                                                                                                                                                                                                        │
│                                                                                                                                                                                                                                                                                                                                                                        │
│    -- Check '/Users/famke/02-nf-core/modules/.nf-test/tests/1f5468570864d0273649d793a99b787b/meta/nextflow.log' file for details                                                                                                                                                                                                                                       │
│   Nextflow stderr:  
```

2024-12-19 10:30 UTC, prototaxites requested changes
Hopefully this will make the tests run!

2024-12-19 12:59 UTC, famosab commented
Now I still get:
```bash
│   Test [1f546857] 'sarscov2 - test-search' FAILED (6.297s)                                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                              │
│   Assertion failed:                                                                                                                                                                                                                                          │
│                                                                                                                                                                                                                                                              │
│   2 of 2 assertions failed                                                                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                              │
│   Nextflow stdout:                                                                                                                                                                                                                                           │
│                                                                                                                                                                                                                                                              │
│   ERROR ~ Error executing process > 'MMSEQS_CREATEDB_QUERY (test_query)'                                                                                                                                                                                     │
│                                                                                                                                                                                                                                                              │
│   Caused by:                                                                                                                                                                                                                                                 │
│     Process `MMSEQS_CREATEDB_QUERY (test_query)` terminated with an error exit status (132)                                                                                                                                                                  │
│                                                                                                                                                                                                                                                              │
│                                                                                                                                                                                                                                                              │
│   Command executed:                                                                                                                                                                                                                                          │
│                                                                                                                                                                                                                                                              │
│     if [ "false" == "true" ]; then                                                                                                                                                                                                                           │
│         gzip -c -d contigs.fasta > contigs.fasta                                                                                                                                                                                                             │
│     fi                                                                                                                                                                                                                                                       │
│                                                                                                                                                                                                                                                              │
│     mkdir -p test_query                                                                                                                                                                                                                                      │
│                                                                                                                                                                                                                                                              │
│     mmseqs \                                                                                                                                                                                                                                                 │
│         createdb \                                                                                                                                                                                                                                           │
│         contigs.fasta \                                                                                                                                                                                                                                      │
│         test_query/test_query \                                                                                                                                                                                                                              │
│          \                                                                                                                                                                                                                                                   │
│         --compressed 1                                                                                                                                                                                                                                       │
│                                                                                                                                                                                                                                                              │
│     cat <<-END_VERSIONS > versions.yml                                                                                                                                                                                                                       │
│     "MMSEQS_CREATEDB_QUERY":                                                                                                                                                                                                                                 │
│        [...]

2025-01-15 08:35 UTC, jfy133 commented
@famosab I think I will take some of your initial work here into the removing teh compress module PR from Jasmin, as I guess the snapshot might change due to the removal of teh compression

2025-01-15 09:30 UTC, famosab commented
Just close it if its obsolete :)

2025-01-15 09:49 UTC, SPPearce commented
I was finishing this off here before James started so I finished it off (letting him know).
This PR should be good to merge if the checks pass, I included removing the compression.

2025-01-15 09:54 UTC, jfy133 approved these changes
I don't see anything problematic, maybe just a comment why just checking for file names

2025-01-15 10:02 UTC, SPPearce commented on modules/nf-core/mmseqs/search/tests/main.nf.test
> +                    file(process.out.db_search.get(0).get(1)).list().sort(), //second file is empty so fails linting
@jfy133 , you mean like this comment ;)

2025-01-15 11:20 UTC, jfy133 commented on modules/nf-core/mmseqs/search/tests/main.nf.test
> +                    file(process.out.db_search.get(0).get(1)).list().sort(), //second file is empty so fails linting
YEs :grimacing:

2025-01-15 12:56 UTC, jfy133 commented
@SPPearce I'm going to force merge this as your tests are passing but easysearch is fixed in the other PR

2025-01-15 12:56 UTC, merged