Update Prokka to take compressed input && tidy module script
nf-core/modules pull request #7250
Opened 2024-12-19 09:57 UTC by prototaxites

Also bump container to latest biocontainer build

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [x] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-12-19 10:19 UTC, prototaxites commented
Undoing container build bump - there's some kind of java version error with minced that I'm getting when running with Singularity on our HPC (but not on Gitpod).

2024-12-20 10:15 UTC, prototaxites commented
The minced binary is built with Java version 8 - I've switched the container to a Sequera container with the correct OpenJDK version pinned, and updated the Conda environment to match. 

Testing seems to have fixed the problem on our cluster; hopefully will fix this intermittently reported issue in mag too: https://github.com/nf-core/mag/issues/552

2025-01-03 10:30 UTC, dialvarezs requested changes
Hi Jim,

Supporting gzipped input is a nice adittion to have. And thank you for looking into the issues when running Prokka, because sometimes becomes mysteriously unreliable for some reason.

Aside from the minor changes I proposed, if you have time, can you please add the stub and the stub test?

Thank you.

2025-01-03 10:30 UTC, dialvarezs commented on modules/nf-core/prokka/main.nf
> +        'oras://community.wave.seqera.io/library/prokka_openjdk:6ee087933c41335a' :
For singularity images, I've seen in the discussions that is prefered to use the https link instead of the oras one.

2025-01-03 10:30 UTC, dialvarezs commented on modules/nf-core/prokka/main.nf
> +    def fasta_compressed = fasta.getExtension() == "gz" ? true : false
`? true : false` seems redundant. Was there a specific reason for implementing it this way?

2025-01-03 10:30 UTC, dialvarezs commented on modules/nf-core/prokka/main.nf
> +    def input            = fasta_compressed ? fasta.toString() - ~/\.gz$/ : fasta
I guess this could be simplified  too, because if the filename doesn't end with `.gz` the pattern should not remove anything anyway.

2025-01-06 10:51 UTC, prototaxites commented on modules/nf-core/prokka/main.nf
> +        'oras://community.wave.seqera.io/library/prokka_openjdk:6ee087933c41335a' :
I'm going to leave this as-is for now, as I'm not sure how to get an https URL - will fix when I have a bit more time to dig!

2025-01-06 10:52 UTC, prototaxites commented on modules/nf-core/prokka/main.nf
> +    def fasta_compressed = fasta.getExtension() == "gz" ? true : false
I think while I was prototyping I had some lines that were very long - but I've tidied this up now,

2025-01-06 10:54 UTC, prototaxites commented
Added stub & corresponding test.

If anyone knows how to convert the oras:// identifier to https://, please let me know!

2025-01-06 11:17 UTC, dialvarezs commented on modules/nf-core/prokka/main.nf
> +        'oras://community.wave.seqera.io/library/prokka_openjdk:6ee087933c41335a' :
There is a checkbox when creating the container
![image](https://github.com/user-attachments/assets/c8588a99-0bfc-4119-a031-9aabba17e72a)

2025-01-06 12:02 UTC, prototaxites commented on modules/nf-core/prokka/main.nf
> +        'oras://community.wave.seqera.io/library/prokka_openjdk:6ee087933c41335a' :
Should be sorted...!

2025-01-06 12:06 UTC, dialvarezs approved these changes
Great, it's ready to merge then!

2025-01-08 09:48 UTC, prototaxites commented
Many thanks!

2025-01-08 09:49 UTC, merged