ADD CATPACK_DOWNLOAD
nf-core/modules pull request #7253
Opened 2024-12-19 14:00 UTC by jfy133

A real test is not possible because they download >10GBs databases (NCBI Nr or GTDB)

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-12-19 15:08 UTC, jasmezz requested changes
You want a review already, right? (Not sure because wrong channel)
Snapshots not passing yet :eyes:

2024-12-19 15:08 UTC, jasmezz commented on modules/nf-core/catpack/download/meta.yml
> +            - edam: "http://edamontology.org/format_1049"
This link is broken

2024-12-19 15:08 UTC, jasmezz commented on modules/nf-core/catpack/download/meta.yml
> +description: write your description here
Add description

2024-12-19 15:08 UTC, jasmezz commented on modules/nf-core/catpack/download/tests/main.nf.test
> +
```suggestion
```

2024-12-19 15:08 UTC, jasmezz commented on modules/nf-core/catpack/download/tests/main.nf.test
> +
Maybe add a comment why only stub test?

2024-12-19 15:21 UTC, jfy133 commented on modules/nf-core/catpack/download/meta.yml
> +            - edam: "http://edamontology.org/format_1049"
Done

2024-12-19 15:21 UTC, jfy133 commented on modules/nf-core/catpack/download/meta.yml
> +description: write your description here
Done

2024-12-19 15:21 UTC, jfy133 commented on modules/nf-core/catpack/download/tests/main.nf.test
> +
Done

2025-01-14 13:18 UTC, jfy133 commented on modules/nf-core/catpack/download/meta.yml
> +            - edam: "http://edamontology.org/data_1049"
```suggestion
            - edam: "http://edamontology.org/data_1049"
```

2025-01-14 13:20 UTC, jfy133 commented on modules/nf-core/coptr/estimate/meta.yml
> +            - edam: "http://edamontology.org/data_3752"
I forgot to switch the number ID :sweat_smile:

2025-01-14 13:50 UTC, nvnieuwk commented on modules/nf-core/catpack/download/main.nf
> +    tuple val(meta), path("${db}/"), emit: rawdb
```suggestion
    tuple val(meta), path("${prefix}/"), emit: rawdb
```

Shouldn't this be the prefix?

2025-01-14 13:51 UTC, nvnieuwk reviewed
One small thing, otherwise LGTM (I'll approve when that thing has been looked at :))

2025-01-14 13:59 UTC, jasmezz approved these changes
Please just update the broken link, otherwise LGTM!

2025-01-14 13:59 UTC, jasmezz commented on modules/nf-core/coptr/estimate/meta.yml
> +            - edam: "http://edamontology.org/data_3752"
Still need to update this link ;)

2025-01-14 14:10 UTC, jfy133 commented
> Please just update the broken link, otherwise LGTM!

What the poop?! I did fix it! Well have to look again...

2025-01-15 07:55 UTC, jfy133 commented
Fixed the thing @nvnieuwk I'll merge once tests pass!

@jasmezz I did update the link -> there is not 'format' for directory so I use `data_1049` as this is called 'directory name' which is teh closest I could find.

The original link didn't work as I forgot to up the number ID part

2025-01-15 08:18 UTC, nvnieuwk approved these changes
Tests will probably fail otherwise

2025-01-15 08:18 UTC, nvnieuwk commented on modules/nf-core/catpack/download/main.nf
> +    def prefix = task.ext.prefix ?: "${meta.id}"
```suggestion
    prefix = task.ext.prefix ?: "${meta.id}"
```

2025-01-15 08:18 UTC, nvnieuwk commented on modules/nf-core/catpack/download/main.nf
> +    def prefix = task.ext.prefix ?: "${meta.id}"
```suggestion
    prefix = task.ext.prefix ?: "${meta.id}"
```

2025-01-15 08:59 UTC, jasmezz commented
Ok I am fine with it if you are fine with it @jfy133 – I don't fully understand but the number ID wasn't updated in line [45](https://github.com/nf-core/modules/pull/7253/files#diff-87876bb17b3892e750ca168379f02deda1fafda44a16e48a00de5d425523db8bR45), it still links to http://edamontology.org/data_3752 which doesn't exist?

2025-01-15 09:07 UTC, jfy133 commented on modules/nf-core/coptr/estimate/meta.yml
> +            - edam: "http://edamontology.org/data_3752"
```suggestion
            - edam: "http://edamontology.org/format_3752"
```

2025-01-15 09:08 UTC, jfy133 commented
> Ok I am fine with it if you are fine with it @jfy133 – I don't fully understand but the number ID wasn't updated in line [45](https://github.com/nf-core/modules/pull/7253/files#diff-87876bb17b3892e750ca168379f02deda1fafda44a16e48a00de5d425523db8bR45), it still links to http://edamontology.org/data_3752 which doesn't exist?

I updated the wrong line :face_exhaling:

2025-01-15 11:15 UTC, merged