modify custom/filterdifferentialtable to allow >=/<=
nf-core/modules pull request #7258
Opened 2024-12-20 17:44 UTC by suzannejin

This modification allows setting ">=" or "<=" comparisons through ext.args

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [x] `nf-core modules test <MODULE> --profile docker`
    - [x] `nf-core modules test <MODULE> --profile singularity`
    - [x] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [x] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2025-01-08 11:34 UTC, pinin4fjords requested changes
The interface is a little confusing here. But in any case, you're effectively making the cardinality a required input here, which means it should go in through a channel.

I suggest we change the inputs from:

```    
    tuple val(meta), path(input_file)
    val(logFC_column)
    val(FC_threshold)
    val(padj_column)
    val(padj_threshold)
```

To:

```
    tuple val(meta), path(input_file)
    val(logFC_column)
    val(FC_threshold)
    val(FC_cardinality)
    val(padj_column)
    val(padj_threshold)
    val(padj_cardinality)
```

(removing the args thing altogether)

OR, maybe we also want to bundle these like:

```
    tuple val(meta), path(input_file)
    tuple val(logFC_column), val(FC_threshold), val(FC_cardinality)
    tuple val(padj_column), val(padj_threshold), val(padj_cardinality)
```

There should then be a check for a valid cardinality ('-', '<', '>', '<=', or '>=').

2025-01-09 15:59 UTC, suzannejin commented
@pinin4fjords Hello!! Thank you for the suggestions! Now the cardinal comparison operators are explicitly given as input :)

2025-01-10 11:02 UTC, pinin4fjords commented on subworkflows/nf-core/abundance_differential_filter/main.nf
> +                'propd' : [fc_column: 'lfc', fc_cardinality: '>=', padj_column: 'weighted_connectivity', padj_cardinality: '>=']
Is it intentional to have '>=' for the propd padj cardinality?

2025-01-10 11:05 UTC, pinin4fjords commented on subworkflows/nf-core/abundance_differential_filter/tests/main.nf.test.snap
> +                        "padj_threshold": 100
I should have asked this before- but why isn't the p value threshold something less than 1?

2025-01-10 11:07 UTC, suzannejin commented on subworkflows/nf-core/abundance_differential_filter/main.nf
> +                'propd' : [fc_column: 'lfc', fc_cardinality: '>=', padj_column: 'weighted_connectivity', padj_cardinality: '>=']
yes, because we use a different estimate that is not p-value
Maybe we should call stat_column instead of padj_column? There are also some other DE methods that don't use p-value, isn't it.

2025-01-10 11:42 UTC, pinin4fjords commented on subworkflows/nf-core/abundance_differential_filter/tests/main.nf.test.snap
> +                        "padj_threshold": 100
OK, now I understand that this isn't a p value at all. Can we maybe leave it at the same value though, so we know the md5sum isn't affected by the code change?

2025-01-10 11:43 UTC, pinin4fjords commented on subworkflows/nf-core/abundance_differential_filter/main.nf
> +                'propd' : [fc_column: 'lfc', fc_cardinality: '>=', padj_column: 'weighted_connectivity', padj_cardinality: '>=']
Yes, that sounds sensible, or others will be as confused as me ;-)

2025-01-10 14:20 UTC, suzannejin commented on subworkflows/nf-core/abundance_differential_filter/tests/main.nf.test.snap
> +                        "padj_threshold": 100
since the operator is ">=" instead of "<=" now (as it should be for weighted connectivity), it will not keep the same md5sum anyway even keeping threshold = 50

2025-01-10 17:01 UTC, pinin4fjords commented on subworkflows/nf-core/abundance_differential_filter/tests/main.nf.test.snap
> +                        "padj_threshold": 100
Ahh, gotcha

2025-01-10 17:02 UTC, pinin4fjords approved these changes
Looking good, thanks for addressing feedback

2025-01-10 17:19 UTC, merged