Add new module `decoupler/progeny`
nf-core/modules pull request #7263
Opened 2024-12-26 13:47 UTC by atrigila

https://github.com/nf-core/differentialabundance/issues/350

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - For modules:
    - [ ] `nf-core modules test <MODULE> --profile docker`
    - [ ] `nf-core modules test <MODULE> --profile singularity`
    - [ ] `nf-core modules test <MODULE> --profile conda`
  - For subworkflows:
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile docker`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile singularity`
    - [ ] `nf-core subworkflows test <SUBWORKFLOW> --profile conda`

2024-12-26 17:24 UTC, atrigila commented
Issues:
- omnipath is not being detected in singularity container. 
- docker: `cannot touch '.command.trace': Permission denied`

2024-12-31 14:00 UTC, atrigila commented
If we want to use the R bioconductor package, it also has compatibility problems with the available decoupler and omnipath versions (https://wave.seqera.io/view/builds/bd-d3c1e824e13fcf24_2)

2025-02-21 10:19 UTC, maxulysse commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
I'm a bit unsure about this part

2025-02-24 11:19 UTC, matthdsm commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Don't really see an issue here. Very similar to what we need to do to get [gatk](https://github.com/nf-core/modules/blob/master/modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf#L36) to work

2025-02-24 11:20 UTC, matthdsm commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
or any other module that has an option to set a TMP_DIR

2025-02-24 11:35 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Don't forget `input:` can also be type `env`. This could be a single tuple of `env` values 
```nextflow
workflow {
    TASK(['$PWD','./tmp']).view()
}

process TASK {
    input:
    tuple env('TASK_HOME'), env('TMP_DIR')

    script:
    """
    echo "TASK_HOME=\$TASK_HOME"
    echo "TMP_DIR=\$TMP_DIR"
    """

    output:
    stdout
}
```

2025-02-24 11:39 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Another option is to have a config file that you source with a single command to set the environment variables

2025-02-25 11:48 UTC, atrigila commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Here are some other examples using the same approach:
https://github.com/nf-core/modules/blob/4d95826db394fc94c9e9ea11170bbe19e0d849ca/modules/nf-core/doubletdetection/templates/doubletdetection.py#L6-L7

https://github.com/nf-core/modules/blob/4d95826db394fc94c9e9ea11170bbe19e0d849ca/modules/nf-core/scimap/mcmicro/main.nf#L28-L29

https://github.com/nf-core/modules/blob/4d95826db394fc94c9e9ea11170bbe19e0d849ca/modules/nf-core/sourcepredict/main.nf#L28-L29

Would you all be agree with keeping it as-is? 

Additionally, I couldn't find any example in nf-core using the `env()` approach. I did attempt, but wasn't able to make it work. This is what I got when trying to use $PWD in the nf-test:
`groovy.lang.MissingPropertyException: No such property: PWD for class: com.askimed.nf.test.lang.process.ProcessContext`

2025-02-25 11:59 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Can you post what you did please that generated the error? My example above works, but this error seems something to do with nf-test, but I don't understand why there would be an issue there.

Also I'm mostly posting alternatives. At the end of the day, the code needs to be somewhere, and setting the variable in the script section is probably the most contained way. Using `env` for something static I think reduces readability/increases debug time since you need to switch between files. 

My vote is keep it in the script block.

2025-02-25 12:21 UTC, atrigila commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Yes, your example worked perfectly so I followed it and I tried to replicate it by adding this:
```
    input:
    tuple val(meta), path(mat)
    tuple env('HOME'), env('OMNIPATH_CACHE_DIR')
```
to the `main.nf` and then added to the `main.nf.test`:
```
                input[0] = [
                    [ id: 'test' ],
                    file("https://github.com/nf-core/test-datasets/raw/modules/data/genomics/homo_sapiens/scrnaseq/h5ad/pbmc3k.h5ad", checkIfExists: true),
                    ['$PWD','./tmp']]
                ]
```

In the script, I temporarily commented the:
```
    #os.environ["HOME"] = os.getcwd()
    #os.environ["OMNIPATH_CACHE_DIR"] = "./tmp"
```
and I got the above error when running the test.

2025-02-25 12:24 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
```
tuple env('HOME'), env('OMNIPATH_CACHE_DIR')
```
Is a second input channel so your test input should be:
```
input[0] = [
    [ id: 'test' ],
    file("https://github.com/nf-core/test-datasets/raw/modules/data/genomics/homo_sapiens/scrnaseq/h5ad/pbmc3k.h5ad", checkIfExists: true),
]
input[1] = ['$PWD','./tmp']
```

2025-02-25 12:30 UTC, atrigila commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
oops, sorry yes you are right. still got the same error though: `groovy.lang.MissingPropertyException: No such property: PWD for class: com.askimed.nf.test.lang.process.ProcessContext`

2025-02-25 12:31 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Try escaping the `$` since it's in a string
```
input[1] = ['\$PWD','./tmp']
```

2025-02-25 13:04 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Interesting. Now I'm curios why it didn't have the intended behaviour, but I don't want to waste your time.

2025-02-26 14:42 UTC, atrigila commented on modules/nf-core/decoupler/progeny/main.nf
> +    os.environ["NUMBA_CACHE_DIR"] = "./tmp"
Could anybody, if you all agree, give a review/approve and merge, then? Thank you :)

2025-02-28 11:53 UTC, mahesh-panchal requested changes
Can you update the meta.yml please, in particular the output descriptions.

2025-02-28 11:53 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/meta.yml
> +      - s:
What's this?

2025-02-28 11:53 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/meta.yml
> +            e.g. [ id:‘test’, single_end ]
Could you correct this please

2025-02-28 11:53 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/meta.yml
> +          pattern: "*estimate__decoupler.tsv"
This needs removing
```suggestion
```

2025-02-28 11:53 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/tests/nextflow.config
> +        ext.args = { """{"organism": "human", "top_genes": 1000}""" }
Could you supply these through the test, as described in the [guidelines](https://nf-co.re/docs/tutorials/tests_and_test_data/nf-test_writing_tests#nf-test-guidelines-for-a-simple-un-chained-module) please?

2025-02-28 15:11 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    def top_genes = args.top_genes ?: 1000
There are no guidelines on this. Does this come under the same realm as custom meta fields. i.e. should these be `input:` ?

2025-02-28 15:13 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/meta.yml
> +          pattern: "matrixplot_decoupler.png"
```suggestion
```

2025-02-28 15:13 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/meta.yml
> +          pattern: "figures/*violin.png"
```suggestion
```

2025-02-28 15:13 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/meta.yml
> +          pattern: "figures/*umap.png"
```suggestion
```

2025-02-28 15:28 UTC, atrigila commented on modules/nf-core/decoupler/progeny/main.nf
> +    def top_genes = args.top_genes ?: 1000
I did those as input in my first design :) but then I remembered this one: https://nf-co.re/docs/guidelines/components/modules#non-file-mandatory-command-arguments
and I changed it to `ext.args`.

2025-02-28 16:11 UTC, atrigila commented on modules/nf-core/decoupler/progeny/main.nf
> +    def top_genes = args.top_genes ?: 1000
(I prefer them as `input:`, though. It's a lot cleaner)

2025-03-03 09:05 UTC, pinin4fjords commented on modules/nf-core/decoupler/progeny/main.nf
> +    #!/usr/bin/env python3
Guidelines currently say that non-trivial scripts should be templates rather than inline code:

2025-03-03 09:09 UTC, mahesh-panchal commented on modules/nf-core/decoupler/progeny/main.nf
> +    #!/usr/bin/env python3
Oh, when did that get added?

2025-03-03 10:34 UTC, pinin4fjords commented on modules/nf-core/decoupler/progeny/main.nf
> +    #!/usr/bin/env python3
Not that long ago. There was some discussion...

2025-03-11 07:12 UTC, SPPearce commented
nf-core tools linting for pip should be addressed in the hackathon: https://github.com/nf-core/tools/issues/3461

2025-03-16 07:55 UTC, grst commented
Hi @atrigila, 

I suggest to reduce the scope of the module a bit and make it database-agnostic. I.e. a pure "decoupler" module that can work with any resource rather than only progeny. 

Instead of querying omnipath internally (`dc.get_progeny()`) I suggest the module takes a reference database as a long-form TSV data frame. In differentialabundance, this resource could then be obtained by making a call to the [omnipath web api](https://pypath.omnipathdb.org/webservice.html) or by providing a custom TSV file. 

Sorry, I should have probably stated that a bit earlier.

2025-03-17 18:52 UTC, atrigila commented
@grst 
Could you give me an example of how you obtain the same structure TSV of the progeny data with the web api call as is obtained via `dc.get_progeny()`? 
Thank you.

2025-03-18 07:40 UTC, grst commented
https://omnipathdb.org/annotations?databases=PROGENy

2025-03-19 18:54 UTC, atrigila commented
Test run locally OK but fail in CI.

2025-03-20 06:51 UTC, grst commented
seems like unstable snapshots? 

You could try to disable multithreading of the underlying linalg libraries (only for the tests), this sometimes helps getting stable results across systems: 

```
export MKL_NUM_THREADS="1"
export OPENBLAS_NUM_THREADS="1"
export OMP_NUM_THREADS="1"
export NUMBA_NUM_THREADS="1"
```

2025-03-21 07:00 UTC, SPPearce commented
Don't know if relevant here, but changes in numerical precision between systems happen so you end up with different values at the last few decimal places if not rounded.

2025-03-24 17:27 UTC, merged