Picard/collecthsmetrics
nf-core/modules pull request #927
Opened 2021-10-27 14:53 UTC by projectoriented

## PR checklist

Closes #793 
~~This PR needs the test-data from this PR (awaiting for review): https://github.com/nf-core/test-datasets/pull/359~~
- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag picard/collecthsmetrics --symlink --keep-workflow-wd`
    - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2021-11-08 10:46 UTC, projectoriented commented
Apologies for all the commit messages. I had to revert the version from `2.26.4` -> `2.26.2` due to conda issues below:

```
N E X T F L O W  ~  version 21.04.1
Launching `tests/modules/picard/collecthsmetrics/main.nf` [fervent_sanger] - revision: 7ececf13ed
[-        ] process > test_picard_collecthsmetrics:PICARD_COLLECTHSMETRICS -

[-        ] process > test_picard_collecthsmetrics:PICARD_COLLECTHSMETRICS -
Creating Conda env: bioconda::picard=2.26.4 [cache /home/mei.wu/tmp/pytest_workflow_dyq_gnsd/picard_collecthsmetrics_test_picard_collecthsmetrics/work/conda/env-2bd1fde7df90cefe945ae19f31c1dc35]

[-        ] process > test_picard_collecthsmetrics:PICARD_COLLECTHSMETRICS -

Error executing process > 'test_picard_collecthsmetrics:PICARD_COLLECTHSMETRICS (test)'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /home/mei.wu/tmp/pytest_workflow_dyq_gnsd/picard_collecthsmetrics_test_picard_collecthsmetrics/work/conda/env-2bd1fde7df90cefe945ae19f31c1dc35 bioconda::picard=2.26.4
  status : 1
  message:
    PaddingError: Placeholder of length '80' too short in package /home/mei.wu/tmp/pytest_workflow_dyq_gnsd/picard_collecthsmetrics_test_picard_collecthsmetrics/work/conda/env-2bd1fde7df90cefe945ae19f31c1dc35/bin/Rscript.
    The package must be rebuilt with conda-build > 2.0.
```

2021-11-10 08:41 UTC, sguizard requested changes
Looks good to me overall. Just small modifications and one comment about the meta.yml

2021-11-10 08:41 UTC, sguizard commented on modules/picard/collecthsmetrics/main.nf
> +    path "versions.yml"                     , emit: versions
```suggestion
    tuple val(meta), path("*collecthsmetrics.txt"), emit: hs_metrics
    path "versions.yml"                           , emit: versions
```

2021-11-10 08:41 UTC, sguizard commented on modules/picard/collecthsmetrics/meta.yml
> +  - bam:
```suggestion
  - hs_metrics:
```

2021-11-10 08:41 UTC, sguizard commented on tests/modules/picard/collecthsmetrics/test.yml
> +    - path: output/picard/test_collecthsmetrics.txt
The md5sum could'nt be computed?

2021-11-10 08:56 UTC, projectoriented commented on tests/modules/picard/collecthsmetrics/test.yml
> +    - path: output/picard/test_collecthsmetrics.txt
Unfortunately not, it was too variable.

2021-11-10 09:26 UTC, sguizard approved these changes

2021-11-10 09:26 UTC, sguizard commented
@projectoriented Thanks for the contribution!

2021-11-10 09:52 UTC, merged